let
    Fuente = Csv.Document(Binary.FromText("TWVzLEFuaW8sTWVzX251bWVybyxNZXNfbm9tYnJlLEFuaW9fbWVzLFRyaW1lc3RyZSxEaWFzX21lcyxDb25fcHJvZHVjY2lvbixDb25fcHJlY2lvCjIwMjEtMDEtMDEsMjAyMSwxLGVuZXJvLDIwMjEtMDEsVDEsMzEsMCwxCjIwMjEtMDItMDEsMjAyMSwyLGZlYnJlcm8sMjAyMS0wMixUMSwyOCwwLDEKMjAyMS0wMy0wMSwyMDIxLDMsbWFyem8sMjAyMS0wMyxUMSwzMSwwLDEKMjAyMS0wNC0wMSwyMDIxLDQsYWJyaWwsMjAyMS0wNCxUMiwzMCwwLDEKMjAyMS0wNS0wMSwyMDIxLDUsbWF5bywyMDIxLTA1LFQyLDMxLDAsMQoyMDIxLTA2LTAxLDIwMjEsNixqdW5pbywyMDIxLTA2LFQyLDMwLDAsMQoyMDIxLTA3LTAxLDIwMjEsNyxqdWxpbywyMDIxLTA3LFQzLDMxLDAsMQoyMDIxLTA4LTAxLDIwMjEsOCxhZ29zdG8sMjAyMS0wOCxUMywzMSwwLDEKMjAyMS0wOS0wMSwyMDIxLDksc2VwdGllbWJyZSwyMDIxLTA5LFQzLDMwLDAsMQoyMDIxLTEwLTAxLDIwMjEsMTAsb2N0dWJyZSwyMDIxLTEwLFQ0LDMxLDAsMQoyMDIxLTExLTAxLDIwMjEsMTEsbm92aWVtYnJlLDIwMjEtMTEsVDQsMzAsMCwxCjIwMjEtMTItMDEsMjAyMSwxMixkaWNpZW1icmUsMjAyMS0xMixUNCwzMSwwLDEKMjAyMi0wMS0wMSwyMDIyLDEsZW5lcm8sMjAyMi0wMSxUMSwzMSwxLDEKMjAyMi0wMi0wMSwyMDIyLDIsZmVicmVybywyMDIyLTAyLFQxLDI4LDEsMQoyMDIyLTAzLTAxLDIwMjIsMyxtYXJ6bywyMDIyLTAzLFQxLDMxLDEsMQoyMDIyLTA0LTAxLDIwMjIsNCxhYnJpbCwyMDIyLTA0LFQyLDMwLDEsMQoyMDIyLTA1LTAxLDIwMjIsNSxtYXlvLDIwMjItMDUsVDIsMzEsMSwxCjIwMjItMDYtMDEsMjAyMiw2LGp1bmlvLDIwMjItMDYsVDIsMzAsMSwxCjIwMjItMDctMDEsMjAyMiw3LGp1bGlvLDIwMjItMDcsVDMsMzEsMSwxCjIwMjItMDgtMDEsMjAyMiw4LGFnb3N0bywyMDIyLTA4LFQzLDMxLDEsMQoyMDIyLTA5LTAxLDIwMjIsOSxzZXB0aWVtYnJlLDIwMjItMDksVDMsMzAsMSwxCjIwMjItMTAtMDEsMjAyMiwxMCxvY3R1YnJlLDIwMjItMTAsVDQsMzEsMSwxCjIwMjItMTEtMDEsMjAyMiwxMSxub3ZpZW1icmUsMjAyMi0xMSxUNCwzMCwxLDEKMjAyMi0xMi0wMSwyMDIyLDEyLGRpY2llbWJyZSwyMDIyLTEyLFQ0LDMxLDEsMQoyMDIzLTAxLTAxLDIwMjMsMSxlbmVybywyMDIzLTAxLFQxLDMxLDEsMQoyMDIzLTAyLTAxLDIwMjMsMixmZWJyZXJvLDIwMjMtMDIsVDEsMjgsMSwxCjIwMjMtMDMtMDEsMjAyMywzLG1hcnpvLDIwMjMtMDMsVDEsMzEsMSwxCjIwMjMtMDQtMDEsMjAyMyw0LGFicmlsLDIwMjMtMDQsVDIsMzAsMSwxCjIwMjMtMDUtMDEsMjAyMyw1LG1heW8sMjAyMy0wNSxUMiwzMSwxLDEKMjAyMy0wNi0wMSwyMDIzLDYsanVuaW8sMjAyMy0wNixUMiwzMCwxLDEKMjAyMy0wNy0wMSwyMDIzLDcsanVsaW8sMjAyMy0wNyxUMywzMSwxLDEKMjAyMy0wOC0wMSwyMDIzLDgsYWdvc3RvLDIwMjMtMDgsVDMsMzEsMSwxCjIwMjMtMDktMDEsMjAyMyw5LHNlcHRpZW1icmUsMjAyMy0wOSxUMywzMCwxLDEKMjAyMy0xMC0wMSwyMDIzLDEwLG9jdHVicmUsMjAyMy0xMCxUNCwzMSwxLDEKMjAyMy0xMS0wMSwyMDIzLDExLG5vdmllbWJyZSwyMDIzLTExLFQ0LDMwLDEsMQoyMDIzLTEyLTAxLDIwMjMsMTIsZGljaWVtYnJlLDIwMjMtMTIsVDQsMzEsMSwxCjIwMjQtMDEtMDEsMjAyNCwxLGVuZXJvLDIwMjQtMDEsVDEsMzEsMSwxCjIwMjQtMDItMDEsMjAyNCwyLGZlYnJlcm8sMjAyNC0wMixUMSwyOSwxLDEKMjAyNC0wMy0wMSwyMDI0LDMsbWFyem8sMjAyNC0wMyxUMSwzMSwxLDEKMjAyNC0wNC0wMSwyMDI0LDQsYWJyaWwsMjAyNC0wNCxUMiwzMCwxLDEKMjAyNC0wNS0wMSwyMDI0LDUsbWF5bywyMDI0LTA1LFQyLDMxLDEsMQoyMDI0LTA2LTAxLDIwMjQsNixqdW5pbywyMDI0LTA2LFQyLDMwLDEsMQoyMDI0LTA3LTAxLDIwMjQsNyxqdWxpbywyMDI0LTA3LFQzLDMxLDEsMQoyMDI0LTA4LTAxLDIwMjQsOCxhZ29zdG8sMjAyNC0wOCxUMywzMSwxLDEKMjAyNC0wOS0wMSwyMDI0LDksc2VwdGllbWJyZSwyMDI0LTA5LFQzLDMwLDEsMQoyMDI0LTEwLTAxLDIwMjQsMTAsb2N0dWJyZSwyMDI0LTEwLFQ0LDMxLDEsMQoyMDI0LTExLTAxLDIwMjQsMTEsbm92aWVtYnJlLDIwMjQtMTEsVDQsMzAsMSwxCjIwMjQtMTItMDEsMjAyNCwxMixkaWNpZW1icmUsMjAyNC0xMixUNCwzMSwxLDEKMjAyNS0wMS0wMSwyMDI1LDEsZW5lcm8sMjAyNS0wMSxUMSwzMSwxLDEKMjAyNS0wMi0wMSwyMDI1LDIsZmVicmVybywyMDI1LTAyLFQxLDI4LDEsMQoyMDI1LTAzLTAxLDIwMjUsMyxtYXJ6bywyMDI1LTAzLFQxLDMxLDEsMQoyMDI1LTA0LTAxLDIwMjUsNCxhYnJpbCwyMDI1LTA0LFQyLDMwLDEsMQoyMDI1LTA1LTAxLDIwMjUsNSxtYXlvLDIwMjUtMDUsVDIsMzEsMSwxCjIwMjUtMDYtMDEsMjAyNSw2LGp1bmlvLDIwMjUtMDYsVDIsMzAsMSwxCjIwMjUtMDctMDEsMjAyNSw3LGp1bGlvLDIwMjUtMDcsVDMsMzEsMSwxCjIwMjUtMDgtMDEsMjAyNSw4LGFnb3N0bywyMDI1LTA4LFQzLDMxLDEsMQoyMDI1LTA5LTAxLDIwMjUsOSxzZXB0aWVtYnJlLDIwMjUtMDksVDMsMzAsMSwxCjIwMjUtMTAtMDEsMjAyNSwxMCxvY3R1YnJlLDIwMjUtMTAsVDQsMzEsMSwxCjIwMjUtMTEtMDEsMjAyNSwxMSxub3ZpZW1icmUsMjAyNS0xMSxUNCwzMCwxLDEKMjAyNS0xMi0wMSwyMDI1LDEyLGRpY2llbWJyZSwyMDI1LTEyLFQ0LDMxLDEsMQoyMDI2LTAxLTAxLDIwMjYsMSxlbmVybywyMDI2LTAxLFQxLDMxLDEsMQoyMDI2LTAyLTAxLDIwMjYsMixmZWJyZXJvLDIwMjYtMDIsVDEsMjgsMSwxCjIwMjYtMDMtMDEsMjAyNiwzLG1hcnpvLDIwMjYtMDMsVDEsMzEsMSwxCjIwMjYtMDQtMDEsMjAyNiw0LGFicmlsLDIwMjYtMDQsVDIsMzAsMSwxCjIwMjYtMDUtMDEsMjAyNiw1LG1heW8sMjAyNi0wNSxUMiwzMSwxLDEKMjAyNi0wNi0wMSwyMDI2LDYsanVuaW8sMjAyNi0wNixUMiwzMCwxLDEKMjAyNi0wNy0wMSwyMDI2LDcsanVsaW8sMjAyNi0wNyxUMywzMSwxLDEKMjAyNi0wOC0wMSwyMDI2LDgsYWdvc3RvLDIwMjYtMDgsVDMsMzEsMSwwCg==", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Fuente, [PromoteAllScalars=true]),
    Nulos = Table.ReplaceValue(Encabezados, "", null, Replacer.ReplaceValue, Table.ColumnNames(Encabezados)),
    Tipos = Table.TransformColumnTypes(Nulos, {{"Mes", type date}, {"Anio", Int64.Type}, {"Mes_numero", Int64.Type}, {"Mes_nombre", type text}, {"Anio_mes", type text}, {"Trimestre", type text}, {"Dias_mes", Int64.Type}, {"Con_produccion", Int64.Type}, {"Con_precio", Int64.Type}}, "en-US")
in
    Tipos
