let
    Fuente = Csv.Document(Binary.FromText("QWN0aXZvLE5vbWJyZSxDYXRhbG9nb19mYWx0YW50ZSxFdGlxdWV0YSxHcnVwb192b2x1bWVuCkFNLEFtaXN0YWQsMCxBTSB8IEFtaXN0YWQsUmVzdG8gZGUgYWN0aXZvcwpBUCxBcGFpa2EsMCxBUCB8IEFwYWlrYSxSZXN0byBkZSBhY3Rpdm9zCkFVLEF1Y2EsMCxBVSB8IEF1Y2EsU0EgKyBBVSArIFNICkNVLEN1eWFiZW5vLDAsQ1UgfCBDdXlhYmVubyxSZXN0byBkZSBhY3Rpdm9zCkVZLEVkw6luIFl1dHVyaSwwLEVZIHwgRWTDqW4gWXV0dXJpLFJlc3RvIGRlIGFjdGl2b3MKSU4sSW5kaWxsYW5hLDAsSU4gfCBJbmRpbGxhbmEsUmVzdG8gZGUgYWN0aXZvcwpJVFQsSXNocGluZ28tVGlwdXRpbmktVGFtYm9jb2NoYSwwLElUVCB8IElzaHBpbmdvLVRpcHV0aW5pLVRhbWJvY29jaGEsUmVzdG8gZGUgYWN0aXZvcwpMQSxMYWdvIEFncmlvLDAsTEEgfCBMYWdvIEFncmlvLFJlc3RvIGRlIGFjdGl2b3MKTEksTGliZXJ0YWRvciwwLExJIHwgTGliZXJ0YWRvcixSZXN0byBkZSBhY3Rpdm9zCk9ZLE9zbyBZdXJhbHBhLDAsT1kgfCBPc28gWXVyYWxwYSxSZXN0byBkZSBhY3Rpdm9zClBBLFBhbG8gQXp1bCwwLFBBIHwgUGFsbyBBenVsLFJlc3RvIGRlIGFjdGl2b3MKU0EsU2FjaGEsMCxTQSB8IFNhY2hhLFNBICsgQVUgKyBTSApTSCxTaHVzaHVmaW5kaSwwLFNIIHwgU2h1c2h1ZmluZGksU0EgKyBBVSArIFNICkFCMTYsQUIxNiAoc2luIGNhdMOhbG9nbyksMSxBQjE2IHwgQUIxNiAoc2luIGNhdMOhbG9nbyksUmVzdG8gZGUgYWN0aXZvcwpBVixBbWF6b25pYSBWaXZhLDAsQVYgfCBBbWF6b25pYSBWaXZhLFJlc3RvIGRlIGFjdGl2b3MKQUlULEFtby1Jcm8tVGl2YWN1bm8sMCxBSVQgfCBBbW8tSXJvLVRpdmFjdW5vLFJlc3RvIGRlIGFjdGl2b3MK", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Fuente, [PromoteAllScalars=true]),
    Nulos = Table.ReplaceValue(Encabezados, "", null, Replacer.ReplaceValue, Table.ColumnNames(Encabezados)),
    Tipos = Table.TransformColumnTypes(Nulos, {{"Activo", type text}, {"Nombre", type text}, {"Catalogo_faltante", Int64.Type}, {"Etiqueta", type text}, {"Grupo_volumen", type text}}, "en-US")
in
    Tipos
