let
    Fuente = Csv.Document(Binary.FromText("TWVzLENhbWJpb19jcnVkbyxDYW1iaW9fcHJlY2lvCjIwMjItMDItMDEsMC4wNDE0NDU5MzUsMC4wOTA2OTgyNzQKMjAyMi0wMy0wMSwwLjA0Nzk5MzgwMywwLjE4NTY4MzkxMgoyMDIyLTA0LTAxLDAuMDAwNzcxODk3LC0wLjA1NjU4NDk3NwoyMDIyLTA1LTAxLC0wLjAwMjk2OTY4NCwwLjA2OTc5OTM2NgoyMDIyLTA2LTAxLC0wLjE3NjI2ODIxNCwwLjAzMDUwMDQ0NAoyMDIyLTA3LTAxLDAuMTg2NzQ0NjU4LC0wLjE2MjI2MDUzNgoyMDIyLTA4LTAxLDAuMDI0NTMzNzEyLC0wLjA0Nzc5MzI3NwoyMDIyLTA5LTAxLC0wLjAwMjk1MzIxMCwtMC4wNjgyMDM2NTAKMjAyMi0xMC0wMSwwLjAwNTYwNjIzOCwwLjAzNzUwMDAwMAoyMDIyLTExLTAxLC0wLjAxMDg5NDgxNywtMC4wNjM5NjcyMDkKMjAyMi0xMi0wMSwwLjAwODc3NDUyMywtMC4wODE3NDA5NzcKMjAyMy0wMS0wMSwwLjAwNDI3ODYwOSwtMC4wNTkxMDQwNDYKMjAyMy0wMi0wMSwtMC4wOTYwMzgwNjUsLTAuMDEzOTc2MzQ4CjIwMjMtMDMtMDEsLTAuMDA0NTcwMDc0LC0wLjA1MzU4MjU1NQoyMDIzLTA0LTAxLDAuMDc1ODM1NjUxLDAuMTMxMDA3MjQyCjIwMjMtMDUtMDEsMC4wMDY1NzIwNDEsLTAuMTA2OTU1NzYzCjIwMjMtMDYtMDEsMC4wMDMzMzc4NDYsLTAuMDUzNjA5MjU1CjIwMjMtMDctMDEsMC4wMTUxNTk1NjIsMC4xMjkxMzIyMzEKMjAyMy0wOC0wMSwwLjAxMzMzOTIwNywwLjEzODMwNDM2MQoyMDIzLTA5LTAxLDAuMDA2MTExODEwLDAuMTA4MjM4NDQ2CjIwMjMtMTAtMDEsLTAuMDAxMzQ3MjI4LC0wLjA1MzY2ODU2MAoyMDIzLTExLTAxLDAuMDE1NDc2ODA2LC0wLjA4ODAwNjEzMQoyMDIzLTEyLTAxLC0wLjAwOTc1OTkzMSwtMC4xMDAxNDAwNTYKMjAyNC0wMS0wMSwwLjAxNjk4MTM1OCwwLjAxNjk2NDk4MQoyMDI0LTAyLTAxLC0wLjAxNzc4MDg3NiwwLjA3MDg2MDExNgoyMDI0LTAzLTAxLC0wLjAwOTgzNjE5MSwwLjA1MTQ1MDYyMgoyMDI0LTA0LTAxLC0wLjAwMzYyNjUxMCwwLjA1NTA0OTYxMwoyMDI0LTA1LTAxLC0wLjAwNjA2ODAxMCwtMC4wNzQzMzY1MTEKMjAyNC0wNi0wMSwtMC4wOTg1MTUzMzEsMC4wMDQwMzYxODcKMjAyNC0wNy0wMSwwLjA1MzQzNzQ4NiwwLjAzMjg1Mjc4NgoyMDI0LTA4LTAxLDAuMDIwMDUwMTg2LC0wLjA4NTYyNjA5MAoyMDI0LTA5LTAxLC0wLjAyMDI3NzEwNiwtMC4wODUxMzEzNjcKMjAyNC0xMC0wMSwwLjAwNTMwNjc4OCwwLjA0ODEzMDkxNgoyMDI0LTExLTAxLDAuMDA2MzI4MDM1LC0wLjA2ODg4MTA2NQoyMDI0LTEyLTAxLDAuMDA4ODkwOTA3LDAuMDIxMzcxMDM0CjIwMjUtMDEtMDEsMC4wMDI1MTk5OTcsMC4wODMyMTI2MTkKMjAyNS0wMi0wMSwtMC4wMTI0MzkwNzYsLTAuMDM2ODQ5OTI2CjIwMjUtMDMtMDEsLTAuMDMxMjI1Nzk1LC0wLjA1NDE0OTk1NAoyMDI1LTA0LTAxLDAuMDM1MDIyOTg5LC0wLjA4MTIyNjU1NAoyMDI1LTA1LTAxLC0wLjAxMzU2NjYxNCwtMC4wMjI1NDU3MTMKMjAyNS0wNi0wMSwwLjAwMzY4NTc2MywwLjA5OTE2NDU0OAoyMDI1LTA3LTAxLC0wLjcyOTE4MTQwNiwtMC4wNDExNDM0MjQKMjAyNS0wOC0wMSwyLjY2ODU2MDE2NCwwLjAwODYxNjIzMwoyMDI1LTA5LTAxLDAuMDExMTgzMjAwLC0wLjAxNDM1MTYxNQoyMDI1LTEwLTAxLC0wLjAwMDU2NzkzMSwtMC4wMzgzMDgxOTkKMjAyNS0xMS0wMSwtMC4wMTgyMDc4NzcsLTAuMDM5ODM0MTc0CjIwMjUtMTItMDEsLTAuMDAxOTIyNjIzLC0wLjAyNTM0MjU5NAoyMDI2LTAxLTAxLDAuMDAwMTIyODczLDAuMDIyNzI3MjczCjIwMjYtMDItMDEsLTAuMDEzMjM5NjU3LDAuMDc0NTc2MjcxCjIwMjYtMDMtMDEsLTAuMDAxOTA0NDY5LDAuNDkzNTE1NTk4CjIwMjYtMDQtMDEsLTAuMDE3NDM3OTk1LDAuMDQ5NTE4ODkyCjIwMjYtMDUtMDEsMC4wMTIwOTk2OTgsMC4wNDExNDQ5MDIKMjAyNi0wNi0wMSwwLjAwMTE5Mzk4OCwtMC4xNTEzMTAxMzcKMjAyNi0wNy0wMSwwLjAwMTg1OTI4MCwtMC4wNTk3MjQxNTUK", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Fuente, [PromoteAllScalars=true]),
    Nulos = Table.ReplaceValue(Encabezados, "", null, Replacer.ReplaceValue, Table.ColumnNames(Encabezados)),
    Tipos = Table.TransformColumnTypes(Nulos, {{"Mes", type date}, {"Cambio_crudo", type number}, {"Cambio_precio", type number}}, "en-US")
in
    Tipos
