let
    Fuente = Csv.Document(Binary.FromText("TWVzLENydWRvX2JibCxEaWFzX21lcyxOX2FjdGl2b3MKMjAyMi0wMS0wMSw4NzkyNDg0LjIxOTk5OTk5OSwzMSwxMQoyMDIyLTAyLTAxLDgyNzA3NDUuNjMwMDAwMDAxLDI4LDExCjIwMjItMDMtMDEsOTU5NjM3MS4yNjAwMDAwMDAsMzEsMTEKMjAyMi0wNC0wMSw5MjkzOTc5LjM1OTk5OTk5OSwzMCwxMQoyMDIyLTA1LTAxLDk1NzUyNTguNDgwMDAwMDAwLDMxLDExCjIwMjItMDYtMDEsNzYzMzAxMS4wNzAwMDAwMDAsMzAsMTEKMjAyMi0wNy0wMSw5MzYwMzgyLjk0OTk5OTk5OSwzMSwxMQoyMDIyLTA4LTAxLDk1OTAwMjcuODkwMDAwMDAxLDMxLDExCjIwMjItMDktMDEsOTI1MzI2NC4zODAwMDAwMDEsMzAsMTEKMjAyMi0xMC0wMSw5NjE1MzExLjczMDAwMDAwMCwzMSwxMQoyMDIyLTExLTAxLDkyMDM3NjIuNTgwMDAwMDAwLDMwLDExCjIwMjItMTItMDEsOTU5NDAwNS4yNTAwMDAwMDAsMzEsMTEKMjAyMy0wMS0wMSw5NjM1MDU0LjI1MDAwMDAwMCwzMSwxMQoyMDIzLTAyLTAxLDc4NjY4NDUuOTMwMDAwMDAwLDI4LDExCjIwMjMtMDMtMDEsODY2OTkxOC4xOTk5OTk5OTksMzEsMTEKMjAyMy0wNC0wMSw5MDI2NTIyLjk4OTk5OTk5OCwzMCwxMQoyMDIzLTA1LTAxLDkzODg3MDcuMTg5OTk5OTk4LDMxLDExCjIwMjMtMDYtMDEsOTExNjE3Mi44MTk5OTk5OTgsMzAsMTEKMjAyMy0wNy0wMSw5NTYyODQ5LjAxMDAwMDAwMCwzMSwxMQoyMDIzLTA4LTAxLDk2OTA0MDkuODMwMDAwMDAwLDMxLDExCjIwMjMtMDktMDEsOTQzNTEzMS4zOTAwMDAwMDEsMzAsMTEKMjAyMy0xMC0wMSw5NzM2NTAwLjc4OTk5OTk5OSwzMSwxMQoyMDIzLTExLTAxLDk1NjgyNDkuMDkwMDAwMDAwLDMwLDExCjIwMjMtMTItMDEsOTc5MDY5Mi40MjUwMDAwMDEsMzEsMTEKMjAyNC0wMS0wMSw5OTU2OTUxLjY4MDAwMDAwMCwzMSwxMQoyMDI0LTAyLTAxLDkxNDg5NDYuNTI5OTk5OTk5LDI5LDExCjIwMjQtMDMtMDEsOTY4MzcxMS4zMTAwMDAwMDEsMzEsMTEKMjAyNC0wNC0wMSw5MzM3MzQ4LjI4OTk5OTk5OSwzMCwxMQoyMDI0LTA1LTAxLDk1OTAwNDUuNDcwMDAwMDAxLDMxLDExCjIwMjQtMDYtMDEsODM2NjM5OS4wMDAwMDAwMDEsMzAsMTEKMjAyNC0wNy0wMSw5MTA3MjYwLjkzOTk5OTk5OSwzMSwxMQoyMDI0LTA4LTAxLDkyODk4NjMuMjIwMDAwMDAxLDMxLDExCjIwMjQtMDktMDEsODgwNzg5NS4xNzAwMDAwMDAsMzAsMTEKMjAyNC0xMC0wMSw5MTQ5NzkxLjM1OTk5OTk5OSwzMSwxMQoyMDI0LTExLTAxLDg5MTA2NjkuMjUwMDAwMDAwLDMwLDExCjIwMjQtMTItMDEsOTI4OTU1Ni4yODk5OTk5OTksMzEsMTEKMjAyNS0wMS0wMSw5MzEyOTY1LjkzOTk5OTk5OSwzMSwxMQoyMDI1LTAyLTAxLDgzMDcwNzcuMjYwMDAwMDAxLDI4LDExCjIwMjUtMDMtMDEsODkwOTkzMy44MzAwMDAwMDAsMzEsMTEKMjAyNS0wNC0wMSw4OTI0NTAyLjkxMDAwMDAwMCwzMCwxMQoyMDI1LTA1LTAxLDkwOTY4NzUuMjEwMDAwMDAxLDMxLDExCjIwMjUtMDYtMDEsODgzNTg3NC45NzAwMDAwMDEsMzAsMTEKMjAyNS0wNy0wMSwyNDcyNjgzLjIxMDAwMDAwMCwzMSwxMQoyMDI1LTA4LTAxLDkwNzExODcuMTIzMDAwMDAwLDMxLDExCjIwMjUtMDktMDEsODg3Njc0MC42NzAwMDAwMDIsMzAsMTEKMjAyNS0xMC0wMSw5MTY3NDIyLjYwMDAwMDAwMCwzMSwxMQoyMDI1LTExLTAxLDg3MTAxNjQuNDgwMDAwMDAwLDMwLDExCjIwMjUtMTItMDEsODk4MzE5OC43MjAwMDAwMDEsMzEsMTEKMjAyNi0wMS0wMSw4OTg0MzAyLjUxMDAwMDAwMCwzMSwxMQoyMDI2LTAyLTAxLDgwMDc0MTYuMDAwMDAwMDAwLDI4LDExCjIwMjYtMDMtMDEsODg0ODQ2OS42NDAwMDAwMDEsMzEsMTEKMjAyNi0wNC0wMSw4NDEzNzEyLjk2OTk5OTk5OSwzMCwxMQoyMDI2LTA1LTAxLDg3OTkzNjYuOTAwMDAwMDAwLDMxLDExCjIwMjYtMDYtMDEsODUyNTY4My43ODAwMDAwMDEsMzAsMTEKMjAyNi0wNy0wMSw4ODI2MjUzLjI2MDAwMDAwMCwzMSwxMQoyMDI2LTA4LTAxLDg4Nzg4MzIuNDM5OTk5OTk5LDMxLDExCg==", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Fuente, [PromoteAllScalars=true]),
    Nulos = Table.ReplaceValue(Encabezados, "", null, Replacer.ReplaceValue, Table.ColumnNames(Encabezados)),
    Tipos = Table.TransformColumnTypes(Nulos, {{"Mes", type date}, {"Crudo_bbl", type number}, {"Dias_mes", Int64.Type}, {"N_activos", Int64.Type}}, "en-US")
in
    Tipos
