let
    Fuente = Csv.Document(Binary.FromText("QWN0aXZvLE5fMjAyNixOXzIwMjUsQnBkXzIwMjYsQnBkXzIwMjUsQ2FtYmlvX3BjdCxDYW1iaW9fYnBkLFJlc3VsdGFkbyxQcmlvcmlkYWQKSU4sOCw4LDEyNTU1LjY5MjEzOTkxOCwxMzM5My4zNjExMTExMTEsLTAuMDYyNTQzNTk2LC04MzcuNjY4OTcxMTkzLERlc2NlbnNvLDEgwrcgSW52ZXN0aWdhciBjYcOtZGEKQVYsOCw4LDIyLjYxODg4ODg4OSwyNi40MTcxMTkzNDIsLTAuMTQzNzc5MTMxLC0zLjc5ODIzMDQ1MyxEZXNjZW5zbywyIMK3IFZpZ2lsYXIgZGVzY2Vuc28KQU0sOCw4LDI3LjU4NDg5NzExOSwyOC41NDYxNDQwMzMsLTAuMDMzNjczNDQyLC0wLjk2MTI0NjkxNCxEZXNjZW5zbywyIMK3IFZpZ2lsYXIgZGVzY2Vuc28KQVUsOCw4LDYxNjE4LjY1NjI5NjI5Niw2MDc0OC4zNzQ1MjY3NDksMC4wMTQzMjYwMDksODcwLjI4MTc2OTU0NyxBdW1lbnRvLDQgwrcgU2VndWlyIGV2b2x1Y2nDs24KQ1UsOCw4LDE3NzUxLjA2OTAxMjM0NiwxNjUyMi45OTE3MjgzOTUsMC4wNzQzMjUzNTksMTIyOC4wNzcyODM5NTEsQXVtZW50byw0IMK3IFNlZ3VpciBldm9sdWNpw7NuCklUVCw4LDgsNDE1NDAuNDY1MjYzMzc0LDQwMTI2LjM1NzMyMDk4OCwwLjAzNTI0MTM3MywxNDE0LjEwNzk0MjM4NyxBdW1lbnRvLDQgwrcgU2VndWlyIGV2b2x1Y2nDs24KUEEsOCw4LDEzMDAyLjAxMTgxMDcwMCwxMTM0MC43OTE4NTE4NTIsMC4xNDY0ODE4MzEsMTY2MS4yMTk5NTg4NDgsQXVtZW50byw0IMK3IFNlZ3VpciBldm9sdWNpw7NuCkxJLDgsOCwxMDQxMS41OTc0MDc0MDcsODYzNC41MDQ3MzI1MTAsMC4yMDU4MTI5MjUsMTc3Ny4wOTI2NzQ4OTcsQXVtZW50byw0IMK3IFNlZ3VpciBldm9sdWNpw7NuCkVZLDgsOCwyOTI2OS45MTcxNTIyNjMsMjc0NjQuNDkxNjYyNTUxLDAuMDY1NzM2NzE2LDE4MDUuNDI1NDg5NzEyLEF1bWVudG8sNCDCtyBTZWd1aXIgZXZvbHVjacOzbgpMQSw4LDgsMTIxNzguNDU2ODMxMjc2LDEwMjQ4LjMwNjk5NTg4NSwwLjE4ODMzODQwOSwxOTMwLjE0OTgzNTM5MSxBdW1lbnRvLDQgwrcgU2VndWlyIGV2b2x1Y2nDs24KT1ksOCw4LDIwNjQwLjU4NDczMjUxMCwxNzc3MS41MzI4Mzk1MDYsMC4xNjE0NDA4ODAsMjg2OS4wNTE4OTMwMDQsQXVtZW50byw0IMK3IFNlZ3VpciBldm9sdWNpw7NuCkFQLDgsOCw2NzY2LjM3Njg4NDc3NCwzNDE1LjE1MTk2Mjk2MywwLjk4MTI4MTM0OCwzMzUxLjIyNDkyMTgxMSxBdW1lbnRvLDMgwrcgU29zdGVuZXIgYXVtZW50bwpTQSw4LDgsNzE1MzUuNTQwMjg4MDY2LDY3NzYwLjA3MDgyMzA0NSwwLjA1NTcxODIwNCwzNzc1LjQ2OTQ2NTAyMSxBdW1lbnRvLDMgwrcgU29zdGVuZXIgYXVtZW50bwpTSCw4LDgsNTQ4OTQuMjY2NzkwMTIzLDUwMDU1LjAyNjc0ODk3MSwwLjA5NjY3ODQwMyw0ODM5LjI0MDA0MTE1MixBdW1lbnRvLDMgwrcgU29zdGVuZXIgYXVtZW50bwo=", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Fuente, [PromoteAllScalars=true]),
    Nulos = Table.ReplaceValue(Encabezados, "", null, Replacer.ReplaceValue, Table.ColumnNames(Encabezados)),
    Tipos = Table.TransformColumnTypes(Nulos, {{"Activo", type text}, {"N_2026", Int64.Type}, {"N_2025", Int64.Type}, {"Bpd_2026", type number}, {"Bpd_2025", type number}, {"Cambio_pct", type number}, {"Cambio_bpd", type number}, {"Resultado", type text}, {"Prioridad", type text}}, "en-US")
in
    Tipos
