let
    Fuente = Csv.Document(Binary.FromText("TWVzLFByZWNpb19VU0RfYmJsCjIwMjEtMDEtMDEsNDguNjAwMDAwMDAwCjIwMjEtMDItMDEsNTUuNjEwMDAwMDAwCjIwMjEtMDMtMDEsNTguNzIwMDAwMDAwCjIwMjEtMDQtMDEsNTcuMjQwMDAwMDAwCjIwMjEtMDUtMDEsNjEuNTIwMDAwMDAwCjIwMjEtMDYtMDEsNjcuMjkwMDAwMDAwCjIwMjEtMDctMDEsNjYuODQwMDAwMDAwCjIwMjEtMDgtMDEsNjEuMTQwMDAwMDAwCjIwMjEtMDktMDEsNjQuNzQwMDAwMDAwCjIwMjEtMTAtMDEsNzUuMjAwMDAwMDAwCjIwMjEtMTEtMDEsNjguNDkwMDAwMDAwCjIwMjEtMTItMDEsNjAuMjgwMDAwMDAwCjIwMjItMDEtMDEsNzcuNjIwMDAwMDAwCjIwMjItMDItMDEsODQuNjYwMDAwMDAwCjIwMjItMDMtMDEsMTAwLjM4MDAwMDAwMAoyMDIyLTA0LTAxLDk0LjcwMDAwMDAwMAoyMDIyLTA1LTAxLDEwMS4zMTAwMDAwMDAKMjAyMi0wNi0wMSwxMDQuNDAwMDAwMDAwCjIwMjItMDctMDEsODcuNDYwMDAwMDAwCjIwMjItMDgtMDEsODMuMjgwMDAwMDAwCjIwMjItMDktMDEsNzcuNjAwMDAwMDAwCjIwMjItMTAtMDEsODAuNTEwMDAwMDAwCjIwMjItMTEtMDEsNzUuMzYwMDAwMDAwCjIwMjItMTItMDEsNjkuMjAwMDAwMDAwCjIwMjMtMDEtMDEsNjUuMTEwMDAwMDAwCjIwMjMtMDItMDEsNjQuMjAwMDAwMDAwCjIwMjMtMDMtMDEsNjAuNzYwMDAwMDAwCjIwMjMtMDQtMDEsNjguNzIwMDAwMDAwCjIwMjMtMDUtMDEsNjEuMzcwMDAwMDAwCjIwMjMtMDYtMDEsNTguMDgwMDAwMDAwCjIwMjMtMDctMDEsNjUuNTgwMDAwMDAwCjIwMjMtMDgtMDEsNzQuNjUwMDAwMDAwCjIwMjMtMDktMDEsODIuNzMwMDAwMDAwCjIwMjMtMTAtMDEsNzguMjkwMDAwMDAwCjIwMjMtMTEtMDEsNzEuNDAwMDAwMDAwCjIwMjMtMTItMDEsNjQuMjUwMDAwMDAwCjIwMjQtMDEtMDEsNjUuMzQwMDAwMDAwCjIwMjQtMDItMDEsNjkuOTcwMDAwMDAwCjIwMjQtMDMtMDEsNzMuNTcwMDAwMDAwCjIwMjQtMDQtMDEsNzcuNjIwMDAwMDAwCjIwMjQtMDUtMDEsNzEuODUwMDAwMDAwCjIwMjQtMDYtMDEsNzIuMTQwMDAwMDAwCjIwMjQtMDctMDEsNzQuNTEwMDAwMDAwCjIwMjQtMDgtMDEsNjguMTMwMDAwMDAwCjIwMjQtMDktMDEsNjIuMzMwMDAwMDAwCjIwMjQtMTAtMDEsNjUuMzMwMDAwMDAwCjIwMjQtMTEtMDEsNjAuODMwMDAwMDAwCjIwMjQtMTItMDEsNjIuMTMwMDAwMDAwCjIwMjUtMDEtMDEsNjcuMzAwMDAwMDAwCjIwMjUtMDItMDEsNjQuODIwMDAwMDAwCjIwMjUtMDMtMDEsNjEuMzEwMDAwMDAwCjIwMjUtMDQtMDEsNTYuMzMwMDAwMDAwCjIwMjUtMDUtMDEsNTUuMDYwMDAwMDAwCjIwMjUtMDYtMDEsNjAuNTIwMDAwMDAwCjIwMjUtMDctMDEsNTguMDMwMDAwMDAwCjIwMjUtMDgtMDEsNTguNTMwMDAwMDAwCjIwMjUtMDktMDEsNTcuNjkwMDAwMDAwCjIwMjUtMTAtMDEsNTUuNDgwMDAwMDAwCjIwMjUtMTEtMDEsNTMuMjcwMDAwMDAwCjIwMjUtMTItMDEsNTEuOTIwMDAwMDAwCjIwMjYtMDEtMDEsNTMuMTAwMDAwMDAwCjIwMjYtMDItMDEsNTcuMDYwMDAwMDAwCjIwMjYtMDMtMDEsODUuMjIwMDAwMDAwCjIwMjYtMDQtMDEsODkuNDQwMDAwMDAwCjIwMjYtMDUtMDEsOTMuMTIwMDAwMDAwCjIwMjYtMDYtMDEsNzkuMDMwMDAwMDAwCjIwMjYtMDctMDEsNzQuMzEwMDAwMDAwCg==", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Fuente, [PromoteAllScalars=true]),
    Nulos = Table.ReplaceValue(Encabezados, "", null, Replacer.ReplaceValue, Table.ColumnNames(Encabezados)),
    Tipos = Table.TransformColumnTypes(Nulos, {{"Mes", type date}, {"Precio_USD_bbl", type number}}, "en-US")
in
    Tipos
