let
    Fuente = Csv.Document(Binary.FromText("QWN0aXZvLE1lc19udW1lcm8sQ3J1ZG9fMjAyNSxDcnVkb18yMDI2LERpYXNfbWVzLE1lc19ub21icmUKQU0sMSw5NzIuMzYwMDAwMDAwLDg4My45NTAwMDAwMDAsMzEsZW5lCkFNLDIsODY2LjAzMDAwMDAwMCw4MzcuNTYwMDAwMDAwLDI4LGZlYgpBTSwzLDg1NS4wNjAwMDAwMDAsOTMzLjY3MDAwMDAwMCwzMSxtYXIKQU0sNCw4MjkuNzcwMDAwMDAwLDgxNy41MjAwMDAwMDAsMzAsYWJyCkFNLDUsODU3LjQyMDAwMDAwMCw4MTAuMTAwMDAwMDAwLDMxLG1heQpBTSw2LDgzMC4yNTAwMDAwMDAsNzgzLjA2MDAwMDAwMCwzMCxqdW4KQU0sNyw4NTguODQwMDAwMDAwLDgxNi4yMTAwMDAwMDAsMzEsanVsCkFNLDgsODY2Ljk4MzAwMDAwMCw4MjEuMDYwMDAwMDAwLDMxLGFnbwpBUCwxLDEwNjQ4NC41NDgwMDAwMDAsMTc5MjI4LjQ5NTAwMDAwMCwzMSxlbmUKQVAsMiw5OTYxMC42NjQwMDAwMDAsMTcyMzgyLjE5MDAwMDAwMCwyOCxmZWIKQVAsMywxMTg5ODIuMDA5MDAwMDAwLDIxMjE0MC4xOTEwMDAwMDAsMzEsbWFyCkFQLDQsMTExOTIzLjUyMDAwMDAwMCwyMTI5NzAuMzk1MDAwMDAwLDMwLGFicgpBUCw1LDExMzc0My42MTYwMDAwMDAsMjMzMjg5LjI3MzAwMDAwMCwzMSxtYXkKQVAsNiwxMTQzMjEuOTY0MDAwMDAwLDIxMTAyOC4zMjYwMDAwMDAsMzAsanVuCkFQLDcsNDEzMDYuODI5MDAwMDAwLDIwMDYxMy4wNjUwMDAwMDAsMzEsanVsCkFQLDgsMTIzNTA4Ljc3NzAwMDAwMCwyMjI1NzcuNjQ4MDAwMDAwLDMxLGFnbwpBVSwxLDIyNDc0NjcuMzcwMDAwMDAwLDE5MTYxMjYuNzQwMDAwMDAwLDMxLGVuZQpBVSwyLDE5NDc0MTguNDQwMDAwMDAwLDE3Mjg5NzEuNzQwMDAwMDAwLDI4LGZlYgpBVSwzLDE4ODg0MTQuNDgwMDAwMDAwLDE5MDE2NTQuNTUwMDAwMDAwLDMxLG1hcgpBVSw0LDIxNDc3NjkuOTEwMDAwMDAwLDE3NzQyNjguMTUwMDAwMDAwLDMwLGFicgpBVSw1LDIxMzAwMDkuMzEwMDAwMDAwLDE4NjM1MDUuMDEwMDAwMDAwLDMxLG1heQpBVSw2LDIwODcyMTguMTYwMDAwMDAwLDE4Mzk4NzAuMDEwMDAwMDAwLDMwLGp1bgpBVSw3LDIyNTA4OS4wMzAwMDAwMDAsMTk2NTIzMi42MzAwMDAwMDAsMzEsanVsCkFVLDgsMjA4ODQ2OC4zMTAwMDAwMDAsMTk4MzcwNC42NTAwMDAwMDAsMzEsYWdvCkFWLDEsMTIyNC41ODAwMDAwMDAsMzAzLjkwMDAwMDAwMCwzMSxlbmUKQVYsMiw3MzYuMTUwMDAwMDAwLDY0Ny41NjAwMDAwMDAsMjgsZmViCkFWLDMsODIwLjMwMDAwMDAwMCw4MDcuNjYwMDAwMDAwLDMxLG1hcgpBViw0LDg1Ny42MjAwMDAwMDAsNjk4LjIyMDAwMDAwMCwzMCxhYnIKQVYsNSw3MDMuNjUwMDAwMDAwLDc5Ny44ODAwMDAwMDAsMzEsbWF5CkFWLDYsOTA1LjAxMDAwMDAwMCw5NC40NDAwMDAwMDAsMzAsanVuCkFWLDcsMjY0LjcxMDAwMDAwMCwxMTI2LjU3MDAwMDAwMCwzMSxqdWwKQVYsOCw5MDcuMzQwMDAwMDAwLDEwMjAuMTYwMDAwMDAwLDMxLGFnbwpDVSwxLDU4NjQxMi40NzAwMDAwMDAsNTcyNjYyLjc3MDAwMDAwMCwzMSxlbmUKQ1UsMiw0OTg3NjUuNTUwMDAwMDAwLDUxMTc2OS44ODAwMDAwMDAsMjgsZmViCkNVLDMsNTQ2NjE4LjM5MDAwMDAwMCw1NTY1OTAuNjAwMDAwMDAwLDMxLG1hcgpDVSw0LDU0NDMxNy44NTAwMDAwMDAsNTI0NjIwLjk4MDAwMDAwMCwzMCxhYnIKQ1UsNSw1Nzc4ODAuODMwMDAwMDAwLDU0MTMxNi4xMjAwMDAwMDAsMzEsbWF5CkNVLDYsNTYyODQ5LjU0MDAwMDAwMCw1MTUwMjEuMDMwMDAwMDAwLDMwLGp1bgpDVSw3LDExNDI2OC42MTAwMDAwMDAsNTQyNTA3LjE0MDAwMDAwMCwzMSxqdWwKQ1UsOCw1ODM5NzMuNzUwMDAwMDAwLDU0OTAyMS4yNTAwMDAwMDAsMzEsYWdvCkVZLDEsOTI0MjY3LjE2MDAwMDAwMCw5NTk3MTkuNjA3MDAwMDAwLDMxLGVuZQpFWSwyLDgzOTMxNC45NzgwMDAwMDAsODgyNTQ1LjY2ODAwMDAwMCwyOCxmZWIKRVksMyw5MjI2NzcuMDExMDAwMDAwLDkzNjE5MS4yMjIwMDAwMDAsMzEsbWFyCkVZLDQsOTEwMzg2Ljg0NzAwMDAwMCw4ODUzOTcuNzc5MDAwMDAwLDMwLGFicgpFWSw1LDkzMzMzNy40MjAwMDAwMDAsOTA1OTM3LjgwNzAwMDAwMCwzMSxtYXkKRVksNiw4OTgxMTUuMjQ3MDAwMDAwLDg0NzcwMS43ODkwMDAwMDAsMzAsanVuCkVZLDcsMzE1Njk0LjYxMzAwMDAwMCw4NjAyMTQuODYzMDAwMDAwLDMxLGp1bApFWSw4LDkzMDA3OC4xOTgwMDAwMDAsODM0ODgxLjEzMzAwMDAwMCwzMSxhZ28KSU4sMSw0OTUyODYuNDgwMDAwMDAwLDQwMTI3MS40NjAwMDAwMDAsMzEsZW5lCklOLDIsNDQwNjQyLjEwMDAwMDAwMCwzMzU4NDYuNTEwMDAwMDAwLDI4LGZlYgpJTiwzLDQ2Mzk2NC40MjAwMDAwMDAsMzgwNjQ2LjAzMDAwMDAwMCwzMSxtYXIKSU4sNCw0MjI1NjAuNjUwMDAwMDAwLDM1MzA3My41MDAwMDAwMDAsMzAsYWJyCklOLDUsNDIxOTU3LjM2MDAwMDAwMCwzOTMwMzguNDIwMDAwMDAwLDMxLG1heQpJTiw2LDQxNDU2Ni44MDAwMDAwMDAsMzg2NjQ1Ljc5MDAwMDAwMCwzMCxqdW4KSU4sNywxNjY4NDUuMzQwMDAwMDAwLDM5NjkzMC4zMDAwMDAwMDAsMzEsanVsCklOLDgsNDI4NzYzLjYwMDAwMDAwMCw0MDM1ODEuMTgwMDAwMDAwLDMxLGFnbwpJVFQsMSwxMzk4NDQ2LjU3MjAwMDAwMCwxMzc5MDg3LjMzODAwMDAwMCwzMSxlbmUKSVRULDIsMTI0NzkxOS4zNDgwMDAwMDAsMTIwMDk5Mi43NzIwMDAwMDAsMjgsZmViCklUVCwzLDEzNjU4OTIuNDUwMDAwMDAwLDEzMTgwMzEuMDM3MDAwMDAwLDMxLG1hcgpJVFQsNCwxMzEyODQ5LjQ4MzAwMDAwMCwxMjM0MDkwLjk5NjAwMDAwMCwzMCxhYnIKSVRULDUsMTMzOTczMS42ODQwMDAwMDAsMTI3MTQ5Mi4wNzAwMDAwMDAsMzEsbWF5CklUVCw2LDEzMTI1NDEuMTM5MDAwMDAwLDEyMTczMDQuODg1MDAwMDAwLDMwLGp1bgpJVFQsNyw0MzA1ODMuMTg4MDAwMDAwLDEyMzA3MDIuNDcyMDAwMDAwLDMxLGp1bApJVFQsOCwxMzQyNzQwLjk2NTAwMDAwMCwxMjQyNjMxLjQ4OTAwMDAwMCwzMSxhZ28KTEEsMSwzMjgzMDkuODgwMDAwMDAwLDMzMjA0My42MzAwMDAwMDAsMzEsZW5lCkxBLDIsMjk2MDgwLjg0MDAwMDAwMCwyOTcxNDYuNjgwMDAwMDAwLDI4LGZlYgpMQSwzLDMyNzIyMy45MzAwMDAwMDAsMzIxMDQ4Ljc1MDAwMDAwMCwzMSxtYXIKTEEsNCwzMjU0OTQuNzcwMDAwMDAwLDMyNDg5My44NTAwMDAwMDAsMzAsYWJyCkxBLDUsMzU2NDQ1LjM1MDAwMDAwMCwzODI1NDYuODYwMDAwMDAwLDMxLG1heQpMQSw2LDM0NzU4OC44ODAwMDAwMDAsMzkwMTI2LjcyMDAwMDAwMCwzMCxqdW4KTEEsNywxNDU4NjIuMjkwMDAwMDAwLDQ1OTg3MC44NjAwMDAwMDAsMzEsanVsCkxBLDgsMzYzMzMyLjY2MDAwMDAwMCw0NTE2ODcuNjYwMDAwMDAwLDMxLGFnbwpMSSwxLDI4Njc3Mi44NDAwMDAwMDAsMzQxODkzLjgzMDAwMDAwMCwzMSxlbmUKTEksMiwyNDk2NjQuMjgwMDAwMDAwLDMwOTQ0MS43NzAwMDAwMDAsMjgsZmViCkxJLDMsMjk0MzkxLjg2MDAwMDAwMCwzMzE4NDMuNzUwMDAwMDAwLDMxLG1hcgpMSSw0LDI3ODg3OC41MzAwMDAwMDAsMzAwMzQzLjUzMDAwMDAwMCwzMCxhYnIKTEksNSwyODEzNTcuMTEwMDAwMDAwLDMwNzE5NC45NjAwMDAwMDAsMzEsbWF5CkxJLDYsMjU2NTYyLjIwMDAwMDAwMCwyOTkyOTYuNTgwMDAwMDAwLDMwLGp1bgpMSSw3LDEzNzY3OS41MzAwMDAwMDAsMzE5MzY1LjE1MDAwMDAwMCwzMSxqdWwKTEksOCwzMTI4NzguMzAwMDAwMDAwLDMyMDYzOC42MDAwMDAwMDAsMzEsYWdvCk9ZLDEsNTk0MjI3Ljc5MDAwMDAwMCw2MzYyMDcuNjQwMDAwMDAwLDMxLGVuZQpPWSwyLDU0NDczNy4wMjAwMDAwMDAsNTQ0NjQ0LjE5MDAwMDAwMCwyOCxmZWIKT1ksMyw1OTc3NTIuMDcwMDAwMDAwLDY0ODE3MC44NDAwMDAwMDAsMzEsbWFyCk9ZLDQsNTczNzc2LjQyMDAwMDAwMCw2MjUzMzMuNTcwMDAwMDAwLDMwLGFicgpPWSw1LDU4MjM2Ni40ODAwMDAwMDAsNjQ1ODgxLjYzMDAwMDAwMCwzMSxtYXkKT1ksNiw1NzA4MTguNzYwMDAwMDAwLDYzMTI1NS4zNzAwMDAwMDAsMzAsanVuCk9ZLDcsMjQ3MTY1LjYyMDAwMDAwMCw2NDgxNjkuNTcwMDAwMDAwLDMxLGp1bApPWSw4LDYwNzYzOC4zMjAwMDAwMDAsNjM1OTk5LjI4MDAwMDAwMCwzMSxhZ28KUEEsMSwzNzcwNzYuNzYwMDAwMDAwLDQwNzQ1OS42NTAwMDAwMDAsMzEsZW5lClBBLDIsMzQ1ODE3LjI4MDAwMDAwMCwzNTY3MDYuNDQwMDAwMDAwLDI4LGZlYgpQQSwzLDM4NDY3OS45MjAwMDAwMDAsMzg2NjY4LjY1MDAwMDAwMCwzMSxtYXIKUEEsNCwzNjg5MTkuNzcwMDAwMDAwLDM4MDg3Ny41MjAwMDAwMDAsMzAsYWJyClBBLDUsMzkwOTkwLjM3MDAwMDAwMCwzOTk5MzMuMTkwMDAwMDAwLDMxLG1heQpQQSw2LDM3NTA0OS40MzAwMDAwMDAsMzg3MzIzLjIzMDAwMDAwMCwzMCxqdW4KUEEsNywxMDAwODYuNjEwMDAwMDAwLDQxNzExNy4xMDAwMDAwMDAsMzEsanVsClBBLDgsNDEzMTkyLjI4MDAwMDAwMCw0MjM0MDMuMDkwMDAwMDAwLDMxLGFnbwpTQSwxLDIyOTU1NTEuNTkwMDAwMDAwLDIxODk3NjEuMDMwMDAwMDAwLDMxLGVuZQpTQSwyLDIwOTIzMjEuNTcwMDAwMDAwLDE5NjMyNzcuMjgwMDAwMDAwLDI4LGZlYgpTQSwzLDIzMjU3MDYuMTYwMDAwMDAwLDIxNzU1OTkuMTAwMDAwMDAwLDMxLG1hcgpTQSw0LDIyNTIyOTAuMTYwMDAwMDAwLDIxMjE5MTkuMDMwMDAwMDAwLDMwLGFicgpTQSw1LDIzMjQ2NDMuNjEwMDAwMDAwLDIyMzY5NjguMzIwMDAwMDAwLDMxLG1heQpTQSw2LDIyNDMwMDEuNDgwMDAwMDAwLDIxODk0NTMuNzEwMDAwMDAwLDMwLGp1bgpTQSw3LDY5MzEwNS4wMDAwMDAwMDAsMjI0NDU4NC43NjAwMDAwMDAsMzEsanVsClNBLDgsMjIzOTA3Ny42NDAwMDAwMDAsMjI2MTU3My4wNjAwMDAwMDAsMzEsYWdvClNILDEsMTc0MDA5Mi43NzAwMDAwMDAsMTc2MTczOC42NDAwMDAwMDAsMzEsZW5lClNILDIsMTU0NDQ1MS4yNjAwMDAwMDAsMTU4OTE2MS43NTAwMDAwMDAsMjgsZmViClNILDMsMTY1NDg4Mi4zMjAwMDAwMDAsMTY5MzM2Ny4yODAwMDAwMDAsMzEsbWFyClNILDQsMTY1NDIwNC4zMjAwMDAwMDAsMTYzOTI4NC42ODAwMDAwMDAsMzAsYWJyClNILDUsMTY2Mjc4NC44NDAwMDAwMDAsMTY5MDI2My4yNjAwMDAwMDAsMzEsbWF5ClNILDYsMTYxMjk2Ny41MTAwMDAwMDAsMTYzNTI1NS42MjAwMDAwMDAsMzAsanVuClNILDcsNjE3MjA4LjI5MDAwMDAwMCwxNjcwNzg5Ljg4MDAwMDAwMCwzMSxqdWwKU0gsOCwxNjc2NzgwLjE5MDAwMDAwMCwxNjU5NDQ1LjcyMDAwMDAwMCwzMSxhZ28K", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Encabezados = Table.PromoteHeaders(Fuente, [PromoteAllScalars=true]),
    Nulos = Table.ReplaceValue(Encabezados, "", null, Replacer.ReplaceValue, Table.ColumnNames(Encabezados)),
    Tipos = Table.TransformColumnTypes(Nulos, {{"Activo", type text}, {"Mes_numero", Int64.Type}, {"Crudo_2025", type number}, {"Crudo_2026", type number}, {"Dias_mes", Int64.Type}, {"Mes_nombre", type text}}, "en-US")
in
    Tipos
