{
  "name": "Petroleo_EDA",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "es-ES",
    "sourceQueryCulture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "Produccion",
        "lineageTag": "906a3ac9-7e0c-545b-82ed-ade488694e1f",
        "columns": [
          {
            "name": "Mes",
            "dataType": "dateTime",
            "sourceColumn": "Mes",
            "summarizeBy": "none",
            "lineageTag": "2b7dda79-64f6-52ec-a8fa-a31688c1f242",
            "formatString": "yyyy-MM-dd"
          },
          {
            "name": "Activo",
            "dataType": "string",
            "sourceColumn": "Activo",
            "summarizeBy": "none",
            "lineageTag": "836ccb71-cde7-5de1-8799-506c8bbca62c"
          },
          {
            "name": "Crudo_bbl",
            "dataType": "double",
            "sourceColumn": "Crudo_bbl",
            "summarizeBy": "none",
            "lineageTag": "254ea45d-bfe0-5c5f-82ab-66dabdd1fa10",
            "formatString": "#,0.00"
          },
          {
            "name": "Gas_miles_pies3",
            "dataType": "double",
            "sourceColumn": "Gas_miles_pies3",
            "summarizeBy": "none",
            "lineageTag": "741f5f80-d452-5f49-aa65-ae6eed099045",
            "formatString": "#,0.00"
          },
          {
            "name": "Crudo_diario_bbl",
            "dataType": "double",
            "sourceColumn": "Crudo_diario_bbl",
            "summarizeBy": "none",
            "lineageTag": "6ed84180-a2ae-5aee-a6ee-cefed1f4d265",
            "formatString": "#,0.00"
          },
          {
            "name": "Gas_diario_miles_pies3",
            "dataType": "double",
            "sourceColumn": "Gas_diario_miles_pies3",
            "summarizeBy": "none",
            "lineageTag": "21fe92b0-84a3-5271-9a8d-7432a7434a8c",
            "formatString": "#,0.00"
          },
          {
            "name": "Conflicto_crudo",
            "dataType": "int64",
            "sourceColumn": "Conflicto_crudo",
            "summarizeBy": "none",
            "lineageTag": "bc37c2ed-79ff-50ea-abfb-abeb068c0f8b",
            "formatString": "0"
          },
          {
            "name": "Conflicto_gas",
            "dataType": "int64",
            "sourceColumn": "Conflicto_gas",
            "summarizeBy": "none",
            "lineageTag": "178b28a8-dcd5-51ba-9506-3147a5e987fe",
            "formatString": "0"
          },
          {
            "name": "Atipico_crudo",
            "dataType": "int64",
            "sourceColumn": "Atipico_crudo",
            "summarizeBy": "none",
            "lineageTag": "9fb84f26-f096-5c73-9726-b78edcf5eb60",
            "formatString": "0"
          },
          {
            "name": "Atipico_gas",
            "dataType": "int64",
            "sourceColumn": "Atipico_gas",
            "summarizeBy": "none",
            "lineageTag": "ba4d64f6-96ed-55e2-b147-675b217f8fdb",
            "formatString": "0"
          },
          {
            "name": "Filas_origen",
            "dataType": "int64",
            "sourceColumn": "Filas_origen",
            "summarizeBy": "none",
            "lineageTag": "0f10eb52-3a95-5c94-8504-5e56aae5a957",
            "formatString": "0"
          },
          {
            "name": "Referencias_origen",
            "dataType": "string",
            "sourceColumn": "Referencias_origen",
            "summarizeBy": "none",
            "lineageTag": "a75a8c42-8b0c-5477-8a4d-ffd5abfc6581"
          }
        ],
        "partitions": [
          {
            "name": "Produccion",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Fuente = Csv.Document(Binary.FromText(\"TWVzLEFjdGl2byxDcnVkb19iYmwsR2FzX21pbGVzX3BpZXMzLENydWRvX2RpYXJpb19iYmwsR2FzX2RpYXJpb19taWxlc19waWVzMyxDb25mbGljdG9fY3J1ZG8sQ29uZmxpY3RvX2dhcyxBdGlwaWNvX2NydWRvLEF0aXBpY29fZ2FzLEZpbGFzX29yaWdlbixSZWZlcmVuY2lhc19vcmlnZW4KMjAyMi0wMS0wMSxBTSwxNTUzLjQ0MDAwMDAwMCw3Njg5OTMuNDgwMDAwMDAwLDUwLjExMDk2Nzc0MiwyNDgwNi4yNDEyOTAzMjMsMCwwLDEsMCwxLDIKMjAyMi0wMS0wMSxBUCwxMTEzMDMuNTI1MDAwMDAwLDEwOTgzLjMxODAwMDAwMCwzNTkwLjQzNjI5MDMyMywzNTQuMzAwNTgwNjQ1LDAsMCwwLDAsMSwzCjIwMjItMDEtMDEsQVUsMjIwMTI5OS41MjAwMDAwMDAsMjg0ODkzLjExMzAwMDAwMCw3MTAwOS42NjE5MzU0ODQsOTE5MC4xMDA0MTkzNTUsMCwwLDAsMCwxLDQKMjAyMi0wMS0wMSxDVSw3NDMzMzUuMzYwMDAwMDAwLDE1NjcwMi41MjAwMDAwMDAsMjM5NzguNTYwMDAwMDAwLDUwNTQuOTIwMDAwMDAwLDAsMCwxLDAsMSw1CjIwMjItMDEtMDEsRVksODI5MjcwLjY0MDAwMDAwMCwxMTc5MDcuODMyMDAwMDAwLDI2NzUwLjY2NTgwNjQ1MiwzODAzLjQ3ODQ1MTYxMywwLDAsMSwwLDEsNgoyMDIyLTAxLTAxLElOLDQ2MjQ2NC44NzAwMDAwMDAsOTc3NzguNjY3MDAwMDAwLDE0OTE4LjIyMTYxMjkwMywzMTU0LjE1MDU0ODM4NywwLDAsMCwwLDEsNwoyMDIyLTAxLTAxLElUVCwxNDU2ODQxLjU1NTAwMDAwMCw1NTExNC42MjcwMDAwMDAsNDY5OTQuODg4ODcwOTY4LDE3NzcuODkxMTkzNTQ4LDAsMCwwLDAsMSw4CjIwMjItMDEtMDEsTEEsMzg3OTg0LjE2MDAwMDAwMCwxNzAzMzcuMjU3MDAwMDAwLDEyNTE1LjYxODA2NDUxNiw1NDk0Ljc1MDIyNTgwNiwwLDAsMCwxLDEsOQoyMDIyLTAxLTAxLExJLDMyNzI5OC43NzAwMDAwMDAsMjU1MTUwLjg3MzAwMDAwMCwxMDU1OC4wMjQ4Mzg3MTAsODIzMC42NzMzMjI1ODEsMCwwLDAsMCwxLDEwCjIwMjItMDEtMDEsT1ksNTQwNzk4LjEyMDAwMDAwMCwyNDYxOS4zNTkwMDAwMDAsMTc0NDUuMTAwNjQ1MTYxLDc5NC4xNzI4NzA5NjgsMCwwLDAsMSwxLDExCjIwMjItMDEtMDEsUEEsMjMwNTQ2LjQyMDAwMDAwMCwyMzU3MDUuODYyMDAwMDAwLDc0MzYuOTgxMjkwMzIzLDc2MDMuNDE0OTAzMjI2LDAsMCwwLDAsMSwxMgoyMDIyLTAxLTAxLFNBLDE4ODc3NzIuMDAwMDAwMDAwLDUzNjM2NS40NjUwMDAwMDAsNjA4OTUuODcwOTY3NzQyLDE3MzAyLjExMTc3NDE5NCwwLDAsMSwwLDEsMTMKMjAyMi0wMS0wMSxTSCwxODI2NTk0Ljk0MDAwMDAwMCw1Mzk2NzIuNjU1MDAwMDAwLDU4OTIyLjQxNzQxOTM1NSwxNzQwOC43OTUzMjI1ODEsMCwwLDAsMCwxLDE0CjIwMjItMDItMDEsQU0sMTM4Ny45ODAwMDAwMDAsNjg3OTI4Ljg2MDAwMDAwMCw0OS41NzA3MTQyODYsMjQ1NjguODg3ODU3MTQzLDAsMCwxLDAsMSwxNQoyMDIyLTAyLTAxLEFQLDkxNzE3LjczNTAwMDAwMCw5NTMwLjc2MjAwMDAwMCwzMjc1LjYzMzM5Mjg1NywzNDAuMzg0MzU3MTQzLDAsMCwwLDAsMSwxNgoyMDIyLTAyLTAxLEFVLDIxMTU4MzguNTEwMDAwMDAwLDI3NzIxOC4xNDcwMDAwMDAsNzU1NjUuNjYxMDcxNDI5LDk5MDAuNjQ4MTA3MTQzLDAsMCwwLDAsMSwxNwoyMDIyLTAyLTAxLENVLDczNDg5OC44MjAwMDAwMDAsMTUxMjU4LjI2MzAwMDAwMCwyNjI0Ni4zODY0Mjg1NzEsNTQwMi4wODA4MjE0MjksMCwwLDEsMSwxLDE4CjIwMjItMDItMDEsRVksNzU2NjQxLjMzMzAwMDAwMCwxMTgxNjQuMjQ4MDAwMDAwLDI3MDIyLjkwNDc1MDAwMCw0MjIwLjE1MTcxNDI4NiwwLDAsMSwwLDEsMTkKMjAyMi0wMi0wMSxJTiw0NDU2MjQuNzMwMDAwMDAwLDk3NzgyLjg0MTAwMDAwMCwxNTkxNS4xNjg5Mjg1NzEsMzQ5Mi4yNDQzMjE0MjksMCwwLDAsMCwxLDIwCjIwMjItMDItMDEsSVRULDEyMDQ1OTguNjYyMDAwMDAwLDQ1MjE5LjIxOTAwMDAwMCw0MzAyMS4zODA3ODU3MTQsMTYxNC45NzIxMDcxNDMsMCwwLDAsMCwxLDIxCjIwMjItMDItMDEsTEEsMzU0OTk4LjAxMDAwMDAwMCwxNDcwMTMuNzUzMDAwMDAwLDEyNjc4LjUwMDM1NzE0Myw1MjUwLjQ5MTE3ODU3MSwwLDAsMCwxLDEsMjIKMjAyMi0wMi0wMSxMSSwzMTQyODAuODQwMDAwMDAwLDIyNDUzOS40MjMwMDAwMDAsMTEyMjQuMzE1NzE0Mjg2LDgwMTkuMjY1MTA3MTQzLDAsMCwwLDAsMSwyMwoyMDIyLTAyLTAxLE9ZLDUwNjkxNy45NTAwMDAwMDAsMjM0NDIuMzg5MDAwMDAwLDE4MTA0LjIxMjUwMDAwMCw4MzcuMjI4MTc4NTcxLDAsMCwwLDAsMSwyNAoyMDIyLTAyLTAxLFBBLDIxODA0My44ODAwMDAwMDAsMjE1MDI5LjY1NDAwMDAwMCw3Nzg3LjI4MTQyODU3MSw3Njc5LjYzMDUwMDAwMCwwLDAsMCwwLDEsMjUKMjAyMi0wMi0wMSxTQSwxODgwNzk1LjE5MDAwMDAwMCw1MjU3MDQuNzQ3MDAwMDAwLDY3MTcxLjI1Njc4NTcxNCwxODc3NS4xNjk1MzU3MTQsMCwwLDAsMCwxLDI2CjIwMjItMDItMDEsU0gsMTc5Nzg1OC4yMzAwMDAwMDAsNTIxODYxLjEyOTAwMDAwMCw2NDIwOS4yMjI1MDAwMDAsMTg2MzcuODk3NDY0Mjg2LDAsMCwwLDAsMSwyNwoyMDIyLTAzLTAxLEFNLDE0MTkuOTAwMDAwMDAwLDc1MzU3NS4wODAwMDAwMDAsNDUuODAzMjI1ODA2LDI0MzA4Ljg3MzU0ODM4NywwLDAsMSwwLDEsMjgKMjAyMi0wMy0wMSxBUCwxMTg2OTkuMDYwMDAwMDAwLDEzMzQ4LjUyMjAwMDAwMCwzODI5LjAwMTkzNTQ4NCw0MzAuNTk3NDgzODcxLDAsMCwwLDAsMSwyOQoyMDIyLTAzLTAxLEFVLDIzMTUxNjkuNzIwMDAwMDAwLDMwODI5NS42NDMwMDAwMDAsNzQ2ODIuODk0MTkzNTQ4LDk5NDUuMDIwNzQxOTM1LDAsMCwwLDAsMSwzMAoyMDIyLTAzLTAxLENVLDc5MTY2My4wODAwMDAwMDAsMTY5MjU4Ljg3MjAwMDAwMCwyNTUzNy41MTg3MDk2NzcsNTQ1OS45NjM2MTI5MDMsMCwwLDEsMSwxLDMxCjIwMjItMDMtMDEsRVksOTI4NjMwLjU5OTAwMDAwMCwxNDY3MzguNDU4MDAwMDAwLDI5OTU1LjgyNTc3NDE5NCw0NzMzLjQ5ODY0NTE2MSwwLDAsMCwwLDEsMzIKMjAyMi0wMy0wMSxJTiw0OTk0NTAuMzgwMDAwMDAwLDExMTM4OS44MzMwMDAwMDAsMTYxMTEuMzAyNTgwNjQ1LDM1OTMuMjIwNDE5MzU1LDAsMCwwLDAsMSwzMwoyMDIyLTAzLTAxLElUVCwxNjY5OTI2LjM0MTAwMDAwMCw2MzI2My40NDYwMDAwMDAsNTM4NjguNTkxNjQ1MTYxLDIwNDAuNzU2MzIyNTgxLDAsMCwwLDAsMSwzNAoyMDIyLTAzLTAxLExBLDQxMjQ2Ni4yNzAwMDAwMDAsMTc1MDkwLjIxNjAwMDAwMCwxMzMwNS4zNjM1NDgzODcsNTY0OC4wNzE0ODM4NzEsMCwwLDEsMCwxLDM1CjIwMjItMDMtMDEsTEksMzY0Nzc3LjQ1MDAwMDAwMCwyNTUyNjUuMDgyMDAwMDAwLDExNzY3LjAxNDUxNjEyOSw4MjM0LjM1NzQ4Mzg3MSwwLDAsMCwwLDEsMzYKMjAyMi0wMy0wMSxPWSw1NjEyNTAuNTEwMDAwMDAwLDI2MDIzLjE0NjAwMDAwMCwxODEwNC44NTUxNjEyOTAsODM5LjQ1NjMyMjU4MSwwLDAsMCwwLDEsMzcKMjAyMi0wMy0wMSxQQSwyNDAyMTEuOTgwMDAwMDAwLDIzMzIxMi44MDgwMDAwMDAsNzc0OC43NzM1NDgzODcsNzUyMi45OTM4MDY0NTIsMCwwLDAsMCwxLDM4CjIwMjItMDMtMDEsU0EsMjEwNTE3Mi4yNDAwMDAwMDAsNTgzMjA0LjQzNzAwMDAwMCw2NzkwOC43ODE5MzU0ODQsMTg4MTMuMDQ2MzU0ODM5LDAsMCwwLDAsMSwzOQoyMDIyLTAzLTAxLFNILDIwMDkwMDQuMzcwMDAwMDAwLDU5NTI2Mi4xMjIwMDAwMDAsNjQ4MDYuNTkyNTgwNjQ1LDE5MjAyLjAwMzkzNTQ4NCwwLDAsMCwwLDEsNDAKMjAyMi0wNC0wMSxBTSwxMjQ4LjQzMDAwMDAwMCw3MjI3NDcuMTAwMDAwMDAwLDQxLjYxNDMzMzMzMywyNDA5MS41NzAwMDAwMDAsMCwwLDAsMCwxLDQxCjIwMjItMDQtMDEsQVAsMTEwNDIwLjY5MDAwMDAwMCwxMjg0MS4yMTIwMDAwMDAsMzY4MC42ODk2NjY2NjcsNDI4LjA0MDQwMDAwMCwwLDAsMCwwLDEsNDIKMjAyMi0wNC0wMSxBVSwyMjU4ODI5LjIzMDAwMDAwMCwyOTg3MTguMTQwMDAwMDAwLDc1Mjk0LjMwNzY2NjY2Nyw5OTU3LjI3MTMzMzMzMywwLDAsMCwwLDEsNDMKMjAyMi0wNC0wMSxDVSw3NjY5MDcuOTUwMDAwMDAwLDE3MDU2NS40MzQwMDAwMDAsMjU1NjMuNTk4MzMzMzMzLDU2ODUuNTE0NDY2NjY3LDAsMCwxLDEsMSw0NAoyMDIyLTA0LTAxLEVZLDkxMTY1My43OTYwMDAwMDAsMTQwNTY3LjIzODAwMDAwMCwzMDM4OC40NTk4NjY2NjcsNDY4NS41NzQ2MDAwMDAsMCwwLDAsMCwxLDQ1CjIwMjItMDQtMDEsSU4sNDc1NjY1LjMzMDAwMDAwMCwxMDIyMzMuODMzMDAwMDAwLDE1ODU1LjUxMTAwMDAwMCwzNDA3Ljc5NDQzMzMzMywwLDAsMCwwLDEsNDYKMjAyMi0wNC0wMSxJVFQsMTU5NjY5Ni41NTQwMDAwMDAsNjI5NjYuMzU0MDAwMDAwLDUzMjIzLjIxODQ2NjY2NywyMDk4Ljg3ODQ2NjY2NywwLDAsMCwwLDEsNDcKMjAyMi0wNC0wMSxMQSwzODY1MjUuOTcwMDAwMDAwLDE4MTI3OS4xODgwMDAwMDAsMTI4ODQuMTk5MDAwMDAwLDYwNDIuNjM5NjAwMDAwLDAsMCwwLDAsMSw0OAoyMDIyLTA0LTAxLExJLDM0OTE4My43MjAwMDAwMDAsMjQyMzY0LjU4NjAwMDAwMCwxMTYzOS40NTczMzMzMzMsODA3OC44MTk1MzMzMzMsMCwwLDAsMCwxLDQ5CjIwMjItMDQtMDEsT1ksNTUxOTUzLjU2MDAwMDAwMCwyNTg2My4wMDEwMDAwMDAsMTgzOTguNDUyMDAwMDAwLDg2Mi4xMDAwMzMzMzMsMCwwLDAsMCwxLDUwCjIwMjItMDQtMDEsUEEsMjI0NDgzLjAxMDAwMDAwMCwyMTU1MDcuODg0MDAwMDAwLDc0ODIuNzY3MDAwMDAwLDcxODMuNTk2MTMzMzMzLDAsMCwwLDAsMSw1MQoyMDIyLTA0LTAxLFNBLDIwNDY5MzcuMDkwMDAwMDAwLDU5MzE4Mi40NzgwMDAwMDAsNjgyMzEuMjM2MzMzMzMzLDE5NzcyLjc0OTI2NjY2NywwLDAsMCwwLDEsNTIKMjAyMi0wNC0wMSxTSCwxOTMyNDM3LjgzMDAwMDAwMCw1NzMwNjkuMTQ1MDAwMDAwLDY0NDE0LjU5NDMzMzMzMywxOTEwMi4zMDQ4MzMzMzMsMCwwLDAsMCwxLDUzCjIwMjItMDUtMDEsQU0sMTI0NC45NjAwMDAwMDAsNzQzMjgyLjUyMDAwMDAwMCw0MC4xNjAwMDAwMDAsMjM5NzYuODU1NDgzODcxLDAsMCwwLDAsMSw1NAoyMDIyLTA1LTAxLEFQLDExNTI2MS45MjkwMDAwMDAsMTMwNDMuMzcxMDAwMDAwLDM3MTguMTI2NzQxOTM1LDQyMC43NTM5MDMyMjYsMCwwLDAsMCwxLDU1CjIwMjItMDUtMDEsQVUsMjM0OTAyNi44MzAwMDAwMDAsMzE3NjYzLjYxNDAwMDAwMCw3NTc3NS4wNTkwMzIyNTgsMTAyNDcuMjEzMzU0ODM5LDAsMCwwLDAsMSw1NgoyMDIyLTA1LTAxLENVLDc4ODc3OC44MjAwMDAwMDAsMTc3MzM0LjIxNDAwMDAwMCwyNTQ0NC40NzgwNjQ1MTYsNTcyMC40NTg1MTYxMjksMCwwLDEsMSwxLDU3CjIwMjItMDUtMDEsRVksOTIzODQ2LjQ3MjAwMDAwMCwxNDEyOTEuNjg5MDAwMDAwLDI5ODAxLjQ5OTA5Njc3NCw0NTU3Ljc5NjQxOTM1NSwwLDAsMCwwLDEsNTgKMjAyMi0wNS0wMSxJTiw0ODIzOTIuMjkwMDAwMDAwLDEwNjA4Ny40NTgwMDAwMDAsMTU1NjEuMDQxNjEyOTAzLDM0MjIuMTc2MDY0NTE2LDAsMCwwLDAsMSw1OQoyMDIyLTA1LTAxLElUVCwxNjA1NjMyLjQ0OTAwMDAwMCw2NDI0OC42MzUwMDAwMDAsNTE3OTQuNTk1MTI5MDMyLDIwNzIuNTM2NjEyOTAzLDAsMCwwLDAsMSw2MAoyMDIyLTA1LTAxLExBLDM4MjE2OC44ODAwMDAwMDAsMTg0Nzg3LjI3MDAwMDAwMCwxMjMyOC4wMjgzODcwOTcsNTk2MC44Nzk2Nzc0MTksMCwwLDAsMCwxLDYxCjIwMjItMDUtMDEsTEksMzQ5OTE3LjIzMDAwMDAwMCwyMzc2MzAuOTU4MDAwMDAwLDExMjg3LjY1MjU4MDY0NSw3NjY1LjUxNDc3NDE5NCwwLDAsMCwwLDEsNjIKMjAyMi0wNS0wMSxPWSw1OTMwNTIuNDAwMDAwMDAwLDI3NzM4LjAxMjAwMDAwMCwxOTEzMC43MjI1ODA2NDUsODk0Ljc3NDU4MDY0NSwwLDAsMCwwLDEsNjMKMjAyMi0wNS0wMSxQQSwyMjUyNzYuNDkwMDAwMDAwLDIyODg1MS4xNjgwMDAwMDAsNzI2Ni45ODM1NDgzODcsNzM4Mi4yOTU3NDE5MzUsMCwwLDAsMCwxLDY0CjIwMjItMDUtMDEsU0EsMjE0MDgyOC42MTAwMDAwMDAsNjQ2MTYyLjMzNTAwMDAwMCw2OTA1OC45ODc0MTkzNTUsMjA4NDMuOTQ2MjkwMzIzLDAsMCwwLDAsMSw2NQoyMDIyLTA1LTAxLFNILDIwMzM5NzQuMzkwMDAwMDAwLDYwMTYxOS4zNzAwMDAwMDAsNjU2MTIuMDc3MDk2Nzc0LDE5NDA3LjA3NjQ1MTYxMywwLDAsMCwwLDEsNjYKMjAyMi0wNi0wMSxBTSwxMjA3LjM3MDAwMDAwMCw3MDk4ODEuOTAwMDAwMDAwLDQwLjI0NTY2NjY2NywyMzY2Mi43MzAwMDAwMDAsMCwwLDAsMCwxLDY3CjIwMjItMDYtMDEsQVAsMTA0MDU5LjE3OTAwMDAwMCwxMjMwNi44MjgwMDAwMDAsMzQ2OC42MzkzMDAwMDAsNDEwLjIyNzYwMDAwMCwwLDAsMCwwLDEsNjgKMjAyMi0wNi0wMSxBVSwxODMwMTQ3LjgzMDAwMDAwMCwyNDQ2NDEuNjk0MDAwMDAwLDYxMDA0LjkyNzY2NjY2Nyw4MTU0LjcyMzEzMzMzMywwLDAsMCwwLDEsNjkKMjAyMi0wNi0wMSxDVSw1NDI0NDAuNjEwMDAwMDAwLDEyMDQ2Mi4yOTIwMDAwMDAsMTgwODEuMzUzNjY2NjY3LDQwMTUuNDA5NzMzMzMzLDAsMCwwLDEsMSw3MAoyMDIyLTA2LTAxLEVZLDkxNTY5My44NDYwMDAwMDAsMTQwMzc1LjM3MjAwMDAwMCwzMDUyMy4xMjgyMDAwMDAsNDY3OS4xNzkwNjY2NjcsMCwwLDAsMCwxLDcxCjIwMjItMDYtMDEsSU4sMzUwODk3LjM5MDAwMDAwMCw3MTgzMC4xNjQwMDAwMDAsMTE2OTYuNTc5NjY2NjY3LDIzOTQuMzM4ODAwMDAwLDAsMCwwLDAsMSw3MgoyMDIyLTA2LTAxLElUVCwxNTcxMTU2Ljg5NTAwMDAwMCw2NDcyMi4wNzUwMDAwMDAsNTIzNzEuODk2NTAwMDAwLDIxNTcuNDAyNTAwMDAwLDAsMCwwLDAsMSw3MwoyMDIyLTA2LTAxLExBLDI4MDc0MS4yOTAwMDAwMDAsMTU1NTg0LjE5MDAwMDAwMCw5MzU4LjA0MzAwMDAwMCw1MTg2LjEzOTY2NjY2NywwLDAsMCwxLDEsNzQKMjAyMi0wNi0wMSxMSSwyNDM1MzYuMDAwMDAwMDAwLDE1MjczOS4yMjQwMDAwMDAsODExNy44NjY2NjY2NjcsNTA5MS4zMDc0NjY2NjcsMCwwLDAsMCwxLDc1CjIwMjItMDYtMDEsT1ksMzkyNjg1LjM3MDAwMDAwMCwxODkwMS4xNTcwMDAwMDAsMTMwODkuNTEyMzMzMzMzLDYzMC4wMzg1NjY2NjcsMCwwLDEsMSwxLDc2CjIwMjItMDYtMDEsUEEsMTgzMjAyLjE4MDAwMDAwMCwxNjUyODcuMTg4MDAwMDAwLDYxMDYuNzM5MzMzMzMzLDU1MDkuNTcyOTMzMzMzLDAsMCwwLDAsMSw3NwoyMDIyLTA2LTAxLFNBLDE0OTc5ODQuNDAwMDAwMDAwLDQ2MDk4MC4yMDkwMDAwMDAsNDk5MzIuODEzMzMzMzMzLDE1MzY2LjAwNjk2NjY2NywwLDAsMSwxLDEsNzgKMjAyMi0wNi0wMSxTSCwxNjIzODgxLjAxMDAwMDAwMCw0ODM0MjMuMDE0MDAwMDAwLDU0MTI5LjM2NzAwMDAwMCwxNjExNC4xMDA0NjY2NjcsMCwwLDAsMCwxLDc5CjIwMjItMDctMDEsQU0sMTI1NS4zNTAwMDAwMDAsNzIwNjc0LjU5MDAwMDAwMCw0MC40OTUxNjEyOTAsMjMyNDcuNTY3NDE5MzU1LDAsMCwwLDAsMSw4MAoyMDIyLTA3LTAxLEFQLDEwMjU5NS40NzYwMDAwMDAsMTE2OTkuMDk4MDAwMDAwLDMzMDkuNTMxNDgzODcxLDM3Ny4zOTAyNTgwNjUsMCwwLDAsMCwxLDgxCjIwMjItMDctMDEsQVUsMjI3MTc2Ny41OTAwMDAwMDAsMjk4NjczLjEwMDAwMDAwMCw3MzI4Mi44MjU0ODM4NzEsOTYzNC42MTYxMjkwMzIsMCwwLDAsMCwxLDgyCjIwMjItMDctMDEsQ1UsNzU1MzkwLjU1MDAwMDAwMCwxNjQ3ODguNTQzMDAwMDAwLDI0MzY3LjQzNzA5Njc3NCw1MzE1Ljc1OTQ1MTYxMywwLDAsMSwwLDEsODMKMjAyMi0wNy0wMSxFWSw5NTY3MTYuNjkzMDAwMDAwLDE0NjYyNS41ODIwMDAwMDAsMzA4NjEuODI4ODA2NDUyLDQ3MjkuODU3NDgzODcxLDAsMCwwLDAsMSw4NAoyMDIyLTA3LTAxLElOLDQ1ODc5My41NjAwMDAwMDAsOTIzMzguNTAwMDAwMDAwLDE0Nzk5Ljc5MjI1ODA2NSwyOTc4LjY2MTI5MDMyMywwLDAsMCwwLDEsODUKMjAyMi0wNy0wMSxJVFQsMTYwNzI5My41MDEwMDAwMDAsNjg1MjcuNDk3MDAwMDAwLDUxODQ4LjE3NzQ1MTYxMywyMjEwLjU2NDQxOTM1NSwwLDAsMCwwLDEsODYKMjAyMi0wNy0wMSxMQSwzNTg5MTguNzAwMDAwMDAwLDE3NDcwNS42ODEwMDAwMDAsMTE1NzguMDIyNTgwNjQ1LDU2MzUuNjY3MTI5MDMyLDAsMCwwLDAsMSw4NwoyMDIyLTA3LTAxLExJLDMzNDM3My41NjAwMDAwMDAsMjE5MDQxLjc4MDAwMDAwMCwxMDc4Ni4yNDM4NzA5NjgsNzA2NS44NjM4NzA5NjgsMCwwLDAsMCwxLDg4CjIwMjItMDctMDEsT1ksNTIwMzIzLjE2MDAwMDAwMCwyNjQ0Ny45NjAwMDAwMDAsMTY3ODQuNjE4MDY0NTE2LDg1My4xNjAwMDAwMDAsMCwwLDAsMCwxLDg5CjIwMjItMDctMDEsUEEsMjU2MTY2LjI5MDAwMDAwMCwyMjIzMDMuMDAyMDAwMDAwLDgyNjMuNDI4NzA5Njc3LDcxNzEuMDY0NTgwNjQ1LDAsMCwwLDAsMSw5MAoyMDIyLTA3LTAxLFNBLDIwOTU3MDcuMjIwMDAwMDAwLDY0MTkyMi45NjMwMDAwMDAsNjc2MDMuNDU4NzA5Njc3LDIwNzA3LjE5MjM1NDgzOSwwLDAsMCwwLDEsOTEKMjAyMi0wNy0wMSxTSCwxODg5NTE0LjE0MDAwMDAwMCw1NDgzMTQuNTExMDAwMDAwLDYwOTUyLjA2OTAzMjI1OCwxNzY4Ny41NjQ4NzA5NjgsMCwwLDAsMCwxLDkyCjIwMjItMDgtMDEsQU0sMTI1My43MDAwMDAwMDAsLDQwLjQ0MTkzNTQ4NCwsMCwxLDAsMCwyLDkzfDExMAoyMDIyLTA4LTAxLEFQLDEwOTc4NS44MzEwMDAwMDAsMTQwMTkuMzIwMDAwMDAwLDM1NDEuNDc4NDE5MzU1LDQ1Mi4yMzYxMjkwMzIsMCwwLDAsMCwyLDk0fDEwNgoyMDIyLTA4LTAxLEFVLDIzMDEzOTUuNTEwMDAwMDAwLCw3NDIzOC41NjQ4Mzg3MTAsLDAsMSwwLDAsMiw5NXwxMTUKMjAyMi0wOC0wMSxDVSw3Njk2MzMuOTIwMDAwMDAwLDE3MzYwMS43NzAwMDAwMDAsMjQ4MjYuOTAwNjQ1MTYxLDU2MDAuMDU3MDk2Nzc0LDAsMCwxLDEsMiw5NnwxMTEKMjAyMi0wOC0wMSxFWSw5NTI4MzIuNDI2MDAwMDAwLDE1MjQwMC4yMTAwMDAwMDAsMzA3MzYuNTI5ODcwOTY4LDQ5MTYuMTM1ODA2NDUyLDAsMCwwLDAsMiw5N3wxMDcKMjAyMi0wOC0wMSxJTiw0ODM0NDIuOTAwMDAwMDAwLDk0MTYxLjAwMDAwMDAwMCwxNTU5NC45MzIyNTgwNjUsMzAzNy40NTE2MTI5MDMsMCwwLDAsMCwyLDk4fDEwOAoyMDIyLTA4LTAxLElUVCwxNjAwMTQ5LjQxMzAwMDAwMCw2NzI1MC4xMzYwMDAwMDAsNTE2MTcuNzIzMDAwMDAwLDIxNjkuMzU5MjI1ODA2LDAsMCwwLDAsMiw5OXwxMDkKMjAyMi0wOC0wMSxMQSwsMTc2NzcwLjY1NjAwMDAwMCwsNTcwMi4yNzkyMjU4MDYsMSwwLDAsMCwyLDEwMHwxMTIKMjAyMi0wOC0wMSxMSSwzNDk2NDMuNzkwMDAwMDAwLDIzMTE2Mi41MTEwMDAwMDAsMTEyNzguODMxOTM1NDg0LDc0NTYuODU1MTkzNTQ4LDAsMCwwLDAsMiwxMDF8MTEzCjIwMjItMDgtMDEsT1ksNTkwODg3LjExMDAwMDAwMCwzMDg5MS43MjAwMDAwMDAsMTkwNjAuODc0NTE2MTI5LDk5Ni41MDcwOTY3NzQsMCwwLDAsMCwyLDEwMnwxMTYKMjAyMi0wOC0wMSxQQSwyNzEyMDUuNjUwMDAwMDAwLDIzMzU3NC4zNTUwMDAwMDAsODc0OC41NjkzNTQ4MzksNzUzNC42NTY2MTI5MDMsMCwwLDAsMCwyLDEwM3wxMTcKMjAyMi0wOC0wMSxTQSwyMTU5Nzk3LjY0MDAwMDAwMCw2NTgxOTMuMDU4MDAwMDAwLDY5NjcwLjg5MTYxMjkwMywyMTIzMi4wMzQxMjkwMzIsMCwwLDAsMCwyLDEwNHwxMTgKMjAyMi0wOC0wMSxTSCwxOTg5OTA1LjQ1MDAwMDAwMCw2MjU0NzYuNDQ1MDAwMDAwLDY0MTkwLjQ5ODM4NzA5NywyMDE3Ni42NTk1MTYxMjksMCwwLDAsMCwyLDEwNXwxMTQKMjAyMi0wOS0wMSxBTSwxMjA0LjU2MDAwMDAwMCwxMDYuMTkwMDAwMDAwLDQwLjE1MjAwMDAwMCwzLjUzOTY2NjY2NywwLDAsMCwxLDEsMTIzCjIwMjItMDktMDEsQVAsMTAyMTY1LjAwMzAwMDAwMCwxMjA4Mi45NDkwMDAwMDAsMzQwNS41MDAxMDAwMDAsNDAyLjc2NDk2NjY2NywwLDAsMCwwLDEsMTE5CjIwMjItMDktMDEsQVUsMjI3NDU5MS4wNTAwMDAwMDAsMzA0OTk3LjI1OTAwMDAwMCw3NTgxOS43MDE2NjY2NjcsMTAxNjYuNTc1MzAwMDAwLDAsMCwwLDAsMSwxMjgKMjAyMi0wOS0wMSxDVSw3MTAxNzEuMDcwMDAwMDAwLDE2MzIzOS45MTIwMDAwMDAsMjM2NzIuMzY5MDAwMDAwLDU0NDEuMzMwNDAwMDAwLDAsMCwxLDEsMSwxMjQKMjAyMi0wOS0wMSxFWSw5MTE2NDAuMzE3MDAwMDAwLDE0MTgzMi42MTEwMDAwMDAsMzAzODguMDEwNTY2NjY3LDQ3MjcuNzUzNzAwMDAwLDAsMCwwLDAsMSwxMjAKMjAyMi0wOS0wMSxJTiw0NTEwMTEuNjEwMDAwMDAwLDk1NTczLjA2MzAwMDAwMCwxNTAzMy43MjAzMzMzMzMsMzE4NS43Njg3NjY2NjcsMCwwLDAsMCwxLDEyMQoyMDIyLTA5LTAxLElUVCwxNTExODQ4Ljk2MDAwMDAwMCw2NjcyNS45NzEwMDAwMDAsNTAzOTQuOTY1MzMzMzMzLDIyMjQuMTk5MDMzMzMzLDAsMCwwLDAsMSwxMjIKMjAyMi0wOS0wMSxMQSwzNTI3MjMuMjQwMDAwMDAwLDE2NzY4NS44MjYwMDAwMDAsMTE3NTcuNDQxMzMzMzMzLDU1ODkuNTI3NTMzMzMzLDAsMCwwLDEsMSwxMjUKMjAyMi0wOS0wMSxMSSwzNTYyMDguOTkwMDAwMDAwLDIzOTMyMy41MzAwMDAwMDAsMTE4NzMuNjMzMDAwMDAwLDc5NzcuNDUxMDAwMDAwLDAsMCwwLDAsMSwxMjYKMjAyMi0wOS0wMSxPWSw1ODU2NTAuMDkwMDAwMDAwLDI5NzM4LjE5MDAwMDAwMCwxOTUyMS42Njk2NjY2NjcsOTkxLjI3MzAwMDAwMCwwLDAsMCwwLDEsMTI5CjIwMjItMDktMDEsUEEsMjYwOTcwLjYyMDAwMDAwMCwyNDk2MzQuNzQ3MDAwMDAwLDg2OTkuMDIwNjY2NjY3LDgzMjEuMTU4MjMzMzMzLDAsMCwwLDAsMSwxMzAKMjAyMi0wOS0wMSxTQSwyMDg3ODAyLjExMDAwMDAwMCw2MjYzOTIuNjEwMDAwMDAwLDY5NTkzLjQwMzY2NjY2NywyMDg3OS43NTM2NjY2NjcsMCwwLDAsMCwxLDEzMQoyMDIyLTA5LTAxLFNILDE4NzUwMjkuNjYwMDAwMDAwLDU0NDk3Mi41MjIwMDAwMDAsNjI1MDAuOTg4NjY2NjY3LDE4MTY1Ljc1MDczMzMzMywwLDAsMCwwLDEsMTI3CjIwMjItMTAtMDEsQU0sMTIzNy41NjAwMDAwMDAsMTEwLjc5MDAwMDAwMCwzOS45MjEyOTAzMjMsMy41NzM4NzA5NjgsMCwwLDAsMSwxLDEzNgoyMDIyLTEwLTAxLEFQLDEwMTc1MC40MjgwMDAwMDAsMTE5NzIuNzM5MDAwMDAwLDMyODIuMjcxODcwOTY4LDM4Ni4yMTczODcwOTcsMCwwLDAsMCwxLDEzMgoyMDIyLTEwLTAxLEFVLDIzNzc5MjguOTIwMDAwMDAwLDMyMDk5Ny44NzIwMDAwMDAsNzY3MDcuMzg0NTE2MTI5LDEwMzU0Ljc3MDA2NDUxNiwwLDAsMCwwLDEsMTQxCjIwMjItMTAtMDEsQ1UsNjgyODQ2LjE5MDAwMDAwMCwxNjAyNTQuMTY2MDAwMDAwLDIyMDI3LjI5NjQ1MTYxMyw1MTY5LjQ4OTIyNTgwNiwwLDAsMCwwLDEsMTM3CjIwMjItMTAtMDEsRVksOTQ0NTM3LjQ1ODAwMDAwMCwxNDM4MzguNDcxMDAwMDAwLDMwNDY4Ljk1MDI1ODA2NSw0NjM5Ljk1MDY3NzQxOSwwLDAsMCwwLDEsMTMzCjIwMjItMTAtMDEsSU4sNDczNDQyLjk5MDAwMDAwMCwxMDYyNjguMTMwMDAwMDAwLDE1MjcyLjM1NDUxNjEyOSwzNDI4LjAwNDE5MzU0OCwwLDAsMCwwLDEsMTM0CjIwMjItMTAtMDEsSVRULDE1OTQ0NzcuMTE0MDAwMDAwLDczOTQ4Ljc1NzAwMDAwMCw1MTQzNC43NDU2MTI5MDMsMjM4NS40NDM3NzQxOTQsMCwwLDAsMCwxLDEzNQoyMDIyLTEwLTAxLExBLDM1OTQ1Mi42NDAwMDAwMDAsMTc0OTc2Ljk4OTAwMDAwMCwxMTU5NS4yNDY0NTE2MTMsNTY0NC40MTkwMDAwMDAsMCwwLDAsMCwxLDEzOAoyMDIyLTEwLTAxLExJLDQxNDQ1NS4yMDAwMDAwMDAsMjc4NTE5LjU0NTAwMDAwMCwxMzM2OS41MjI1ODA2NDUsODk4NC41MDE0NTE2MTMsMCwwLDAsMCwxLDEzOQoyMDIyLTEwLTAxLE9ZLDYyMDUzMy4xNjAwMDAwMDAsMzEwNDkuMDI2MDAwMDAwLDIwMDE3LjE5ODcwOTY3NywxMDAxLjU4MTQ4Mzg3MSwwLDAsMCwwLDEsMTQyCjIwMjItMTAtMDEsUEEsMjcwNjUxLjI1MDAwMDAwMCwyNTI4OTEuMzMxMDAwMDAwLDg3MzAuNjg1NDgzODcxLDgxNTcuNzg0ODcwOTY4LDAsMCwwLDAsMSwxNDMKMjAyMi0xMC0wMSxTQSwyMTMzNDUxLjQ2MDAwMDAwMCw2Mzk4NTguMjAxMDAwMDAwLDY4ODIxLjAxNDgzODcxMCwyMDY0MC41ODcxMjkwMzIsMCwwLDAsMCwxLDE0NAoyMDIyLTEwLTAxLFNILDE5OTE0NzcuNDcwMDAwMDAwLDU2NTYxOC4wNjMwMDAwMDAsNjQyNDEuMjA4NzA5Njc3LDE4MjQ1Ljc0Mzk2Nzc0MiwwLDAsMCwwLDEsMTQwCjIwMjItMTEtMDEsQU0sMTA0MS45MTAwMDAwMDAsOTguNDUwMDAwMDAwLDM0LjczMDMzMzMzMywzLjI4MTY2NjY2NywwLDAsMCwxLDEsMTQ5CjIwMjItMTEtMDEsQVAsOTc0MDAuMjc5MDAwMDAwLDEyNTMxLjA2NjAwMDAwMCwzMjQ2LjY3NTk2NjY2Nyw0MTcuNzAyMjAwMDAwLDAsMCwwLDAsMSwxNDUKMjAyMi0xMS0wMSxBVSwyMzE5NjgzLjAzMDAwMDAwMCwzMTE1MzIuODc4MDAwMDAwLDc3MzIyLjc2NzY2NjY2NywxMDM4NC40MjkyNjY2NjcsMCwwLDAsMCwxLDE1NAoyMDIyLTExLTAxLENVLDYyOTU2NC44NDAwMDAwMDAsMTQ2MzI4LjAxMTAwMDAwMCwyMDk4NS40OTQ2NjY2NjcsNDg3Ny42MDAzNjY2NjcsMCwwLDAsMCwxLDE1MAoyMDIyLTExLTAxLEVZLDkwNTUyOS43MTEwMDAwMDAsMTQzMjg0LjgxNDAwMDAwMCwzMDE4NC4zMjM3MDAwMDAsNDc3Ni4xNjA0NjY2NjcsMCwwLDAsMCwxLDE0NgoyMDIyLTExLTAxLElOLDQ1ODU5Mi4xMDAwMDAwMDAsMTA1MTQyLjQxNzAwMDAwMCwxNTI4Ni40MDMzMzMzMzMsMzUwNC43NDcyMzMzMzMsMCwwLDAsMCwxLDE0NwoyMDIyLTExLTAxLElUVCwxNDUyNDc4LjMyMDAwMDAwMCw2OTIyMS44NTMwMDAwMDAsNDg0MTUuOTQ0MDAwMDAwLDIzMDcuMzk1MTAwMDAwLDAsMCwwLDAsMSwxNDgKMjAyMi0xMS0wMSxMQSwzMzk2NjguMDUwMDAwMDAwLDE5MTk5NC40OTgwMDAwMDAsMTEzMjIuMjY4MzMzMzMzLDYzOTkuODE2NjAwMDAwLDAsMCwwLDAsMSwxNTEKMjAyMi0xMS0wMSxMSSwzNzYxMjYuOTgwMDAwMDAwLDI3Mzc4MC4wNjIwMDAwMDAsMTI1MzcuNTY2MDAwMDAwLDkxMjYuMDAyMDY2NjY3LDAsMCwwLDAsMSwxNTIKMjAyMi0xMS0wMSxPWSw2MDA4MjIuMzgwMDAwMDAwLDMwMTU4LjEyNTAwMDAwMCwyMDAyNy40MTI2NjY2NjcsMTAwNS4yNzA4MzMzMzMsMCwwLDAsMCwxLDE1NQoyMDIyLTExLTAxLFBBLDI0OTc2OS42NzAwMDAwMDAsMjMzNDEwLjM2NDAwMDAwMCw4MzI1LjY1NTY2NjY2Nyw3NzgwLjM0NTQ2NjY2NywwLDAsMCwwLDEsMTU2CjIwMjItMTEtMDEsU0EsMjExMjc1My4zNjAwMDAwMDAsNjM5MzczLjQ4MTAwMDAwMCw3MDQyNS4xMTIwMDAwMDAsMjEzMTIuNDQ5MzY2NjY3LDAsMCwwLDAsMSwxNTcKMjAyMi0xMS0wMSxTSCwxOTMxMDI5LjMwMDAwMDAwMCw1Mjg3NzEuMDE2MDAwMDAwLDY0MzY3LjY0MzMzMzMzMywxNzYyNS43MDA1MzMzMzMsMCwwLDAsMCwxLDE1MwoyMDIyLTEyLTAxLEFNLDk4My42OTAwMDAwMDAsOTAuMzIwMDAwMDAwLDMxLjczMTkzNTQ4NCwyLjkxMzU0ODM4NywwLDAsMCwxLDEsMTYyCjIwMjItMTItMDEsQVAsMTAzMzA5LjY5NDAwMDAwMCwxNDI0MC4xMDYwMDAwMDAsMzMzMi41NzA3NzQxOTQsNDU5LjM1ODI1ODA2NSwwLDAsMCwwLDEsMTU4CjIwMjItMTItMDEsQVUsMjM3MTg5OC44OTAwMDAwMDAsMzI1NjM0LjU4OTAwMDAwMCw3NjUxMi44Njc0MTkzNTUsMTA1MDQuMzQxNTgwNjQ1LDAsMCwwLDAsMSwxNjcKMjAyMi0xMi0wMSxDVSw2NDE4MzEuMDEwMDAwMDAwLDE0MzE1Ni4wNTMwMDAwMDAsMjA3MDQuMjI2MTI5MDMyLDQ2MTcuOTM3MTkzNTQ4LDAsMCwwLDAsMSwxNjMKMjAyMi0xMi0wMSxFWSw5NDg4OTEuMzkwMDAwMDAwLDE1OTI3MC40MzQwMDAwMDAsMzA2MDkuMzk5Njc3NDE5LDUxMzcuNzU1OTM1NDg0LDAsMCwwLDAsMSwxNTkKMjAyMi0xMi0wMSxJTiw0NjM1MjMuMDYwMDAwMDAwLDEwMjQ1Mi43NTAwMDAwMDAsMTQ5NTIuMzU2Nzc0MTk0LDMzMDQuOTI3NDE5MzU1LDAsMCwwLDAsMSwxNjAKMjAyMi0xMi0wMSxJVFQsMTYwMjUyOS45NzYwMDAwMDAsNzk3NTEuMDE2MDAwMDAwLDUxNjk0LjUxNTM1NDgzOSwyNTcyLjYxMzQxOTM1NSwwLDAsMCwwLDEsMTYxCjIwMjItMTItMDEsTEEsMzQ0NjIyLjgwMDAwMDAwMCwyMjE0NTUuMDI4MDAwMDAwLDExMTE2Ljg2NDUxNjEyOSw3MTQzLjcxMDU4MDY0NSwwLDAsMCwwLDEsMTY0CjIwMjItMTItMDEsTEksMzgxMTQ0LjAzMDAwMDAwMCwyOTgxOTIuMDgxMDAwMDAwLDEyMjk0Ljk2ODcwOTY3Nyw5NjE5LjA5OTM4NzA5NywwLDAsMCwwLDEsMTY1CjIwMjItMTItMDEsT1ksNjMwNDM3Ljg4MDAwMDAwMCwzMTQyMC4zNTgwMDAwMDAsMjAzMzYuNzA1ODA2NDUyLDEwMTMuNTU5OTM1NDg0LDAsMCwwLDAsMSwxNjgKMjAyMi0xMi0wMSxQQSwyNjA4OTYuMzQwMDAwMDAwLDI1NTEyMS40NzQwMDAwMDAsODQxNi4wMTA5Njc3NDIsODIyOS43MjQ5Njc3NDIsMCwwLDAsMCwxLDE2OQoyMDIyLTEyLTAxLFNBLDIxODg1NTkuMjkwMDAwMDAwLDY1NzAzOS42NDkwMDAwMDAsNzA1OTguNjg2Nzc0MTk0LDIxMTk0LjgyNzM4NzA5NywwLDAsMCwwLDEsMTcwCjIwMjItMTItMDEsU0gsMTkxMjI2MC45MDAwMDAwMDAsNTQzMzQxLjkzODAwMDAwMCw2MTY4NS44MzU0ODM4NzEsMTc1MjcuMTU5MjkwMzIzLDAsMCwwLDAsMSwxNjYKMjAyMy0wMS0wMSxBQjE2LDQxNTI1MS45NjAwMDAwMDAsMTIwMzA5Ljk1MDAwMDAwMCwxMzM5NS4yMjQ1MTYxMjksMzg4MC45NjYxMjkwMzIsMCwwLDAsMSwxLDE3MQoyMDIzLTAxLTAxLEFNLDkwMy4xMDAwMDAwMDAsNjc5MDk4LjIxMDAwMDAwMCwyOS4xMzIyNTgwNjUsMjE5MDYuMzkzODcwOTY4LDAsMCwwLDAsMSwxNzIKMjAyMy0wMS0wMSxBUCwxMDM4NzguMjAzMDAwMDAwLDE0NDk5LjE0MDAwMDAwMCwzMzUwLjkwOTc3NDE5NCw0NjcuNzE0MTkzNTQ4LDAsMCwwLDAsMSwxNzMKMjAyMy0wMS0wMSxBVSwyMzg2NDA0LjQxMDAwMDAwMCwzMjAxMzIuMjc1MDAwMDAwLDc2OTgwLjc4NzQxOTM1NSwxMDMyNi44NDc1ODA2NDUsMCwwLDAsMCwxLDE3NAoyMDIzLTAxLTAxLENVLDY0MDA2My44NjAwMDAwMDAsMTQ4MzA4LjczMzAwMDAwMCwyMDY0Ny4yMjEyOTAzMjMsNDc4NC4xNTI2Nzc0MTksMCwwLDAsMCwxLDE3NQoyMDIzLTAxLTAxLEVZLDk0ODU4My4xNzUwMDAwMDAsMTY1NjYxLjA0MDAwMDAwMCwzMDU5OS40NTcyNTgwNjUsNTM0My45MDQ1MTYxMjksMCwwLDAsMCwxLDE3NgoyMDIzLTAxLTAxLElOLDQ3NjI2My4wNTAwMDAwMDAsOTk5MTMuMTQ2MDAwMDAwLDE1MzYzLjMyNDE5MzU0OCwzMjIzLjAwNDcwOTY3NywwLDAsMCwwLDEsMTc3CjIwMjMtMDEtMDEsSVRULDE2MzE0MTEuOTQyMDAwMDAwLDgwODk0LjU2ODAwMDAwMCw1MjYyNi4xOTE2Nzc0MTksMjYwOS41MDIxOTM1NDgsMCwwLDAsMCwxLDE3OAoyMDIzLTAxLTAxLExBLDMyMTg4Ny41NjAwMDAwMDAsMjE3NjI1Ljc0MTAwMDAwMCwxMDM4My40Njk2Nzc0MTksNzAyMC4xODUxOTM1NDgsMCwwLDAsMCwxLDE3OQoyMDIzLTAxLTAxLExJLDM2MTI3MS4wMTAwMDAwMDAsMjg1MjI0LjA2NzAwMDAwMCwxMTY1My45MDM1NDgzODcsOTIwMC43NzYzNTQ4MzksMCwwLDAsMCwxLDE4MAoyMDIzLTAxLTAxLE9ZLDYyNzEyNC4wNjAwMDAwMDAsMzE1NzQuMDI0MDAwMDAwLDIwMjI5LjgwODM4NzA5NywxMDE4LjUxNjkwMzIyNiwwLDAsMCwwLDEsMTgxCjIwMjMtMDEtMDEsUEEsMjY0MDIzLjU2MDAwMDAwMCwzMDc1OTUuMzUwMDAwMDAwLDg1MTYuODg5MDMyMjU4LDk5MjIuNDMwNjQ1MTYxLDAsMCwwLDAsMSwxODIKMjAyMy0wMS0wMSxTQSwyMTk1MTI3Ljg4MDAwMDAwMCw2NTQ1ODUuMDAwMDAwMDAwLDcwODEwLjU3Njc3NDE5NCwyMTExNS42NDUxNjEyOTAsMCwwLDAsMCwxLDE4MwoyMDIzLTAxLTAxLFNILDE5MjQyNTEuMDYwMDAwMDAwLDU0NDU5OC4zOTEwMDAwMDAsNjIwNzIuNjE0ODM4NzEwLDE3NTY3LjY5MDAzMjI1OCwwLDAsMCwwLDEsMTg0CjIwMjMtMDItMDEsQUIxNiwzMjg2ODIuMzIwMDAwMDAwLDk1NTg1Ljk1MDAwMDAwMCwxMTczOC42NTQyODU3MTQsMzQxMy43ODM5Mjg1NzEsMCwwLDAsMCwxLDE4NQoyMDIzLTAyLTAxLEFNLDc5OC4xODAwMDAwMDAsNjA4MjkzLjMzMDAwMDAwMCwyOC41MDY0Mjg1NzEsMjE3MjQuNzYxNzg1NzE0LDAsMCwwLDAsMSwxODYKMjAyMy0wMi0wMSxBUCw4MDQ2Ni4yODYwMDAwMDAsMTE1MjcuNDA0MDAwMDAwLDI4NzMuNzk1OTI4NTcxLDQxMS42OTMwMDAwMDAsMCwwLDAsMCwxLDE4NwoyMDIzLTAyLTAxLEFVLDE4MTU4MDAuMTQwMDAwMDAwLDIzODIwOC43NTkwMDAwMDAsNjQ4NTAuMDA1MDAwMDAwLDg1MDcuNDU1Njc4NTcxLDAsMCwwLDAsMSwxODgKMjAyMy0wMi0wMSxDVSw1MjAzMjYuNTUwMDAwMDAwLDEyMzEyMS43MDkwMDAwMDAsMTg1ODMuMDkxMDcxNDI5LDQzOTcuMjAzODkyODU3LDAsMCwwLDAsMSwxODkKMjAyMy0wMi0wMSxFWSw3NTg4NDMuNjgxMDAwMDAwLDEzNzA2MS44MDYwMDAwMDAsMjcxMDEuNTYwMDM1NzE0LDQ4OTUuMDY0NTAwMDAwLDAsMCwxLDAsMSwxOTAKMjAyMy0wMi0wMSxJTiwzODUyMzkuODYwMDAwMDAwLDg5NjM5LjM1NDAwMDAwMCwxMzc1OC41NjY0Mjg1NzEsMzIwMS40MDU1MDAwMDAsMCwwLDAsMCwxLDE5MQoyMDIzLTAyLTAxLElUVCwxMzMwODA1LjMwMzAwMDAwMCw2MzA5Ni42NjAwMDAwMDAsNDc1MjguNzYwODIxNDI5LDIyNTMuNDUyMTQyODU3LDAsMCwwLDAsMSwxOTIKMjAyMy0wMi0wMSxMQSwyODU5MjQuOTcwMDAwMDAwLDE4MTA5MS43OTQwMDAwMDAsMTAyMTEuNjA2MDcxNDI5LDY0NjcuNTY0MDcxNDI5LDAsMCwwLDAsMSwxOTMKMjAyMy0wMi0wMSxMSSwyOTY3NDQuMDcwMDAwMDAwLDI1MjkwOS42ODAwMDAwMDAsMTA1OTguMDAyNTAwMDAwLDkwMzIuNDg4NTcxNDI5LDAsMCwwLDAsMSwxOTQKMjAyMy0wMi0wMSxPWSw1MzY3MjUuNDMwMDAwMDAwLDI3MTY2LjA5NTAwMDAwMCwxOTE2OC43NjUzNTcxNDMsOTcwLjIxNzY3ODU3MSwwLDAsMCwwLDEsMTk1CjIwMjMtMDItMDEsUEEsMjE4MjA1LjI4MDAwMDAwMCwyNDg5NzkuNTc5MDAwMDAwLDc3OTMuMDQ1NzE0Mjg2LDg4OTIuMTI3ODIxNDI5LDAsMCwwLDAsMSwxOTYKMjAyMy0wMi0wMSxTQSwxOTIyODkxLjE1MDAwMDAwMCw1NTk2NDYuNDgzMDAwMDAwLDY4Njc0LjY4MzkyODU3MSwxOTk4Ny4zNzQzOTI4NTcsMCwwLDAsMCwxLDE5NwoyMDIzLTAyLTAxLFNILDE1ODY5MjkuODkwMDAwMDAwLDQ0ODExNS4wNjgwMDAwMDAsNTY2NzYuMDY3NTAwMDAwLDE2MDA0LjEwOTU3MTQyOSwwLDAsMCwwLDEsMTk4CjIwMjMtMDMtMDEsQUIxNiwzNDk2OTIuNjcwMDAwMDAwLDg4MjQ0Ljc2MDAwMDAwMCwxMTI4MC40MDg3MDk2NzcsMjg0Ni42MDUxNjEyOTAsMCwwLDAsMCwxLDE5OQoyMDIzLTAzLTAxLEFNLDg0NS40ODAwMDAwMDAsNjYxMjc0LjU5MDAwMDAwMCwyNy4yNzM1NDgzODcsMjEzMzEuNDM4Mzg3MDk3LDAsMCwwLDAsMSwyMDAKMjAyMy0wMy0wMSxBUCw2NDAyNy45MDcwMDAwMDAsOTY3NS42NTgwMDAwMDAsMjA2NS40MTYzNTQ4MzksMzEyLjExODAwMDAwMCwwLDAsMSwwLDEsMjAxCjIwMjMtMDMtMDEsQVUsMjA4NDQ1Mi44MzAwMDAwMDAsMjc3NTg3Ljk5NzAwMDAwMCw2NzI0MC40MTM4NzA5NjgsODk1NC40NTE1MTYxMjksMCwwLDAsMCwxLDIwMgoyMDIzLTAzLTAxLENVLDYwOTI3OC42ODAwMDAwMDAsMTQzNDExLjM4ODAwMDAwMCwxOTY1NC4xNTA5Njc3NDIsNDYyNi4xNzM4MDY0NTIsMCwwLDAsMCwxLDIwMwoyMDIzLTAzLTAxLEVZLDcyMDQxMS43MzMwMDAwMDAsMTUyMDMzLjA3MjAwMDAwMCwyMzIzOS4wODgxNjEyOTAsNDkwNC4yOTI2NDUxNjEsMCwwLDEsMCwxLDIwNAoyMDIzLTAzLTAxLElOLDQzMTIwOC4wOTAwMDAwMDAsMTAzODI0LjQyMjAwMDAwMCwxMzkwOS45MzgzODcwOTcsMzM0OS4xNzQ5MDMyMjYsMCwwLDAsMCwxLDIwNQoyMDIzLTAzLTAxLElUVCwxNDY3NTI5LjQ5MDAwMDAwMCw2NTMyNy40MzIwMDAwMDAsNDczMzkuNjYwOTY3NzQyLDIxMDcuMzM2NTE2MTI5LDAsMCwwLDAsMSwyMDYKMjAyMy0wMy0wMSxMQSwzMTExNzYuNjYwMDAwMDAwLDIwNjM1OC41MzkwMDAwMDAsMTAwMzcuOTU2Nzc0MTk0LDY2NTYuNzI3MDY0NTE2LDAsMCwwLDAsMSwyMDcKMjAyMy0wMy0wMSxMSSwzMjA5MTcuNjEwMDAwMDAwLDI5NTgwMi43MjMwMDAwMDAsMTAzNTIuMTgwOTY3NzQyLDk1NDIuMDIzMzIyNTgxLDAsMCwwLDAsMSwyMDgKMjAyMy0wMy0wMSxPWSw2MDU4NTAuOTEwMDAwMDAwLDMxMDUyLjA3MDAwMDAwMCwxOTU0My41Nzc3NDE5MzUsMTAwMS42Nzk2Nzc0MTksMCwwLDAsMCwxLDIwOQoyMDIzLTAzLTAxLFBBLDIzODIxNS41NjAwMDAwMDAsMjc2MzE1LjMyOTAwMDAwMCw3Njg0LjM3MjkwMzIyNiw4OTEzLjM5NzcwOTY3NywwLDAsMCwwLDEsMjEwCjIwMjMtMDMtMDEsU0EsMjEyNzE3OS45MTAwMDAwMDAsNjExNDA5LjY1NzAwMDAwMCw2ODYxOC43MDY3NzQxOTQsMTk3MjIuODkyMTYxMjkwLDAsMCwwLDAsMSwyMTEKMjAyMy0wMy0wMSxTSCwxODUzNzUxLjAyMDAwMDAwMCw1MTUzNDguMDcxMDAwMDAwLDU5Nzk4LjQyMDAwMDAwMCwxNjYyNC4xMzEzMjI1ODEsMCwwLDAsMCwxLDIxMgoyMDIzLTA0LTAxLEFCMTYsMjYwMDMxLjMyMDAwMDAwMCw2ODcxNS4wMDAwMDAwMDAsODY2Ny43MTA2NjY2NjcsMjI5MC41MDAwMDAwMDAsMCwwLDAsMCwxLDIxMwoyMDIzLTA0LTAxLEFNLDgyMC4yODAwMDAwMDAsNjM2NzUzLjI0MDAwMDAwMCwyNy4zNDI2NjY2NjcsMjEyMjUuMTA4MDAwMDAwLDAsMCwwLDAsMSwyMTQKMjAyMy0wNC0wMSxBUCw4NDk4My41MzIwMDAwMDAsMTMxNzguMjE2MDAwMDAwLDI4MzIuNzg0NDAwMDAwLDQzOS4yNzM4NjY2NjcsMCwwLDAsMCwxLDIxNQoyMDIzLTA0LTAxLEFVLDIyMDgxMDAuMDIwMDAwMDAwLDI4OTgwNy44OTAwMDAwMDAsNzM2MDMuMzM0MDAwMDAwLDk2NjAuMjYzMDAwMDAwLDAsMCwwLDAsMSwyMTYKMjAyMy0wNC0wMSxDVSw2MTYzNzUuMzIwMDAwMDAwLDE0NDgwNC44MjMwMDAwMDAsMjA1NDUuODQ0MDAwMDAwLDQ4MjYuODI3NDMzMzMzLDAsMCwwLDAsMSwyMTcKMjAyMy0wNC0wMSxFWSw4MTMwNTUuNDg2MDAwMDAwLDE2NjM0NS4yMDQwMDAwMDAsMjcxMDEuODQ5NTMzMzMzLDU1NDQuODQwMTMzMzMzLDAsMCwxLDAsMSwyMTgKMjAyMy0wNC0wMSxJTiw0NDczNzQuNTcwMDAwMDAwLDEwOTAwMy4wMDAwMDAwMDAsMTQ5MTIuNDg1NjY2NjY3LDM2MzMuNDMzMzMzMzMzLDAsMCwwLDAsMSwyMTkKMjAyMy0wNC0wMSxJVFQsMTY0NDAwNy4yMTIwMDAwMDAsNzI2MDAuNzQwMDAwMDAwLDU0ODAwLjI0MDQwMDAwMCwyNDIwLjAyNDY2NjY2NywwLDAsMCwwLDEsMjIwCjIwMjMtMDQtMDEsTEEsMjg3MDYxLjE0MDAwMDAwMCwxOTg1NDAuNTQ5MDAwMDAwLDk1NjguNzA0NjY2NjY3LDY2MTguMDE4MzAwMDAwLDAsMCwwLDAsMSwyMjEKMjAyMy0wNC0wMSxMSSwzMjM4NTEuOTYwMDAwMDAwLDI5MTA3MS45NTUwMDAwMDAsMTA3OTUuMDY1MzMzMzMzLDk3MDIuMzk4NTAwMDAwLDAsMCwwLDAsMSwyMjIKMjAyMy0wNC0wMSxPWSw1ODU1NTguOTgwMDAwMDAwLDI5NTUzLjMxMTAwMDAwMCwxOTUxOC42MzI2NjY2NjcsOTg1LjExMDM2NjY2NywwLDAsMCwwLDEsMjIzCjIwMjMtMDQtMDEsUEEsMjMxMjkzLjc1MDAwMDAwMCwyNjYwNzkuODU1MDAwMDAwLDc3MDkuNzkxNjY2NjY3LDg4NjkuMzI4NTAwMDAwLDAsMCwwLDAsMSwyMjQKMjAyMy0wNC0wMSxTQSwyMDcxMTAxLjg4MDAwMDAwMCw1ODczMzEuMzk1MDAwMDAwLDY5MDM2LjcyOTMzMzMzMywxOTU3Ny43MTMxNjY2NjcsMCwwLDAsMCwxLDIyNQoyMDIzLTA0LTAxLFNILDE4OTM4NzAuNzgwMDAwMDAwLDUyMTQ1MS4zNjcwMDAwMDAsNjMxMjkuMDI2MDAwMDAwLDE3MzgxLjcxMjIzMzMzMywwLDAsMCwwLDEsMjI2CjIwMjMtMDUtMDEsQUIxNiwzMDIxODMuNTYwMDAwMDAwLDc4OTUxLjAwMDAwMDAwMCw5NzQ3Ljg1Njc3NDE5NCwyNTQ2LjgwNjQ1MTYxMywwLDAsMCwwLDEsMjI3CjIwMjMtMDUtMDEsQU0sODM4LjM0MDAwMDAwMCw2NTQ2NDMuMjcwMDAwMDAwLDI3LjA0MzIyNTgwNiwyMTExNy41MjQ4Mzg3MTAsMCwwLDAsMCwxLDIyOAoyMDIzLTA1LTAxLEFQLDk4MjMwLjI2NDAwMDAwMCwxNTE3Ny41MjUwMDAwMDAsMzE2OC43MTgxOTM1NDgsNDg5LjU5NzU4MDY0NSwwLDAsMCwwLDEsMjI5CjIwMjMtMDUtMDEsQVUsMjIxOTI1Ni4wMTAwMDAwMDAsMjg0NTU4LjI3MzAwMDAwMCw3MTU4OC45MDM1NDgzODcsOTE3OS4yOTkxMjkwMzIsMCwwLDAsMCwxLDIzMAoyMDIzLTA1LTAxLENVLDYyMTY1Mi43MjAwMDAwMDAsMTQ4NDA4LjIxMDAwMDAwMCwyMDA1My4zMTM1NDgzODcsNDc4Ny4zNjE2MTI5MDMsMCwwLDAsMCwxLDIzMQoyMDIzLTA1LTAxLEVZLDkxOTMxNS43MTAwMDAwMDAsMTc0NzE2LjgyNTAwMDAwMCwyOTY1NS4zNDU0ODM4NzEsNTYzNi4wMjY2MTI5MDMsMCwwLDAsMCwxLDIzMgoyMDIzLTA1LTAxLElOLDQ1ODU3Ny4wNzAwMDAwMDAsMTA5ODczLjcyMDAwMDAwMCwxNDc5Mi44MDg3MDk2NzcsMzU0NC4zMTM1NDgzODcsMCwwLDAsMCwxLDIzMwoyMDIzLTA1LTAxLElUVCwxNzEzMTAyLjg2NjAwMDAwMCw3ODE1Ni43MTgwMDAwMDAsNTUyNjEuMzgyNzc0MTk0LDI1MjEuMTg0NDUxNjEzLDAsMCwwLDAsMSwyMzQKMjAyMy0wNS0wMSxMQSwzMTYwMDYuNTcwMDAwMDAwLDIxODk3Ni4wMzkwMDAwMDAsMTAxOTMuNzYwMzIyNTgxLDcwNjMuNzQzMTkzNTQ4LDAsMCwwLDAsMSwyMzUKMjAyMy0wNS0wMSxMSSwzNTE1MTIuOTkwMDAwMDAwLDMyOTQ4MS44NDQwMDAwMDAsMTEzMzkuMTI4NzA5Njc3LDEwNjI4LjQ0NjU4MDY0NSwwLDAsMCwwLDEsMjM2CjIwMjMtMDUtMDEsT1ksNTg1MjQzLjA5MDAwMDAwMCwzMDMyOS4wNzQwMDAwMDAsMTg4NzguODA5MzU0ODM5LDk3OC4zNTcyMjU4MDYsMCwwLDAsMCwxLDIzNwoyMDIzLTA1LTAxLFBBLDIzOTkyNS45MjAwMDAwMDAsMjgzMzE0LjA3MzAwMDAwMCw3NzM5LjU0NTgwNjQ1Miw5MTM5LjE2MzY0NTE2MSwwLDAsMCwwLDEsMjM4CjIwMjMtMDUtMDEsU0EsMjE4MTA1Mi4yMTAwMDAwMDAsNjIzNjUzLjc4OTAwMDAwMCw3MDM1Ni41MjI5MDMyMjYsMjAxMTcuODY0MTYxMjkwLDAsMCwwLDAsMSwyMzkKMjAyMy0wNS0wMSxTSCwxOTE5Mjc3LjMyMDAwMDAwMCw1MzA5MzUuMTUzMDAwMDAwLDYxOTEyLjE3MTYxMjkwMywxNzEyNi45NDA0MTkzNTUsMCwwLDAsMCwxLDI0MAoyMDIzLTA2LTAxLEFCMTYsMjk0OTIyLjYwMDAwMDAwMCw3OTA2NS4wMDAwMDAwMDAsOTgzMC43NTMzMzMzMzMsMjYzNS41MDAwMDAwMDAsMCwwLDAsMCwxLDI0MQoyMDIzLTA2LTAxLEFNLDgxMS42MTAwMDAwMDAsNjMwMTIyLjM3MDAwMDAwMCwyNy4wNTM2NjY2NjcsMjEwMDQuMDc5MDAwMDAwLDAsMCwwLDAsMSwyNDIKMjAyMy0wNi0wMSxBUCw5NjIzNy4xNTkwMDAwMDAsMTUzMTIuMjU2MDAwMDAwLDMyMDcuOTA1MzAwMDAwLDUxMC40MDg1MzMzMzMsMCwwLDAsMCwxLDI0MwoyMDIzLTA2LTAxLEFVLDIxMTkxNTQuODYwMDAwMDAwLDI3ODU4Ni44ODYwMDAwMDAsNzA2MzguNDk1MzMzMzMzLDkyODYuMjI5NTMzMzMzLDAsMCwwLDAsMSwyNDQKMjAyMy0wNi0wMSxDVSw1OTU0MDguMTcwMDAwMDAwLDE0NTIzMC4yNjAwMDAwMDAsMTk4NDYuOTM5MDAwMDAwLDQ4NDEuMDA4NjY2NjY3LDAsMCwwLDAsMSwyNDUKMjAyMy0wNi0wMSxFWSw5MDU5MjUuNDIwMDAwMDAwLDE4MjM4Ni40NzQwMDAwMDAsMzAxOTcuNTE0MDAwMDAwLDYwNzkuNTQ5MTMzMzMzLDAsMCwwLDAsMSwyNDYKMjAyMy0wNi0wMSxJTiw0MjU4NjUuMzcwMDAwMDAwLDEwMzM4NC4xNjYwMDAwMDAsMTQxOTUuNTEyMzMzMzMzLDM0NDYuMTM4ODY2NjY3LDAsMCwwLDAsMSwyNDcKMjAyMy0wNi0wMSxJVFQsMTY4NTc5NC4wMDEwMDAwMDAsNzk1MTMuMTQzMDAwMDAwLDU2MTkzLjEzMzM2NjY2NywyNjUwLjQzODEwMDAwMCwwLDAsMCwwLDEsMjQ4CjIwMjMtMDYtMDEsTEEsMzA2NjgyLjY4MDAwMDAwMCwyMTk3NDAuOTQ4MDAwMDAwLDEwMjIyLjc1NjAwMDAwMCw3MzI0LjY5ODI2NjY2NywwLDAsMCwwLDEsMjQ5CjIwMjMtMDYtMDEsTEksMzQzMjI1Ljc4MDAwMDAwMCwzMjEyMzMuNTIyMDAwMDAwLDExNDQwLjg1OTMzMzMzMywxMDcwNy43ODQwNjY2NjcsMCwwLDAsMCwxLDI1MAoyMDIzLTA2LTAxLE9ZLDU1NzA4NS4yMjAwMDAwMDAsMjkyMzcuNTUyMDAwMDAwLDE4NTY5LjUwNzMzMzMzMyw5NzQuNTg1MDY2NjY3LDAsMCwwLDAsMSwyNTEKMjAyMy0wNi0wMSxQQSwyMzYzNzcuMDQwMDAwMDAwLDI4NzY3NS40NzcwMDAwMDAsNzg3OS4yMzQ2NjY2NjcsOTU4OS4xODI1NjY2NjcsMCwwLDAsMCwxLDI1MgoyMDIzLTA2LTAxLFNBLDIxNTAyODguMTkwMDAwMDAwLDYyNzM2My40NTQwMDAwMDAsNzE2NzYuMjczMDAwMDAwLDIwOTEyLjExNTEzMzMzMywwLDAsMCwwLDEsMjUzCjIwMjMtMDYtMDEsU0gsMTg2MTYzMi43MTAwMDAwMDAsNTM1Mzg2LjcyMDAwMDAwMCw2MjA1NC40MjM2NjY2NjcsMTc4NDYuMjI0MDAwMDAwLDAsMCwwLDAsMSwyNTQKMjAyMy0wNy0wMSxBQjE2LDMxNDU0Ny41MjAwMDAwMDAsODQ3NTEuMDAwMDAwMDAwLDEwMTQ2LjY5NDE5MzU0OCwyNzMzLjkwMzIyNTgwNiwwLDAsMCwwLDEsMjU1CjIwMjMtMDctMDEsQU0sODUzLjEzMDAwMDAwMCw2NTA5MjYuOTIwMDAwMDAwLDI3LjUyMDMyMjU4MSwyMDk5Ny42NDI1ODA2NDUsMCwwLDAsMCwxLDI1NgoyMDIzLTA3LTAxLEFQLDEwMTM0Ni4yMjUwMDAwMDAsMTQ4MzMuOTk1MDAwMDAwLDMyNjkuMjMzMDY0NTE2LDQ3OC41MTU5Njc3NDIsMCwwLDAsMCwxLDI1NwoyMDIzLTA3LTAxLEFVLDIyNzU2OTIuMDEwMDAwMDAwLDMwMzgwNi45ODAwMDAwMDAsNzM0MDkuNDE5Njc3NDE5LDk4MDAuMjI1MTYxMjkwLDAsMCwwLDAsMSwyNTgKMjAyMy0wNy0wMSxDVSw2MTAxMDIuMTkwMDAwMDAwLDE0NjU2MS4zMTAwMDAwMDAsMTk2ODAuNzE1ODA2NDUyLDQ3MjcuNzg0MTkzNTQ4LDAsMCwwLDAsMSwyNTkKMjAyMy0wNy0wMSxFWSw5NjM2ODYuNjQ0MDAwMDAwLDE4ODQ3Ni4xNTUwMDAwMDAsMzEwODYuNjY1OTM1NDg0LDYwNzkuODc1OTY3NzQyLDAsMCwwLDAsMSwyNjAKMjAyMy0wNy0wMSxJTiw0MzIxMDIuODAwMDAwMDAwLDEwOTYyMy45MjQwMDAwMDAsMTM5MzguODAwMDAwMDAwLDM1MzYuMjU1NjEyOTAzLDAsMCwwLDAsMSwyNjEKMjAyMy0wNy0wMSxJVFQsMTc3MDc0NS4xNDEwMDAwMDAsODg0ODEuMjU4MDAwMDAwLDU3MTIwLjgxMTAwMDAwMCwyODU0LjIzNDEyOTAzMiwwLDAsMCwwLDEsMjYyCjIwMjMtMDctMDEsTEEsMzE5NjIxLjQzMDAwMDAwMCwyMjc4MjcuMTExMDAwMDAwLDEwMzEwLjM2ODcwOTY3Nyw3MzQ5LjI2MTY0NTE2MSwwLDAsMCwwLDEsMjYzCjIwMjMtMDctMDEsTEksMzQ1OTc0LjIwMDAwMDAwMCwzNDM5MjguMTc2MDAwMDAwLDExMTYwLjQ1ODA2NDUxNiwxMTA5NC40NTcyOTAzMjMsMCwwLDAsMCwxLDI2NAoyMDIzLTA3LTAxLE9ZLDU3ODM2NC44NDAwMDAwMDAsMjk5NzUuOTQxMDAwMDAwLDE4NjU2LjkzMDMyMjU4MSw5NjYuOTY1ODM4NzEwLDAsMCwwLDAsMSwyNjUKMjAyMy0wNy0wMSxQQSwyNTk0MzIuMDYwMDAwMDAwLDI5OTA3OC4xMTEwMDAwMDAsODM2OC43NzYxMjkwMzIsOTY0Ny42ODEwMDAwMDAsMCwwLDAsMCwxLDI2NgoyMDIzLTA3LTAxLFNBLDIyMjQ1NDkuNzcwMDAwMDAwLDY1NDA5My4zNDgwMDAwMDAsNzE3NTkuNjcwMDAwMDAwLDIxMDk5Ljc4NTQxOTM1NSwwLDAsMCwwLDEsMjY3CjIwMjMtMDctMDEsU0gsMTg4Nzg4NC4yMjAwMDAwMDAsNTU5MjMxLjQ5NDAwMDAwMCw2MDg5OS40OTA5Njc3NDIsMTgwMzkuNzI1NjEyOTAzLDAsMCwwLDAsMSwyNjgKMjAyMy0wOC0wMSxBQjE2LDMxMTgyNy4xOTAwMDAwMDAsODU3OTEuMDAwMDAwMDAwLDEwMDU4Ljk0MTYxMjkwMywyNzY3LjQ1MTYxMjkwMywwLDAsMCwwLDEsMjY5CjIwMjMtMDgtMDEsQU0sMTA1NS4yMDAwMDAwMDAsNjQ5NTE4LjQ4MDAwMDAwMCwzNC4wMzg3MDk2NzcsMjA5NTIuMjA5MDMyMjU4LDAsMCwwLDAsMSwyNzAKMjAyMy0wOC0wMSxBUCwxMDE2NTAuMTk3MDAwMDAwLDE0ODg2LjQ4ODAwMDAwMCwzMjc5LjAzODYxMjkwMyw0ODAuMjA5MjkwMzIzLDAsMCwwLDAsMSwyNzEKMjAyMy0wOC0wMSxBVSwyMzkyODAyLjA0MDAwMDAwMCwzMjE0NjUuOTMwMDAwMDAwLDc3MTg3LjE2MjU4MDY0NSwxMDM2OS44Njg3MDk2NzcsMCwwLDAsMCwxLDI3MgoyMDIzLTA4LTAxLENVLDU5MTYyNC4xNjAwMDAwMDAsMTQ0MzM5LjIyOTAwMDAwMCwxOTA4NC42NTAzMjI1ODEsNDY1Ni4xMDQxNjEyOTAsMCwwLDAsMCwxLDI3MwoyMDIzLTA4LTAxLEVZLDk3Mjc2NC43NjAwMDAwMDAsMTkxOTQ1LjY4MjAwMDAwMCwzMTM3OS41MDgzODcwOTcsNjE5MS43OTYxOTM1NDgsMCwwLDAsMCwxLDI3NAoyMDIzLTA4LTAxLElOLDQxNDk5OS4wNTAwMDAwMDAsMTAyMTQ4LjMzMzAwMDAwMCwxMzM4Ny4wNjYxMjkwMzIsMzI5NS4xMDc1MTYxMjksMCwwLDAsMCwxLDI3NQoyMDIzLTA4LTAxLElUVCwxNzc1NjgzLjIwMzAwMDAwMCw4ODM4Ni4xMzUwMDAwMDAsNTcyODAuMTAzMzIyNTgxLDI4NTEuMTY1NjQ1MTYxLDAsMCwwLDAsMSwyNzYKMjAyMy0wOC0wMSxMQSwzMjQxNjEuODAwMDAwMDAwLDIzNDExMi44NzgwMDAwMDAsMTA0NTYuODMyMjU4MDY1LDc1NTIuMDI4MzIyNTgxLDAsMCwwLDAsMSwyNzcKMjAyMy0wOC0wMSxMSSwzMzU1MjUuNjYwMDAwMDAwLDM0ODAyNi4yNDUwMDAwMDAsMTA4MjMuNDA4Mzg3MDk3LDExMjI2LjY1MzA2NDUxNiwwLDAsMCwwLDEsMjc4CjIwMjMtMDgtMDEsT1ksNTcwMzg3Ljg0MDAwMDAwMCwyOTA4NC42NDAwMDAwMDAsMTgzOTkuNjA3NzQxOTM1LDkzOC4yMTQxOTM1NDgsMCwwLDAsMCwxLDI3OQoyMDIzLTA4LTAxLFBBLDI4Mjc3OS43MzAwMDAwMDAsMjkzNjQ4Ljc4ODAwMDAwMCw5MTIxLjkyNjc3NDE5NCw5NDcyLjU0MTU0ODM4NywwLDAsMCwwLDEsMjgwCjIwMjMtMDgtMDEsU0EsMjI1MTEzNy45OTAwMDAwMDAsNjY4OTEyLjQ0MjAwMDAwMCw3MjYxNy4zNTQ1MTYxMjksMjE1NzcuODIwNzA5Njc3LDAsMCwwLDAsMSwyODEKMjAyMy0wOC0wMSxTSCwxODU3NTQ0LjA3MDAwMDAwMCw1NjMyODkuMzYwMDAwMDAwLDU5OTIwLjc3NjQ1MTYxMywxODE3MC42MjQ1MTYxMjksMCwwLDAsMCwxLDI4MgoyMDIzLTA5LTAxLEFCMTYsMjk1NDUxLjA1MDAwMDAwMCw4MzEwMy4zODAwMDAwMDAsOTg0OC4zNjgzMzMzMzMsMjc3MC4xMTI2NjY2NjcsMCwwLDAsMCwxLDI4MwoyMDIzLTA5LTAxLEFNLDExMDkuODAwMDAwMDAwLDYyNjcxNC4wMjAwMDAwMDAsMzYuOTkzMzMzMzMzLDIwODkwLjQ2NzMzMzMzMywwLDAsMCwwLDEsMjg0CjIwMjMtMDktMDEsQVAsOTYyODguMjA5MDAwMDAwLDE0MDYwLjQwNTAwMDAwMCwzMjA5LjYwNjk2NjY2Nyw0NjguNjgwMTY2NjY3LDAsMCwwLDAsMSwyODUKMjAyMy0wOS0wMSxBVSwyMzY2NjAyLjk2MDAwMDAwMCwzMTc1NjUuMjcxMDAwMDAwLDc4ODg2Ljc2NTMzMzMzMywxMDU4NS41MDkwMzMzMzMsMCwwLDAsMCwxLDI4NgoyMDIzLTA5LTAxLENVLDU2NTkwNS41MTAwMDAwMDAsMTQxMzM5LjIxNzAwMDAwMCwxODg2My41MTcwMDAwMDAsNDcxMS4zMDcyMzMzMzMsMCwwLDAsMCwxLDI4NwoyMDIzLTA5LTAxLEVZLDk0MTI3Mi44MDMwMDAwMDAsMTg3OTUyLjc1NTAwMDAwMCwzMTM3NS43NjAxMDAwMDAsNjI2NS4wOTE4MzMzMzMsMCwwLDAsMCwxLDI4OAoyMDIzLTA5LTAxLElOLDM5ODAyNy4zNjAwMDAwMDAsOTIwNzcuNTAwMDAwMDAwLDEzMjY3LjU3ODY2NjY2NywzMDY5LjI1MDAwMDAwMCwwLDAsMCwwLDEsMjg5CjIwMjMtMDktMDEsSVRULDE3MjIzOTguNzg4MDAwMDAwLDg1Mzk5LjkzMjAwMDAwMCw1NzQxMy4yOTI5MzMzMzMsMjg0Ni42NjQ0MDAwMDAsMCwwLDAsMCwxLDI5MAoyMDIzLTA5LTAxLExBLDMxOTUxNS44ODAwMDAwMDAsMjMwMzAxLjkzNTAwMDAwMCwxMDY1MC41MjkzMzMzMzMsNzY3Ni43MzExNjY2NjcsMCwwLDAsMCwxLDI5MQoyMDIzLTA5LTAxLExJLDMyNDExOC4xNDAwMDAwMDAsMjgzOTk4LjcxNTAwMDAwMCwxMDgwMy45MzgwMDAwMDAsOTQ2Ni42MjM4MzMzMzMsMCwwLDAsMCwxLDI5MgoyMDIzLTA5LTAxLE9ZLDU2Mjc5NC44NjAwMDAwMDAsMjg5NjEuMjU2MDAwMDAwLDE4NzU5LjgyODY2NjY2Nyw5NjUuMzc1MjAwMDAwLDAsMCwwLDAsMSwyOTMKMjAyMy0wOS0wMSxQQSwyNzI3ODcuOTUwMDAwMDAwLDI4NTQzMS43MDAwMDAwMDAsOTA5Mi45MzE2NjY2NjcsOTUxNC4zOTAwMDAwMDAsMCwwLDAsMCwxLDI5NAoyMDIzLTA5LTAxLFNBLDIxODM4MjUuMDEwMDAwMDAwLDY2MTIxMS4wMDYwMDAwMDAsNzI3OTQuMTY3MDAwMDAwLDIyMDQwLjM2Njg2NjY2NywwLDAsMCwwLDEsMjk1CjIwMjMtMDktMDEsU0gsMTc3MDMwMi45NTAwMDAwMDAsNTM1Mzg4LjgzOTAwMDAwMCw1OTAxMC4wOTgzMzMzMzMsMTc4NDYuMjk0NjMzMzMzLDAsMCwwLDAsMSwyOTYKMjAyMy0xMC0wMSxBQjE2LDI5MjY5MS4wMjAwMDAwMDAsODQyMTIuODMwMDAwMDAwLDk0NDEuNjQ1ODA2NDUyLDI3MTYuNTQyOTAzMjI2LDAsMCwwLDAsMSwyOTcKMjAyMy0xMC0wMSxBTSwxMDg5LjgwMDAwMDAwMCw2NDI2MjAuNjAwMDAwMDAwLDM1LjE1NDgzODcxMCwyMDcyOS42OTY3NzQxOTQsMCwwLDAsMCwxLDI5OAoyMDIzLTEwLTAxLEFQLDk5MDMwLjQ4MTAwMDAwMCwxMzg2NS42NTcwMDAwMDAsMzE5NC41MzE2NDUxNjEsNDQ3LjI3OTI1ODA2NSwwLDAsMCwwLDEsMjk5CjIwMjMtMTAtMDEsQVUsMjM1ODE4MS4yMzAwMDAwMDAsMzIxMjM1LjU3NjAwMDAwMCw3NjA3MC4zNjIyNTgwNjUsMTAzNjIuNDM3OTM1NDg0LDAsMCwwLDAsMSwzMDAKMjAyMy0xMC0wMSxBViw4MTQuODEwMDAwMDAwLDAuMDAwMDAwMDAwLDI2LjI4NDE5MzU0OCwwLjAwMDAwMDAwMCwwLDAsMCwwLDEsMzAxCjIwMjMtMTAtMDEsQ1UsNTY5MzU1LjY0MDAwMDAwMCwxNDA1MTYuMjQyMDAwMDAwLDE4MzY2LjMxMDk2Nzc0Miw0NTMyLjc4MjAwMDAwMCwwLDAsMCwwLDEsMzAyCjIwMjMtMTAtMDEsRVksOTg1MzY5LjAzMDAwMDAwMCwxODk4MDYuNDUzMDAwMDAwLDMxNzg2LjA5Nzc0MTkzNSw2MTIyLjc4ODgwNjQ1MiwwLDAsMCwwLDEsMzAzCjIwMjMtMTAtMDEsSU4sNDIyNTE1LjMzMDAwMDAwMCwxMDQ5MTguMDAwMDAwMDAwLDEzNjI5LjUyNjc3NDE5NCwzMzg0LjQ1MTYxMjkwMywwLDAsMCwwLDEsMzA0CjIwMjMtMTAtMDEsSVRULDE3ODMyNTcuNDY5MDAwMDAwLDg5NDg0Ljg4MTAwMDAwMCw1NzUyNC40MzQ0ODM4NzEsMjg4Ni42MDkwNjQ1MTYsMCwwLDAsMCwxLDMwNQoyMDIzLTEwLTAxLExBLDMyNDI1Mi4zNTAwMDAwMDAsMjM1ODQ4LjE2MzAwMDAwMCwxMDQ1OS43NTMyMjU4MDYsNzYwOC4wMDUyNTgwNjUsMCwwLDAsMCwxLDMwNgoyMDIzLTEwLTAxLExJLDMyOTc4MS4xODAwMDAwMDAsMjUxOTIwLjgzMDAwMDAwMCwxMDYzOC4xMDI1ODA2NDUsODEyNi40NzgzODcwOTcsMCwwLDAsMCwxLDMwNwoyMDIzLTEwLTAxLE9ZLDU3OTY0Mi4xOTAwMDAwMDAsMjk5MjYuMjQwMDAwMDAwLDE4Njk4LjEzNTE2MTI5MCw5NjUuMzYyNTgwNjQ1LDAsMCwwLDAsMSwzMDgKMjAyMy0xMC0wMSxQQSwyODQ5MzYuNTYwMDAwMDAwLDI5NjE3MC4zNjkwMDAwMDAsOTE5MS41MDE5MzU0ODQsOTU1My44ODI4NzA5NjgsMCwwLDAsMCwxLDMwOQoyMDIzLTEwLTAxLFNBLDIzMjMzNDEuODgwMDAwMDAwLDcxOTY5Mi4zNzkwMDAwMDAsNzQ5NDYuNTEyMjU4MDY1LDIzMjE1Ljg4MzE5MzU0OCwwLDAsMCwwLDEsMzEwCjIwMjMtMTAtMDEsU0gsMTg1OTE1OC43NjAwMDAwMDAsNTM5NzIwLjgwMzAwMDAwMCw1OTk3Mi44NjMyMjU4MDYsMTc0MTAuMzQ4NDgzODcxLDAsMCwwLDAsMSwzMTEKMjAyMy0xMS0wMSxBQjE2LDMwNTA4Ni41MzAwMDAwMDAsODI3MTQuMjMwMDAwMDAwLDEwMTY5LjU1MTAwMDAwMCwyNzU3LjE0MTAwMDAwMCwwLDAsMCwwLDEsMzEyCjIwMjMtMTEtMDEsQU0sOTcwLjg5MDAwMDAwMCw2MTMxMzQuOTEwMDAwMDAwLDMyLjM2MzAwMDAwMCwyMDQzNy44MzAzMzMzMzMsMCwwLDAsMCwxLDMxMwoyMDIzLTExLTAxLEFQLDk3NjIwLjA3NDAwMDAwMCwxNDAzMy42MTAwMDAwMDAsMzI1NC4wMDI0NjY2NjcsNDY3Ljc4NzAwMDAwMCwwLDAsMCwwLDEsMzE0CjIwMjMtMTEtMDEsQVUsMjM0NjAzOC45MTAwMDAwMDAsMzE2NzIzLjY1MzAwMDAwMCw3ODIwMS4yOTcwMDAwMDAsMTA1NTcuNDU1MTAwMDAwLDAsMCwwLDAsMSwzMTUKMjAyMy0xMS0wMSxDVSw1NzA1NTIuNTkwMDAwMDAwLDEzNTM2MS41MDAwMDAwMDAsMTkwMTguNDE5NjY2NjY3LDQ1MTIuMDUwMDAwMDAwLDAsMCwwLDAsMSwzMTYKMjAyMy0xMS0wMSxFWSw5NjQ4NjIuNjE1MDAwMDAwLDE4OTc2OC4wMzAwMDAwMDAsMzIxNjIuMDg3MTY2NjY3LDYzMjUuNjAxMDAwMDAwLDAsMCwwLDAsMSwzMTcKMjAyMy0xMS0wMSxJTiw0MTcwODUuNDAwMDAwMDAwLDEwMTY5NC4wMDAwMDAwMDAsMTM5MDIuODQ2NjY2NjY3LDMzODkuODAwMDAwMDAwLDAsMCwwLDAsMSwzMTgKMjAyMy0xMS0wMSxJVFQsMTY5MDg2MC41ODEwMDAwMDAsODI1MzIuNTQxMDAwMDAwLDU2MzYyLjAxOTM2NjY2NywyNzUxLjA4NDcwMDAwMCwwLDAsMCwwLDEsMzE5CjIwMjMtMTEtMDEsTEEsMzEzMzg0LjAzMDAwMDAwMCwyMjc4MTQuNTU0MDAwMDAwLDEwNDQ2LjEzNDMzMzMzMyw3NTkzLjgxODQ2NjY2NywwLDAsMCwwLDEsMzIwCjIwMjMtMTEtMDEsTEksMzIwMjQ2Ljg1MDAwMDAwMCwyNTM0ODguNzM4MDAwMDAwLDEwNjc0Ljg5NTAwMDAwMCw4NDQ5LjYyNDYwMDAwMCwwLDAsMCwwLDEsMzIxCjIwMjMtMTEtMDEsT1ksNTU4NzQ4LjE4MDAwMDAwMCwyOTM1Ni42NTUwMDAwMDAsMTg2MjQuOTM5MzMzMzMzLDk3OC41NTUxNjY2NjcsMCwwLDAsMCwxLDMyMgoyMDIzLTExLTAxLFBBLDI4MzY0Mi40NjAwMDAwMDAsMjk2NjUxLjAzMDAwMDAwMCw5NDU0Ljc0ODY2NjY2Nyw5ODg4LjM2NzY2NjY2NywwLDAsMCwwLDEsMzIzCjIwMjMtMTEtMDEsU0EsMjMxNzYyMC41NDAwMDAwMDAsNzA5ODYxLjY2NDAwMDAwMCw3NzI1NC4wMTgwMDAwMDAsMjM2NjIuMDU1NDY2NjY3LDAsMCwwLDAsMSwzMjQKMjAyMy0xMS0wMSxTSCwxNzk1ODI4LjAxMDAwMDAwMCw1MDg0NjQuNTE5MDAwMDAwLDU5ODYwLjkzMzY2NjY2NywxNjk0OC44MTczMDAwMDAsMCwwLDAsMCwxLDMyNQoyMDIzLTEyLTAxLEFCMTYsMzI5NjU4LjgwMDAwMDAwMCw4ODU2MC43NDAwMDAwMDAsMTA2MzQuMTU0ODM4NzEwLDI4NTYuNzk4MDY0NTE2LDAsMCwwLDAsMSwzMjYKMjAyMy0xMi0wMSxBTSwxMDM4LjU0NTAwMDAwMCw2MzkyMTYuNzMwMDAwMDAwLDMzLjUwMTQ1MTYxMywyMDYxOS44OTQ1MTYxMjksMCwwLDAsMCwxLDMyNwoyMDIzLTEyLTAxLEFQLDEwMDU4MS41MzYwMDAwMDAsMTM4NDYuNDg1MDAwMDAwLDMyNDQuNTY1Njc3NDE5LDQ0Ni42NjA4MDY0NTIsMCwwLDAsMCwxLDMyOAoyMDIzLTEyLTAxLEFVLDIzODExOTkuNDAwMDAwMDAwLDMyMDY0My44OTUwMDAwMDAsNzY4MTIuODgzODcwOTY4LDEwMzQzLjM1MTQ1MTYxMywwLDAsMCwwLDEsMzI5CjIwMjMtMTItMDEsQ1UsNjExMTU4Ljc3MDAwMDAwMCwxNDM5NTYuOTM5MDAwMDAwLDE5NzE0Ljc5OTAzMjI1OCw0NjQzLjc3MjIyNTgwNiwwLDAsMCwwLDEsMzMwCjIwMjMtMTItMDEsRVksOTk4ODI3LjQzNzAwMDAwMCwxOTE3MzIuODc1MDAwMDAwLDMyMjIwLjIzOTkwMzIyNiw2MTg0LjkzMTQ1MTYxMywwLDAsMCwwLDEsMzMxCjIwMjMtMTItMDEsSU4sNDQxMTE0LjY2MDAwMDAwMCwxMDIxNzkuNjA4MDAwMDAwLDE0MjI5LjUwNTE2MTI5MCwzMjk2LjExNjM4NzA5NywwLDAsMCwwLDEsMzMyCjIwMjMtMTItMDEsSVRULDE2NjQ1ODMuODc3MDAwMDAwLDgzMzkxLjI5NTAwMDAwMCw1MzY5Ni4yNTQwOTY3NzQsMjY5MC4wNDE3NzQxOTQsMCwwLDAsMCwxLDMzMwoyMDIzLTEyLTAxLExBLDMzNDg5Ni41MDAwMDAwMDAsMjQyOTIyLjQzMDAwMDAwMCwxMDgwMy4xMTI5MDMyMjYsNzgzNi4yMDc0MTkzNTUsMCwwLDAsMCwxLDMzNAoyMDIzLTEyLTAxLExJLDM1NjA0OS42NDAwMDAwMDAsMjc3ODYxLjM2MjAwMDAwMCwxMTQ4NS40NzIyNTgwNjUsODk2My4yNjk3NDE5MzUsMCwwLDAsMCwxLDMzNQoyMDIzLTEyLTAxLE9ZLDU4MDQyMi44MjAwMDAwMDAsMzA1MTAuMDA4MDAwMDAwLDE4NzIzLjMxNjc3NDE5NCw5ODQuMTkzODA2NDUyLDAsMCwwLDAsMSwzMzYKMjAyMy0xMi0wMSxQQSwzMDEzNDcuNDkwMDAwMDAwLDMxMDUxNS45NzAwMDAwMDAsOTcyMC44ODY3NzQxOTQsMTAwMTYuNjQ0MTkzNTQ4LDAsMCwwLDAsMSwzMzcKMjAyMy0xMi0wMSxTQSwyMzU0MzY4LjI1MDAwMDAwMCw3NjQ4MjcuNzYzMDAwMDAwLDc1OTQ3LjM2MjkwMzIyNiwyNDY3MS44NjMzMjI1ODEsMCwwLDAsMCwxLDMzOAoyMDIzLTEyLTAxLFNILDE4NzE1OTMuMzYwMDAwMDAwLDUyMTIwMy41ODAwMDAwMDAsNjAzNzMuOTc5MzU0ODM5LDE2ODEzLjAxODcwOTY3NywwLDAsMCwwLDEsMzM5CjIwMjQtMDEtMDEsQUIxNiwzMzM2NzguOTQwMDAwMDAwLDg4MDA1LjQyMDAwMDAwMCwxMDc2My44MzY3NzQxOTQsMjgzOC44ODQ1MTYxMjksMCwwLDAsMCwxLDM0MAoyMDI0LTAxLTAxLEFNLDEwMTkuODcwMDAwMDAwLDY0MzI4Ni44MzAwMDAwMDAsMzIuODk5MDMyMjU4LDIwNzUxLjE4ODA2NDUxNiwwLDAsMCwwLDEsMzQxCjIwMjQtMDEtMDEsQVAsMTAwODM3Ljc4NzAwMDAwMCwxNDUxNC45NDQwMDAwMDAsMzI1Mi44MzE4Mzg3MTAsNDY4LjIyNDAwMDAwMCwwLDAsMCwwLDEsMzQyCjIwMjQtMDEtMDEsQVUsMjQyNDk2OS42MzAwMDAwMDAsMzIzMzAyLjA0MTAwMDAwMCw3ODIyNC44MjY3NzQxOTQsMTA0MjkuMDk4MDk2Nzc0LDAsMCwwLDAsMSwzNDMKMjAyNC0wMS0wMSxDVSw2MTQyNjQuOTMwMDAwMDAwLDE0NDE0Mi44NjcwMDAwMDAsMTk4MTQuOTk3NzQxOTM1LDQ2NDkuNzY5OTAzMjI2LDAsMCwwLDAsMSwzNDQKMjAyNC0wMS0wMSxFWSw5ODgxNjguMDkzMDAwMDAwLDE5ODk2MS4yNzYwMDAwMDAsMzE4NzYuMzkwMDk2Nzc0LDY0MTguMTA1Njc3NDE5LDAsMCwwLDAsMSwzNDUKMjAyNC0wMS0wMSxJTiw0Mjc1MjYuOTEwMDAwMDAwLDEwMTM4Ny4zNzUwMDAwMDAsMTM3OTEuMTkwNjQ1MTYxLDMyNzAuNTYwNDgzODcxLDAsMCwwLDAsMSwzNDYKMjAyNC0wMS0wMSxJVFQsMTcxNTU4MS4yMDAwMDAwMDAsODU4MzQuMDg1MDAwMDAwLDU1MzQxLjMyOTAzMjI1OCwyNzY4Ljg0MTQ1MTYxMywwLDAsMCwwLDEsMzQ3CjIwMjQtMDEtMDEsTEEsMzM4MDE2LjE1MDAwMDAwMCwyNDIwNTMuOTE2MDAwMDAwLDEwOTAzLjc0Njc3NDE5NCw3ODA4LjE5MDgzODcxMCwwLDAsMCwwLDEsMzQ4CjIwMjQtMDEtMDEsTEksMzQ4Mjg5LjAwMDAwMDAwMCwyNzc5ODUuMzg3MDAwMDAwLDExMjM1LjEyOTAzMjI1OCw4OTY3LjI3MDU0ODM4NywwLDAsMCwwLDEsMzQ5CjIwMjQtMDEtMDEsT1ksNTc5NDE0LjUwMDAwMDAwMCwzMDQzMy4xODgwMDAwMDAsMTg2OTAuNzkwMzIyNTgxLDk4MS43MTU3NDE5MzUsMCwwLDAsMCwxLDM1MAoyMDI0LTAxLTAxLFBBLDI5OTkyMS4wOTAwMDAwMDAsMzE0OTI1LjY1NDAwMDAwMCw5Njc0Ljg3Mzg3MDk2OCwxMDE1OC44OTIwNjQ1MTYsMCwwLDAsMCwxLDM1MQoyMDI0LTAxLTAxLFNBLDI0NTY5NTguNjcwMDAwMDAwLDc1ODQ5Ny42NzIwMDAwMDAsNzkyNTYuNzMxMjkwMzIzLDI0NDY3LjY2NjgzODcxMCwwLDAsMCwwLDEsMzUyCjIwMjQtMDEtMDEsU0gsMTgxNDczMC4yNTAwMDAwMDAsNTAwMDAyLjU2MDAwMDAwMCw1ODUzOS42ODU0ODM4NzEsMTYxMjkuMTE0ODM4NzEwLDAsMCwwLDAsMSwzNTMKMjAyNC0wMi0wMSxBQjE2LDMyNzY3NS4wMzAwMDAwMDAsODYxMTYuODIwMDAwMDAwLDExMjk5LjEzODk2NTUxNywyOTY5LjU0NTUxNzI0MSwwLDAsMCwwLDEsMzU0CjIwMjQtMDItMDEsQU0sOTg1LjM5MDAwMDAwMCw2MDE1OTYuNjIwMDAwMDAwLDMzLjk3ODk2NTUxNywyMDc0NC43MTEwMzQ0ODMsMCwwLDAsMCwxLDM1NQoyMDI0LTAyLTAxLEFQLDg4MDA5Ljg2MzAwMDAwMCwxMjQyMS4xMjMwMDAwMDAsMzAzNC44MjI4NjIwNjksNDI4LjMxNDU4NjIwNywwLDAsMCwwLDEsMzU2CjIwMjQtMDItMDEsQVUsMjI1MzU3Ny41MjAwMDAwMDAsMzAwMDcyLjUwMjAwMDAwMCw3NzcwOS41Njk2NTUxNzIsMTAzNDcuMzI3NjU1MTcyLDAsMCwwLDAsMSwzNTcKMjAyNC0wMi0wMSxDVSw1ODA5MjcuMTAwMDAwMDAwLDEzNjY4MS43ODgwMDAwMDAsMjAwMzEuOTY4OTY1NTE3LDQ3MTMuMTY1MTAzNDQ4LDAsMCwwLDAsMSwzNTgKMjAyNC0wMi0wMSxFWSw4OTA5MjEuNjI1MDAwMDAwLDE4ODA4MC4yNTcwMDAwMDAsMzA3MjEuNDM1MzQ0ODI4LDY0ODUuNTI2MTAzNDQ4LDAsMCwwLDAsMSwzNTkKMjAyNC0wMi0wMSxJTiwzOTUwMTQuMjkwMDAwMDAwLDg4ODA5LjI3MTAwMDAwMCwxMzYyMS4xODI0MTM3OTMsMzA2Mi4zODg2NTUxNzIsMCwwLDAsMCwxLDM2MAoyMDI0LTAyLTAxLElUVCwxNTkyMjcxLjI1MjAwMDAwMCw4MDgyMy4yNTAwMDAwMDAsNTQ5MDUuOTA1MjQxMzc5LDI3ODcuMDA4NjIwNjkwLDAsMCwwLDAsMSwzNjEKMjAyNC0wMi0wMSxMQSwzMTI0NDUuOTUwMDAwMDAwLDIyNjk4Ni45OTgwMDAwMDAsMTA3NzMuOTk4Mjc1ODYyLDc4MjcuMTM3ODYyMDY5LDAsMCwwLDAsMSwzNjIKMjAyNC0wMi0wMSxMSSwyOTUxMzguODIwMDAwMDAwLDIyMzE0NS45ODkwMDAwMDAsMTAxNzcuMjAwNjg5NjU1LDc2OTQuNjg5Mjc1ODYyLDAsMCwwLDAsMSwzNjMKMjAyNC0wMi0wMSxPWSw1MjE4NjcuMjUwMDAwMDAwLDI3Mjk5LjgxMjAwMDAwMCwxNzk5NS40MjI0MTM3OTMsOTQxLjM3MjgyNzU4NiwwLDAsMCwwLDEsMzY0CjIwMjQtMDItMDEsUEEsMjcxNTk4Ljg3MDAwMDAwMCwyOTI4ODEuNzYzMDAwMDAwLDkzNjUuNDc4Mjc1ODYyLDEwMDk5LjM3MTEzNzkzMSwwLDAsMCwwLDEsMzY1CjIwMjQtMDItMDEsU0EsMjI1ODYzNC41NTAwMDAwMDAsNzEzNjk2LjM4MTAwMDAwMCw3Nzg4My45NTAwMDAwMDAsMjQ2MTAuMjIwMDM0NDgzLDAsMCwwLDAsMSwzNjYKMjAyNC0wMi0wMSxTSCwxNjgzNTg4LjEzMDAwMDAwMCw0NjM0MTEuNjU1MDAwMDAwLDU4MDU0Ljc2MzEwMzQ0OCwxNTk3OS43MTIyNDEzNzksMCwwLDAsMCwxLDM2NwoyMDI0LTAzLTAxLEFCMTYsMzU3NTMwLjAwMDAwMDAwMCw5NTMyMS45NTAwMDAwMDAsMTE1MzMuMjI1ODA2NDUyLDMwNzQuOTAxNjEyOTAzLDAsMCwwLDAsMSwzNjgKMjAyNC0wMy0wMSxBTSwxMTMyLjc0MDAwMDAwMCw2NDIwMDEuMTkwMDAwMDAwLDM2LjU0MDAwMDAwMCwyMDcwOS43MTU4MDY0NTIsMCwwLDAsMCwxLDM2OQoyMDI0LTAzLTAxLEFQLDg1OTMxLjIwNTAwMDAwMCwxMTc4Ni40NDkwMDAwMDAsMjc3MS45NzQzNTQ4MzksMzgwLjIwODAzMjI1OCwwLDAsMCwwLDEsMzcwCjIwMjQtMDMtMDEsQVUsMjM4MTU4MS4xODAwMDAwMDAsMzE0MzQyLjUwMjAwMDAwMCw3NjgyNS4xOTkzNTQ4MzksMTAxNDAuMDgwNzA5Njc3LDAsMCwwLDAsMSwzNzEKMjAyNC0wMy0wMSxDVSw2MjQ2ODUuNDQwMDAwMDAwLDE2OTkyMC40ODcwMDAwMDAsMjAxNTEuMTQzMjI1ODA2LDU0ODEuMzA2MDMyMjU4LDAsMCwwLDEsMSwzNzIKMjAyNC0wMy0wMSxFWSw5NDg0NjYuNTU2MDAwMDAwLDE5NTAxOS4zNjEwMDAwMDAsMzA1OTUuNjk1MzU0ODM5LDYyOTAuOTQ3MTI5MDMyLDAsMCwwLDAsMSwzNzMKMjAyNC0wMy0wMSxJTiw0MjAwOTAuMTMwMDAwMDAwLDk0MTQwLjcwODAwMDAwMCwxMzU1MS4yOTQ1MTYxMjksMzAzNi43OTcwMzIyNTgsMCwwLDAsMCwxLDM3NAoyMDI0LTAzLTAxLElUVCwxNjQ1Njk3LjgxOTAwMDAwMCw4MzM5MS45OTgwMDAwMDAsNTMwODcuMDI2NDE5MzU1LDI2OTAuMDY0NDUxNjEzLDAsMCwwLDAsMSwzNzUKMjAyNC0wMy0wMSxMQSwzMjI2NDMuMDUwMDAwMDAwLDIyNzYyMi43MTAwMDAwMDAsMTA0MDcuODQwMzIyNTgxLDczNDIuNjY4MDY0NTE2LDAsMCwwLDAsMSwzNzYKMjAyNC0wMy0wMSxMSSwzMjA2ODMuNTkwMDAwMDAwLDIzNjcxOC42NjIwMDAwMDAsMTAzNDQuNjMxOTM1NDg0LDc2MzYuMDg1ODcwOTY4LDAsMCwwLDAsMSwzNzcKMjAyNC0wMy0wMSxPWSw1NzUzNDAuMzAwMDAwMDAwLDMwNzAyLjc0MzAwMDAwMCwxODU1OS4zNjQ1MTYxMjksOTkwLjQxMTA2NDUxNiwwLDAsMCwwLDEsMzc4CjIwMjQtMDMtMDEsUEEsMjY1NDQ4LjM5MDAwMDAwMCwzMDM0MTEuMzcyMDAwMDAwLDg1NjIuODUxMjkwMzIzLDk3ODcuNDYzNjEyOTAzLDAsMCwwLDAsMSwzNzkKMjAyNC0wMy0wMSxTQSwyNDE0NjUzLjk2MDAwMDAwMCw3NTU1MzUuMTM2MDAwMDAwLDc3ODkyLjA2MzIyNTgwNiwyNDM3Mi4xMDExNjEyOTAsMCwwLDAsMCwxLDM4MAoyMDI0LTAzLTAxLFNILDE3Nzk1MTQuNjcwMDAwMDAwLDQ4NjUwMS4wNTcwMDAwMDAsNTc0MDMuNjk5MDMyMjU4LDE1NjkzLjU4MjQ4Mzg3MSwwLDAsMCwwLDEsMzgxCjIwMjQtMDQtMDEsQUIxNiwzMTUzMDIuMDAwMDAwMDAwLDg0MDQwLjU1MDAwMDAwMCwxMDUxMC4wNjY2NjY2NjcsMjgwMS4zNTE2NjY2NjcsMCwwLDAsMCwxLDM4MgoyMDI0LTA0LTAxLEFNLDExMDkuMDcwMDAwMDAwLDYxNTgyMy40MjAwMDAwMDAsMzYuOTY5MDAwMDAwLDIwNTI3LjQ0NzMzMzMzMywwLDAsMCwwLDEsMzgzCjIwMjQtMDQtMDEsQVAsMTAxNjI3Ljk5NzAwMDAwMCwxMzkwOS41OTQwMDAwMDAsMzM4Ny41OTk5MDAwMDAsNDYzLjY1MzEzMzMzMywwLDAsMCwwLDEsMzg0CjIwMjQtMDQtMDEsQVUsMjI2MDI5MS41MzAwMDAwMDAsMjk3MTY2Ljg5MDAwMDAwMCw3NTM0My4wNTEwMDAwMDAsOTkwNS41NjMwMDAwMDAsMCwwLDAsMCwxLDM4NQoyMDI0LTA0LTAxLENVLDU5NDc3NS42MjAwMDAwMDAsMTU0NjY0LjI4NzAwMDAwMCwxOTgyNS44NTQwMDAwMDAsNTE1NS40NzYyMzMzMzMsMCwwLDAsMCwxLDM4NgoyMDI0LTA0LTAxLEVZLDk0MTQxNi4yMTkwMDAwMDAsMTkyNzAwLjQ0NjAwMDAwMCwzMTM4MC41NDA2MzMzMzMsNjQyMy4zNDgyMDAwMDAsMCwwLDAsMCwxLDM4NwoyMDI0LTA0LTAxLElOLDM5Mzg5NC4wMzAwMDAwMDAsOTE4MjYuMzMzMDAwMDAwLDEzMTI5LjgwMTAwMDAwMCwzMDYwLjg3Nzc2NjY2NywwLDAsMCwwLDEsMzg4CjIwMjQtMDQtMDEsSVRULDE1NzI2OTEuNDE0MDAwMDAwLDc4MDYzLjQ4ODAwMDAwMCw1MjQyMy4wNDcxMzMzMzMsMjYwMi4xMTYyNjY2NjcsMCwwLDAsMCwxLDM4OQoyMDI0LTA0LTAxLExBLDMxNDIwOS40OTAwMDAwMDAsMjE0NjIxLjAxMjAwMDAwMCwxMDQ3My42NDk2NjY2NjcsNzE1NC4wMzM3MzMzMzMsMCwwLDAsMCwxLDM5MAoyMDI0LTA0LTAxLExJLDMwNzQzOS4yODAwMDAwMDAsMjM3NDg2LjMwMDAwMDAwMCwxMDI0Ny45NzYwMDAwMDAsNzkxNi4yMTAwMDAwMDAsMCwwLDAsMCwxLDM5MQoyMDI0LTA0LTAxLE9ZLDU1NjE2MC4wNzAwMDAwMDAsMzAwODEuNjcyMDAwMDAwLDE4NTM4LjY2OTAwMDAwMCwxMDAyLjcyMjQwMDAwMCwwLDAsMCwwLDEsMzkyCjIwMjQtMDQtMDEsUEEsMjQ4NjUyLjQ5MDAwMDAwMCwyODY4NTEuMjg3MDAwMDAwLDgyODguNDE2MzMzMzMzLDk1NjEuNzA5NTY2NjY3LDAsMCwwLDAsMSwzOTMKMjAyNC0wNC0wMSxTQSwyMzU5MjkwLjU3MDAwMDAwMCw3NDU5NjQuODAzMDAwMDAwLDc4NjQzLjAxOTAwMDAwMCwyNDg2NS40OTM0MzMzMzMsMCwwLDAsMCwxLDM5NAoyMDI0LTA0LTAxLFNILDE3MzQ2ODMuODMwMDAwMDAwLDQ3NTk0OS4xNDQwMDAwMDAsNTc4MjIuNzk0MzMzMzMzLDE1ODY0Ljk3MTQ2NjY2NywwLDAsMCwwLDEsMzk1CjIwMjQtMDUtMDEsQUIxNiwzMzMzODEuOTEwMDAwMDAwLDg4NzMzLjUyMDAwMDAwMCwxMDc1NC4yNTUxNjEyOTAsMjg2Mi4zNzE2MTI5MDMsMCwwLDAsMCwxLDM5NgoyMDI0LTA1LTAxLEFNLDEwNjIuMTYwMDAwMDAwLDYzMjc1Mi43MTAwMDAwMDAsMzQuMjYzMjI1ODA2LDIwNDExLjM3Nzc0MTkzNSwwLDAsMCwwLDEsMzk3CjIwMjQtMDUtMDEsQVAsMTExNjY5LjI3NzAwMDAwMCwxNDgzNC40ODQwMDAwMDAsMzYwMi4yMzQ3NDE5MzUsNDc4LjUzMTc0MTkzNSwwLDAsMCwwLDEsMzk4CjIwMjQtMDUtMDEsQVUsMjI5Mzg3NC42MzAwMDAwMDAsMzAzNDQ5Ljg4ODAwMDAwMCw3Mzk5NS45NTU4MDY0NTIsOTc4OC43MDYwNjQ1MTYsMCwwLDAsMCwxLDM5OQoyMDI0LTA1LTAxLENVLDU5ODExNS45MDAwMDAwMDAsMTU3NjU4LjQ2MTAwMDAwMCwxOTI5NC4wNjEyOTAzMjMsNTA4NS43NTY4MDY0NTIsMCwwLDAsMCwxLDQwMAoyMDI0LTA1LTAxLEVZLDk3MzUwNC42MjMwMDAwMDAsMTk0ODYwLjM0NjAwMDAwMCwzMTQwMy4zNzQ5MzU0ODQsNjI4NS44MTc2MTI5MDMsMCwwLDAsMCwxLDQwMQoyMDI0LTA1LTAxLElOLDQyMzkwOS44MjAwMDAwMDAsOTQzMTcuMDA2MDAwMDAwLDEzNjc0LjUxMDMyMjU4MSwzMDQyLjQ4NDA2NDUxNiwwLDAsMCwwLDEsNDAyCjIwMjQtMDUtMDEsSVRULDE2MjIxNzUuODUwMDAwMDAwLDgwNTkzLjMwOTAwMDAwMCw1MjMyOC4yNTMyMjU4MDYsMjU5OS43ODQxNjEyOTAsMCwwLDAsMCwxLDQwMwoyMDI0LTA1LTAxLExBLDMzNjIxOC4xMDAwMDAwMDAsMjI3ODI2LjQwNzAwMDAwMCwxMDg0NS43NDUxNjEyOTAsNzM0OS4yMzg5MzU0ODQsMCwwLDAsMCwxLDQwNAoyMDI0LTA1LTAxLExJLDMxNTI1OS41NDAwMDAwMDAsMjQ0NDE1LjkwODAwMDAwMCwxMDE2OS42NjI1ODA2NDUsNzg4NC4zODQxMjkwMzIsMCwwLDAsMCwxLDQwNQoyMDI0LTA1LTAxLE9ZLDU0NTkzNC42NDAwMDAwMDAsMjkxNjcuMjkwMDAwMDAwLDE3NjEwLjc5NDgzODcxMCw5NDAuODgwMzIyNTgxLDAsMCwwLDAsMSw0MDYKMjAyNC0wNS0wMSxQQSwyNjIwNjEuMTYwMDAwMDAwLDI5MzY1Ny44NzIwMDAwMDAsODQ1My41ODU4MDY0NTIsOTQ3Mi44MzQ1ODA2NDUsMCwwLDAsMCwxLDQwNwoyMDI0LTA1LTAxLFNBLDI0NDI0NzcuODcwMDAwMDAwLDc5NzM3NS44MzIwMDAwMDAsNzg3ODkuNjA4NzA5Njc3LDI1NzIxLjgwMTAzMjI1OCwwLDAsMCwwLDEsNDA4CjIwMjQtMDUtMDEsU0gsMTgzNjA2MC41NjAwMDAwMDAsNTAwNDQzLjk1OTAwMDAwMCw1OTIyNy43NjAwMDAwMDAsMTYxNDMuMzUzNTE2MTI5LDAsMCwwLDAsMSw0MDkKMjAyNC0wNi0wMSxBQjE2LDMwNDY2MS4wNjAwMDAwMDAsNzQwMjQuODAwMDAwMDAwLDEwMTU1LjM2ODY2NjY2NywyNDY3LjQ5MzMzMzMzMywwLDAsMCwwLDEsNDEwCjIwMjQtMDYtMDEsQU0sMTAwMC43NTAwMDAwMDAsNjE0NDMwLjA2MDAwMDAwMCwzMy4zNTgzMzMzMzMsMjA0ODEuMDAyMDAwMDAwLDAsMCwwLDAsMSw0MTEKMjAyNC0wNi0wMSxBUCw4NjkwMy40OTEwMDAwMDAsMTEzMjYuODU5MDAwMDAwLDI4OTYuNzgzMDMzMzMzLDM3Ny41NjE5NjY2NjcsMCwwLDAsMCwxLDQxMgoyMDI0LTA2LTAxLEFVLDIxODc5NzAuNjIwMDAwMDAwLDI4NTM3Ny4zMzgwMDAwMDAsNzI5MzIuMzU0MDAwMDAwLDk1MTIuNTc3OTMzMzMzLDAsMCwwLDAsMSw0MTMKMjAyNC0wNi0wMSxDVSw1NzQ3NzguMzUwMDAwMDAwLDE0ODQ5OS4wNzQwMDAwMDAsMTkxNTkuMjc4MzMzMzMzLDQ5NDkuOTY5MTMzMzMzLDAsMCwwLDAsMSw0MTQKMjAyNC0wNi0wMSxFWSw2NjYzOTkuNjI3MDAwMDAwLDEyOTQ5MS41NTEwMDAwMDAsMjIyMTMuMzIwOTAwMDAwLDQzMTYuMzg1MDMzMzMzLDAsMCwxLDAsMSw0MTUKMjAyNC0wNi0wMSxJTiwzMzE4NDcuNDEwMDAwMDAwLDcwNDkyLjY2ODAwMDAwMCwxMTA2MS41ODAzMzMzMzMsMjM0OS43NTU2MDAwMDAsMCwwLDAsMCwxLDQxNgoyMDI0LTA2LTAxLElUVCwxMDM0MjkwLjI3MjAwMDAwMCw1NDEyNC41NTUwMDAwMDAsMzQ0NzYuMzQyNDAwMDAwLDE4MDQuMTUxODMzMzMzLDAsMCwwLDAsMSw0MTcKMjAyNC0wNi0wMSxMQSwzMjQ5NzEuNzAwMDAwMDAwLDIxNzIzNy4wMjgwMDAwMDAsMTA4MzIuMzkwMDAwMDAwLDcyNDEuMjM0MjY2NjY3LDAsMCwwLDAsMSw0MTgKMjAyNC0wNi0wMSxMSSwzMDIwNDUuMTQwMDAwMDAwLDIzMDk5Mi42NTYwMDAwMDAsMTAwNjguMTcxMzMzMzMzLDc2OTkuNzU1MjAwMDAwLDAsMCwwLDAsMSw0MTkKMjAyNC0wNi0wMSxPWSw1Mjg3NTcuNDgwMDAwMDAwLDI4NDM0Ljc4MzAwMDAwMCwxNzYyNS4yNDkzMzMzMzMsOTQ3LjgyNjEwMDAwMCwwLDAsMCwwLDEsNDIwCjIwMjQtMDYtMDEsUEEsMjM4NjUzLjczMDAwMDAwMCwyODUzNDkuODA2MDAwMDAwLDc5NTUuMTI0MzMzMzMzLDk1MTEuNjYwMjAwMDAwLDAsMCwwLDAsMSw0MjEKMjAyNC0wNi0wMSxTQSwyNDEzNzUyLjEzMDAwMDAwMCw3OTM0NTMuNDc4MDAwMDAwLDgwNDU4LjQwNDMzMzMzMywyNjQ0OC40NDkyNjY2NjcsMCwwLDAsMCwxLDQyMgoyMDI0LTA3LTAxLEFCMTYsMzEyNDM1LjE5MDAwMDAwMCw4Mjc5Mi40NTAwMDAwMDAsMTAwNzguNTU0NTE2MTI5LDI2NzAuNzI0MTkzNTQ4LDAsMCwwLDAsMSw0MjMKMjAyNC0wNy0wMSxBTSwxMDgwLjYwMDAwMDAwMCw2NjA4MTUuMDAwMDAwMDAwLDM0Ljg1ODA2NDUxNiwyMTMxNi42MTI5MDMyMjYsMCwwLDAsMCwxLDQyNAoyMDI0LTA3LTAxLEFQLDEwNTM0OS43MDIwMDAwMDAsMTE4OTguNDU3MDAwMDAwLDMzOTguMzc3NDgzODcxLDM4My44MjExOTM1NDgsMCwwLDAsMCwxLDQyNQoyMDI0LTA3LTAxLEFVLDIyMDI5MTcuMjMwMDAwMDAwLDI4NjI5OC41OTgwMDAwMDAsNzEwNjEuODQ2MTI5MDMyLDkyMzUuNDM4NjQ1MTYxLDAsMCwwLDAsMSw0MjYKMjAyNC0wNy0wMSxDVSw1OTU0NzguNjkwMDAwMDAwLDE1MzczNy44NTAwMDAwMDAsMTkyMDguOTkwMDAwMDAwLDQ5NTkuMjg1NDgzODcxLDAsMCwwLDAsMSw0MjcKMjAyNC0wNy0wMSxFWSw4ODA2MDkuODYyMDAwMDAwLDE0NjI2Mi41MTMwMDAwMDAsMjg0MDYuNzY5NzQxOTM1LDQ3MTguMTQ1NTgwNjQ1LDAsMCwwLDAsMSw0MjgKMjAyNC0wNy0wMSxJTiwzOTQ0MTkuMTkwMDAwMDAwLDgwMjg4LjYzNjAwMDAwMCwxMjcyMy4xOTk2Nzc0MTksMjU4OS45NTYwMDAwMDAsMCwwLDAsMCwxLDQyOQoyMDI0LTA3LTAxLElUVCwxNDIzOTM2LjI3NjAwMDAwMCw3NDczOS4wNTQwMDAwMDAsNDU5MzMuNDI4MjU4MDY1LDI0MTAuOTM3MjI1ODA2LDAsMCwwLDAsMSw0MzAKMjAyNC0wNy0wMSxMQSwzMzk5MTMuMDYwMDAwMDAwLDIzMDYxMy4zNTQwMDAwMDAsMTA5NjQuOTM3NDE5MzU1LDc0MzkuMTQwNDUxNjEzLDAsMCwwLDAsMSw0MzEKMjAyNC0wNy0wMSxMSSwzMDE4MzAuNjcwMDAwMDAwLDIzMTA2My44MTQwMDAwMDAsOTczNi40NzMyMjU4MDYsNzQ1My42NzE0MTkzNTUsMCwwLDAsMCwxLDQzMgoyMDI0LTA3LTAxLE9ZLDU0NTk3My44MTAwMDAwMDAsMjk1ODIuMzQ1MDAwMDAwLDE3NjEyLjA1ODM4NzA5Nyw5NTQuMjY5MTkzNTQ4LDAsMCwwLDAsMSw0MzMKMjAyNC0wNy0wMSxQQSwyNTc0NjIuMDEwMDAwMDAwLDI4MjgxNy41MjcwMDAwMDAsODMwNS4yMjYxMjkwMzIsOTEyMy4xNDYwMzIyNTgsMCwwLDAsMCwxLDQzNAoyMDI0LTA3LTAxLFNBLDIzOTgyMDIuOTAwMDAwMDAwLDc5NzM3Mi45MzIwMDAwMDAsNzczNjEuMzgzODcwOTY4LDI1NzIxLjcwNzQ4Mzg3MSwwLDAsMCwwLDEsNDM1CjIwMjQtMDctMDEsU0gsMTgyODE5NS40MzAwMDAwMDAsNTE2NDgxLjcwMzAwMDAwMCw1ODk3NC4wNDYxMjkwMzIsMTY2NjAuNzAwMDk2Nzc0LDAsMCwwLDAsMSw0MzYKMjAyNC0wOC0wMSxBQjE2LDMyOTcwNC41NzAwMDAwMDAsODkxNjAuOTAwMDAwMDAwLDEwNjM1LjYzMTI5MDMyMywyODc2LjE1ODA2NDUxNiwwLDAsMCwwLDEsNDM3CjIwMjQtMDgtMDEsQU0sMTA2Ny4yNTAwMDAwMDAsNjQ2NDcwLjYxMDAwMDAwMCwzNC40Mjc0MTkzNTUsMjA4NTMuODkwNjQ1MTYxLDAsMCwwLDAsMSw0MzgKMjAyNC0wOC0wMSxBUCwxMTI5NDIuODAyMDAwMDAwLDEzNjQ3LjEzMzAwMDAwMCwzNjQzLjMxNjE5MzU0OCw0NDAuMjMwMDk2Nzc0LDAsMCwwLDAsMSw0MzkKMjAyNC0wOC0wMSxBVSwyMjE1ODc5LjA0MDAwMDAwMCwyOTIwMTAuMjkxMDAwMDAwLDcxNDc5Ljk2OTAzMjI1OCw5NDE5LjY4NjgwNjQ1MiwwLDAsMCwwLDEsNDQwCjIwMjQtMDgtMDEsQ1UsNTk0ODU2LjU1MDAwMDAwMCwxNTA1NzUuNTU3MDAwMDAwLDE5MTg4LjkyMDk2Nzc0Miw0ODU3LjI3NjAzMjI1OCwwLDAsMCwwLDEsNDQxCjIwMjQtMDgtMDEsRVksOTgyNTk0LjU5MTAwMDAwMCwxNzQ3MjYuMjM3MDAwMDAwLDMxNjk2LjU5OTcwOTY3Nyw1NjM2LjMzMDIyNTgwNiwwLDAsMCwwLDEsNDQyCjIwMjQtMDgtMDEsSU4sNDAxODc2LjA1MDAwMDAwMCw4NjY0OS4wMDAwMDAwMDAsMTI5NjMuNzQzNTQ4Mzg3LDI3OTUuMTI5MDMyMjU4LDAsMCwwLDAsMSw0NDMKMjAyNC0wOC0wMSxJVFQsMTU0NTkzOS4zOTcwMDAwMDAsNzU5ODguNjEyMDAwMDAwLDQ5ODY5LjAxMjgwNjQ1MiwyNDUxLjI0NTU0ODM4NywwLDAsMCwwLDEsNDQ0CjIwMjQtMDgtMDEsTEEsMzM0NjM2Ljg5MDAwMDAwMCwyMjY4MzcuMzUyMDAwMDAwLDEwNzk0LjczODM4NzA5Nyw3MzE3LjMzMzkzNTQ4NCwwLDAsMCwwLDEsNDQ1CjIwMjQtMDgtMDEsTEksMjc3NDk1LjcwMDAwMDAwMCwyMTA5NTUuNzcwMDAwMDAwLDg5NTEuNDc0MTkzNTQ4LDY4MDUuMDI0ODM4NzEwLDAsMCwwLDAsMSw0NDYKMjAyNC0wOC0wMSxPWSw1NDY4MzcuOTcwMDAwMDAwLDI5NTQxLjczODAwMDAwMCwxNzYzOS45MzQ1MTYxMjksOTUyLjk1OTI5MDMyMywwLDAsMCwwLDEsNDQ3CjIwMjQtMDgtMDEsUEEsMjU2NjUwLjA5MDAwMDAwMCwyNzQyNjguNTcwMDAwMDAwLDgyNzkuMDM1MTYxMjkwLDg4NDcuMzczMjI1ODA2LDAsMCwwLDAsMSw0NDgKMjAyNC0wOC0wMSxTQSwyMzUzNzIzLjc4MDAwMDAwMCw3Nzc4NjIuNDM0MDAwMDAwLDc1OTI2LjU3MzU0ODM4NywyNTA5Mi4zMzY1ODA2NDUsMCwwLDAsMCwxLDQ0OQoyMDI0LTA4LTAxLFNILDE4MDE1MjUuMjEwMDAwMDAwLDUxNDc2Ni4xMzYwMDAwMDAsNTgxMTMuNzE2NDUxNjEzLDE2NjA1LjM1OTIyNTgwNiwwLDAsMCwwLDEsNDUwCjIwMjQtMDktMDEsQUIxNiwzMTEwMzEuMzYwMDAwMDAwLDc5MTQ0LjY5MDAwMDAwMCwxMDM2Ny43MTIwMDAwMDAsMjYzOC4xNTYzMzMzMzMsMCwwLDAsMCwxLDQ1MQoyMDI0LTA5LTAxLEFNLDk3Ni4yMDAwMDAwMDAsNTkxODQyLjA4MDAwMDAwMCwzMi41NDAwMDAwMDAsMTk3MjguMDY5MzMzMzMzLDAsMCwwLDAsMSw0NTIKMjAyNC0wOS0wMSxBUCwxMDUyMjAuMjc5MDAwMDAwLDEzMTU4LjM2NDAwMDAwMCwzNTA3LjM0MjYzMzMzMyw0MzguNjEyMTMzMzMzLDAsMCwwLDAsMSw0NTMKMjAyNC0wOS0wMSxBVSwyMTY2NjgyLjEzMDAwMDAwMCwyODAyNTMuMjc0MDAwMDAwLDcyMjIyLjczNzY2NjY2Nyw5MzQxLjc3NTgwMDAwMCwwLDAsMCwwLDEsNDU0CjIwMjQtMDktMDEsQ1UsNTY0OTg3LjI3MDAwMDAwMCwxNDQ1NDkuNzc2MDAwMDAwLDE4ODMyLjkwOTAwMDAwMCw0ODE4LjMyNTg2NjY2NywwLDAsMCwwLDEsNDU1CjIwMjQtMDktMDEsRVksOTA1OTUzLjA3MzAwMDAwMCwxNjczNDcuMTQ2MDAwMDAwLDMwMTk4LjQzNTc2NjY2Nyw1NTc4LjIzODIwMDAwMCwwLDAsMCwwLDEsNDU2CjIwMjQtMDktMDEsSU4sNDMyMTc5Ljk3MDAwMDAwMCw5MTc3OC41MDUwMDAwMDAsMTQ0MDUuOTk5MDAwMDAwLDMwNTkuMjgzNTAwMDAwLDAsMCwwLDAsMSw0NTcKMjAyNC0wOS0wMSxJVFQsMTM0NDk4NC4yNTgwMDAwMDAsNjAyMjUuNDE2MDAwMDAwLDQ0ODMyLjgwODYwMDAwMCwyMDA3LjUxMzg2NjY2NywwLDAsMCwwLDEsNDU4CjIwMjQtMDktMDEsTEEsMzIwNTQ5Ljk2MDAwMDAwMCwyMzM2MzEuMzIzMDAwMDAwLDEwNjg0Ljk5ODY2NjY2Nyw3Nzg3LjcxMDc2NjY2NywwLDAsMCwwLDEsNDU5CjIwMjQtMDktMDEsTEksMjY5ODU4LjM4MDAwMDAwMCwxODY1MzQuNTg2MDAwMDAwLDg5OTUuMjc5MzMzMzMzLDYyMTcuODE5NTMzMzMzLDAsMCwwLDAsMSw0NjAKMjAyNC0wOS0wMSxPWSw1MDk2MjQuMTQwMDAwMDAwLDI3MjY3LjUwNzAwMDAwMCwxNjk4Ny40NzEzMzMzMzMsOTA4LjkxNjkwMDAwMCwwLDAsMCwwLDEsNDYxCjIwMjQtMDktMDEsUEEsMjUwODA5Ljg2MDAwMDAwMCwyNjY3ODAuMTcxMDAwMDAwLDgzNjAuMzI4NjY2NjY3LDg4OTIuNjcyMzY2NjY3LDAsMCwwLDAsMSw0NjIKMjAyNC0wOS0wMSxTQSwyMjU2NjE5LjYxMDAwMDAwMCw3NDIyMDguODExMDAwMDAwLDc1MjIwLjY1MzY2NjY2NywyNDc0MC4yOTM3MDAwMDAsMCwwLDAsMCwxLDQ2MwoyMDI0LTA5LTAxLFNILDE3MjI1NzguNzAwMDAwMDAwLDUzMjI0My4xNTcwMDAwMDAsNTc0MTkuMjkwMDAwMDAwLDE3NzQxLjQzODU2NjY2NywwLDAsMCwwLDEsNDY0CjIwMjQtMTAtMDEsQUIxNiwzMjMzMjYuNTQwMDAwMDAwLDgxODEwLjMwMDAwMDAwMCwxMDQyOS44ODgzODcwOTcsMjYzOS4wNDE5MzU0ODQsMCwwLDAsMCwxLDQ2NQoyMDI0LTEwLTAxLEFNLDk3OS4yODAwMDAwMDAsNjA0ODg0LjY1MDAwMDAwMCwzMS41ODk2Nzc0MTksMTk1MTIuNDA4MDY0NTE2LDAsMCwwLDAsMSw0NjYKMjAyNC0xMC0wMSxBUCwxMDI2NzAuNzg3MDAwMDAwLDE0MzA2LjAxNzAwMDAwMCwzMzExLjk2MDg3MDk2OCw0NjEuNDg0NDE5MzU1LDAsMCwwLDAsMSw0NjcKMjAyNC0xMC0wMSxBVSwyMjQ4Nzk4LjkyMDAwMDAwMCwyOTg3ODIuNDAyMDAwMDAwLDcyNTQxLjkwMDY0NTE2MSw5NjM4LjE0MjAwMDAwMCwwLDAsMCwwLDEsNDY4CjIwMjQtMTAtMDEsQ1UsNTg0Mjg3LjIzMDAwMDAwMCwxNDg0NjkuMjUzMDAwMDAwLDE4ODQ3Ljk3NTE2MTI5MCw0Nzg5LjMzMDc0MTkzNSwwLDAsMCwwLDEsNDY5CjIwMjQtMTAtMDEsRVksOTMyODc1LjAxOTAwMDAwMCwxODYwODMuMzQzMDAwMDAwLDMwMDkyLjc0MjU0ODM4Nyw2MDAyLjY4ODQ4Mzg3MSwwLDAsMCwwLDEsNDcwCjIwMjQtMTAtMDEsSU4sNDU4MDg0Ljc2MDAwMDAwMCwxMDE2NjIuNDM4MDAwMDAwLDE0Nzc2LjkyNzc0MTkzNSwzMjc5LjQzMzQ4Mzg3MSwwLDAsMCwwLDEsNDcxCjIwMjQtMTAtMDEsSVRULDEzNzgyNTQuNzM0MDAwMDAwLDY5MTI2Ljc3NDAwMDAwMCw0NDQ1OS44MzAxMjkwMzIsMjIyOS44OTU5MzU0ODQsMCwwLDAsMCwxLDQ3MgoyMDI0LTEwLTAxLExBLDMzNTk2Ny41MDAwMDAwMDAsMjM5NTEzLjExNzAwMDAwMCwxMDgzNy42NjEyOTAzMjMsNzcyNi4yMjk1ODA2NDUsMCwwLDAsMCwxLDQ3MwoyMDI0LTEwLTAxLExJLDI5MDgwMy44MDAwMDAwMDAsMTY2MTA4LjYxMjAwMDAwMCw5MzgwLjc2Nzc0MTkzNSw1MzU4LjM0MjMyMjU4MSwwLDAsMCwwLDEsNDc0CjIwMjQtMTAtMDEsT1ksNTUyMzE3LjQ3MDAwMDAwMCwzMDI1Ny4wNzgwMDAwMDAsMTc4MTYuNjkyNTgwNjQ1LDk3Ni4wMzQ3NzQxOTQsMCwwLDAsMCwxLDQ3NQoyMDI0LTEwLTAxLFBBLDI3ODkzNC4xMjAwMDAwMDAsMjgwNDkwLjExNDAwMDAwMCw4OTk3Ljg3NDgzODcxMCw5MDQ4LjA2ODE5MzU0OCwwLDAsMCwwLDEsNDc2CjIwMjQtMTAtMDEsU0EsMjMyMTc4NS4yNDAwMDAwMDAsNzYxODgxLjE5MTAwMDAwMCw3NDg5Ni4yOTgwNjQ1MTYsMjQ1NzYuODEyNjEyOTAzLDAsMCwwLDAsMSw0NzcKMjAyNC0xMC0wMSxTSCwxNzk0OTA5LjE2MDAwMDAwMCw1NDcwMjcuNTQzMDAwMDAwLDU3OTAwLjI5NTQ4Mzg3MSwxNzY0Ni4wNDk3NzQxOTQsMCwwLDAsMCwxLDQ3OAoyMDI0LTExLTAxLEFCMTYsMzMzMzg1LjE5MDAwMDAwMCw4NjE4NS4xMDAwMDAwMDAsMTExMTIuODM5NjY2NjY3LDI4NzIuODM2NjY2NjY3LDAsMCwwLDAsMSw0NzkKMjAyNC0xMS0wMSxBTSw4NTMuNDUwMDAwMDAwLDU4MzUxOS41OTAwMDAwMDAsMjguNDQ4MzMzMzMzLDE5NDUwLjY1MzAwMDAwMCwwLDAsMCwwLDEsNDgwCjIwMjQtMTEtMDEsQVAsOTU3OTIuNzYzMDAwMDAwLDEzNTI0LjI0MDAwMDAwMCwzMTkzLjA5MjEwMDAwMCw0NTAuODA4MDAwMDAwLDAsMCwwLDAsMSw0ODEKMjAyNC0xMS0wMSxBVSwyMTYwOTk0Ljc1MDAwMDAwMCwyOTAwNTIuOTMxMDAwMDAwLDcyMDMzLjE1ODMzMzMzMyw5NjY4LjQzMTAzMzMzMywwLDAsMCwwLDEsNDgyCjIwMjQtMTEtMDEsQ1UsNTY5NzgzLjQ4MDAwMDAwMCwxNDYwNjYuNTMxMDAwMDAwLDE4OTkyLjc4MjY2NjY2Nyw0ODY4Ljg4NDM2NjY2NywwLDAsMCwwLDEsNDgzCjIwMjQtMTEtMDEsRVksODk4MDE0LjkyMDAwMDAwMCwxNzkxNTIuMDQwMDAwMDAwLDI5OTMzLjgzMDY2NjY2Nyw1OTcxLjczNDY2NjY2NywwLDAsMCwwLDEsNDg0CjIwMjQtMTEtMDEsSU4sNDc2NjQ3LjM5MDAwMDAwMCw5Nzc2Ny4wNDMwMDAwMDAsMTU4ODguMjQ2MzMzMzMzLDMyNTguOTAxNDMzMzMzLDAsMCwwLDAsMSw0ODUKMjAyNC0xMS0wMSxJVFQsMTM1NjI1Ni4wMTcwMDAwMDAsNjgyNjIuNDg0MDAwMDAwLDQ1MjA4LjUzMzkwMDAwMCwyMjc1LjQxNjEzMzMzMywwLDAsMCwwLDEsNDg2CjIwMjQtMTEtMDEsTEEsMzMyNTEwLjM5MDAwMDAwMCwyMzA3ODMuOTAzMDAwMDAwLDExMDgzLjY3OTY2NjY2Nyw3NjkyLjc5Njc2NjY2NywwLDAsMCwwLDEsNDg3CjIwMjQtMTEtMDEsTEksMjg1NjQ2LjkzMDAwMDAwMCwxNTgyNjAuMTQ5MDAwMDAwLDk1MjEuNTY0MzMzMzMzLDUyNzUuMzM4MzAwMDAwLDAsMCwwLDAsMSw0ODgKMjAyNC0xMS0wMSxPWSw1NDE4NTkuMTYwMDAwMDAwLDMwMTk5LjU2MzAwMDAwMCwxODA2MS45NzIwMDAwMDAsMTAwNi42NTIxMDAwMDAsMCwwLDAsMCwxLDQ4OQoyMDI0LTExLTAxLFBBLDMxMTE2NC4yMDAwMDAwMDAsMjY5ODEyLjAzODAwMDAwMCwxMDM3Mi4xNDAwMDAwMDAsODk5My43MzQ2MDAwMDAsMCwwLDAsMCwxLDQ5MAoyMDI0LTExLTAxLFNBLDIyMTM2NTYuMTkwMDAwMDAwLDczNzYwMC45NDkwMDAwMDAsNzM3ODguNTM5NjY2NjY3LDI0NTg2LjY5ODMwMDAwMCwwLDAsMCwwLDEsNDkxCjIwMjQtMTEtMDEsU0gsMTcyNjcxMS4xNDAwMDAwMDAsNTQ4NjA2Ljg4MTAwMDAwMCw1NzU1Ny4wMzgwMDAwMDAsMTgyODYuODk2MDMzMzMzLDAsMCwwLDAsMSw0OTIKMjAyNC0xMi0wMSxBQjE2LDM1Njk1MS43NjAwMDAwMDAsOTc1NTkuODUwMDAwMDAwLDExNTE0LjU3MjkwMzIyNiwzMTQ3LjA5MTkzNTQ4NCwwLDAsMCwwLDEsNDkzCjIwMjQtMTItMDEsQU0sODgyLjQ0MDAwMDAwMCw1OTIwODUuMTEwMDAwMDAwLDI4LjQ2NTgwNjQ1MiwxOTA5OS41MTk2Nzc0MTksMCwwLDAsMCwxLDQ5NAoyMDI0LTEyLTAxLEFQLDEwNjA3My41MTEwMDAwMDAsMTMyODkuNTA3MDAwMDAwLDM0MjEuNzI2MTYxMjkwLDQyOC42OTM3NzQxOTQsMCwwLDAsMCwxLDQ5NQoyMDI0LTEyLTAxLEFVLDIyNDYzNDIuOTIwMDAwMDAwLDMwMjYwOC43MjQwMDAwMDAsNzI0NjIuNjc0ODM4NzEwLDk3NjEuNTcxNzQxOTM1LDAsMCwwLDAsMSw0OTYKMjAyNC0xMi0wMSxDVSw1ODc1ODUuMDUwMDAwMDAwLDE0OTg1Ny4zNTMwMDAwMDAsMTg5NTQuMzU2NDUxNjEzLDQ4MzQuMTA4MTYxMjkwLDAsMCwwLDAsMSw0OTcKMjAyNC0xMi0wMSxFWSw5MTQyNTAuMDA3MDAwMDAwLDE2NDM0NC4wMzMwMDAwMDAsMjk0OTEuOTM1NzA5Njc3LDUzMDEuNDIwNDE5MzU1LDAsMCwwLDAsMSw0OTgKMjAyNC0xMi0wMSxJTiw1MDU3MDIuNTAwMDAwMDAwLDk3OTc0LjA2NjAwMDAwMCwxNjMxMi45ODM4NzA5NjgsMzE2MC40NTM3NDE5MzUsMCwwLDAsMCwxLDQ5OQoyMDI0LTEyLTAxLElUVCwxNDIzNTk1LjUzMjAwMDAwMCw3MzA3Ni42OTYwMDAwMDAsNDU5MjIuNDM2NTE2MTI5LDIzNTcuMzEyNzc0MTk0LDAsMCwwLDAsMSw1MDAKMjAyNC0xMi0wMSxMQSwzMzA4ODcuNDYwMDAwMDAwLDIyNzUwNS4xNzUwMDAwMDAsMTA2NzMuNzg5MDMyMjU4LDczMzguODc2NjEyOTAzLDAsMCwwLDAsMSw1MDEKMjAyNC0xMi0wMSxMSSwyODIzMDYuMjAwMDAwMDAwLDE0NTc3OC4yMjIwMDAwMDAsOTEwNi42NTE2MTI5MDMsNDcwMi41MjMyOTAzMjMsMCwwLDAsMCwxLDUwMgoyMDI0LTEyLTAxLE9ZLDU2NDM4MS44ODAwMDAwMDAsMzEzNjIuMTE0MDAwMDAwLDE4MjA1Ljg2NzA5Njc3NCwxMDExLjY4MTA5Njc3NCwwLDAsMCwwLDEsNTAzCjIwMjQtMTItMDEsUEEsMzczMzg1LjU4MDAwMDAwMCwzMjA0OTUuODc3MDAwMDAwLDEyMDQ0LjY5NjEyOTAzMiwxMDMzOC41NzY2Nzc0MTksMCwwLDAsMCwxLDUwNAoyMDI0LTEyLTAxLFNBLDIyODUwNTAuNjcwMDAwMDAwLDczNzMxNi4xMjUwMDAwMDAsNzM3MTEuMzExOTM1NDg0LDIzNzg0LjM5MTEyOTAzMiwwLDAsMCwwLDEsNTA1CjIwMjQtMTItMDEsU0gsMTcxNzIwOC44MjAwMDAwMDAsNTY4NjE4LjQ0NDAwMDAwMCw1NTM5My44MzI5MDMyMjYsMTgzNDIuNTMwNDUxNjEzLDAsMCwwLDAsMSw1MDYKMjAyNS0wMS0wMSxBQjE2LDM1OTE2Ny41MzAwMDAwMDAsOTY1NzMuMTEwMDAwMDAwLDExNTg2LjA0OTM1NDgzOSwzMTE1LjI2MTYxMjkwMywwLDAsMCwwLDEsNTA3CjIwMjUtMDEtMDEsQU0sOTcyLjM2MDAwMDAwMCw1ODkyMzcuNDMwMDAwMDAwLDMxLjM2NjQ1MTYxMywxOTAwNy42NTkwMzIyNTgsMCwwLDAsMCwxLDUwOAoyMDI1LTAxLTAxLEFQLDEwNjQ4NC41NDgwMDAwMDAsMTM0MjguNTI5MDAwMDAwLDM0MzQuOTg1NDE5MzU1LDQzMy4xNzgzNTQ4MzksMCwwLDAsMCwxLDUwOQoyMDI1LTAxLTAxLEFVLDIyNDc0NjcuMzcwMDAwMDAwLDMwMTk5MS42NzAwMDAwMDAsNzI0OTguOTQ3NDE5MzU1LDk3NDEuNjY2Nzc0MTk0LDAsMCwwLDAsMSw1MTAKMjAyNS0wMS0wMSxBViwxMjI0LjU4MDAwMDAwMCwwLjAwMDAwMDAwMCwzOS41MDI1ODA2NDUsMC4wMDAwMDAwMDAsMCwwLDEsMCwxLDUxMQoyMDI1LTAxLTAxLENVLDU4NjQxMi40NzAwMDAwMDAsMTQ5MDA2LjQ5MzAwMDAwMCwxODkxNi41MzEyOTAzMjMsNDgwNi42NjEwNjQ1MTYsMCwwLDAsMCwxLDUxMgoyMDI1LTAxLTAxLEVZLDkyNDI2Ny4xNjAwMDAwMDAsMTczMDg0LjkzMTAwMDAwMCwyOTgxNS4wNjk2Nzc0MTksNTU4My4zODQ4NzA5NjgsMCwwLDAsMCwxLDUxMwoyMDI1LTAxLTAxLElOLDQ5NTI4Ni40ODAwMDAwMDAsOTg3ODcuOTYyMDAwMDAwLDE1OTc2Ljk4MzIyNTgwNiwzMTg2LjcwODQ1MTYxMywwLDAsMCwwLDEsNTE0CjIwMjUtMDEtMDEsSVRULDEzOTg0NDYuNTcyMDAwMDAwLDcxOTI3Ljc2MDAwMDAwMCw0NTExMS4xNzk3NDE5MzUsMjMyMC4yNTAzMjI1ODEsMCwwLDAsMCwxLDUxNQoyMDI1LTAxLTAxLExBLDMyODMwOS44ODAwMDAwMDAsMjI0MDQxLjg2MTAwMDAwMCwxMDU5MC42NDEyOTAzMjMsNzIyNy4xNTY4MDY0NTIsMCwwLDAsMCwxLDUxNgoyMDI1LTAxLTAxLExJLDI4Njc3Mi44NDAwMDAwMDAsMTUxNTUzLjkwMjAwMDAwMCw5MjUwLjczNjc3NDE5NCw0ODg4LjgzNTU0ODM4NywwLDAsMCwwLDEsNTE3CjIwMjUtMDEtMDEsT1ksNTk0MjI3Ljc5MDAwMDAwMCwzMjEwOS4xODEwMDAwMDAsMTkxNjguNjM4Mzg3MDk3LDEwMzUuNzgwMDMyMjU4LDAsMCwwLDAsMSw1MTgKMjAyNS0wMS0wMSxQQSwzNzcwNzYuNzYwMDAwMDAwLDM0NjQ0OC4zMzMwMDAwMDAsMTIxNjMuNzY2NDUxNjEzLDExMTc1Ljc1MjY3NzQxOSwwLDAsMCwwLDEsNTE5CjIwMjUtMDEtMDEsU0EsMjI5NTU1MS41OTAwMDAwMDAsNzQ3MDMyLjE2MTAwMDAwMCw3NDA1MC4wNTEyOTAzMjMsMjQwOTcuODExNjQ1MTYxLDAsMCwwLDAsMSw1MjAKMjAyNS0wMS0wMSxTSCwxNzQwMDkyLjc3MDAwMDAwMCw1NzcxODAuMTI2MDAwMDAwLDU2MTMyLjAyNDgzODcxMCwxODYxOC43MTM3NDE5MzUsMCwwLDAsMCwxLDUyMQoyMDI1LTAyLTAxLEFCMTYsMzI1NTQ0LjczMDAwMDAwMCw4NTgwOC4wNzAwMDAwMDAsMTE2MjYuNTk3NTAwMDAwLDMwNjQuNTczOTI4NTcxLDAsMCwwLDAsMSw1MjIKMjAyNS0wMi0wMSxBTSw4NjYuMDMwMDAwMDAwLDUyNTc3MS41MDAwMDAwMDAsMzAuOTI5NjQyODU3LDE4Nzc3LjU1MzU3MTQyOSwwLDAsMCwwLDEsNTIzCjIwMjUtMDItMDEsQVAsOTk2MTAuNjY0MDAwMDAwLDEzMzQ0Ljk5OTAwMDAwMCwzNTU3LjUyMzcxNDI4Niw0NzYuNjA3MTA3MTQzLDAsMCwwLDAsMSw1MjQKMjAyNS0wMi0wMSxBVSwxOTQ3NDE4LjQ0MDAwMDAwMCwyNTg0NzkuOTY1MDAwMDAwLDY5NTUwLjY1ODU3MTQyOSw5MjMxLjQyNzMyMTQyOSwwLDAsMCwwLDEsNTI1CjIwMjUtMDItMDEsQVYsNzM2LjE1MDAwMDAwMCwwLjAwMDAwMDAwMCwyNi4yOTEwNzE0MjksMC4wMDAwMDAwMDAsMCwwLDAsMCwxLDUyNgoyMDI1LTAyLTAxLENVLDQ5ODc2NS41NTAwMDAwMDAsMTMwNjQ2LjI1MDAwMDAwMCwxNzgxMy4wNTUzNTcxNDMsNDY2NS45Mzc1MDAwMDAsMCwwLDAsMCwxLDUyNwoyMDI1LTAyLTAxLEVZLDgzOTMxNC45NzgwMDAwMDAsMTU4ODcxLjc2MTAwMDAwMCwyOTk3NS41MzQ5Mjg1NzEsNTY3My45OTE0NjQyODYsMCwwLDAsMCwxLDUyOAoyMDI1LTAyLTAxLElOLDQ0MDY0Mi4xMDAwMDAwMDAsODM0OTQuNDE3MDAwMDAwLDE1NzM3LjIxNzg1NzE0MywyOTgxLjk0MzQ2NDI4NiwwLDAsMCwwLDEsNTI5CjIwMjUtMDItMDEsSVRULDEyNDc5MTkuMzQ4MDAwMDAwLDY0ODMxLjkxMjAwMDAwMCw0NDU2OC41NDgxNDI4NTcsMjMxNS40MjU0Mjg1NzEsMCwwLDAsMCwxLDUzMAoyMDI1LTAyLTAxLExBLDI5NjA4MC44NDAwMDAwMDAsMjAyNDIxLjQzODAwMDAwMCwxMDU3NC4zMTU3MTQyODYsNzIyOS4zMzcwNzE0MjksMCwwLDAsMCwxLDUzMQoyMDI1LTAyLTAxLExJLDI0OTY2NC4yODAwMDAwMDAsMTM0MzQ1LjI4MDAwMDAwMCw4OTE2LjU4MTQyODU3MSw0Nzk4LjA0NTcxNDI4NiwwLDAsMCwwLDEsNTMyCjIwMjUtMDItMDEsT1ksNTQ0NzM3LjAyMDAwMDAwMCwyOTY5NS43NjAwMDAwMDAsMTk0NTQuODkzNTcxNDI5LDEwNjAuNTYyODU3MTQzLDAsMCwwLDAsMSw1MzMKMjAyNS0wMi0wMSxQQSwzNDU4MTcuMjgwMDAwMDAwLDMwNzY2My40NDkwMDAwMDAsMTIzNTAuNjE3MTQyODU3LDEwOTg3Ljk4MDMyMTQyOSwwLDAsMCwwLDEsNTM0CjIwMjUtMDItMDEsU0EsMjA5MjMyMS41NzAwMDAwMDAsNjkwNjQzLjA2NDAwMDAwMCw3NDcyNS43NzAzNTcxNDMsMjQ2NjUuODIzNzE0Mjg2LDAsMCwwLDAsMSw1MzUKMjAyNS0wMi0wMSxTSCwxNTQ0NDUxLjI2MDAwMDAwMCw1MTM2NzYuNjAwMDAwMDAwLDU1MTU4Ljk3MzU3MTQyOSwxODM0NS41OTI4NTcxNDMsMCwwLDAsMCwxLDUzNgoyMDI1LTAzLTAxLEFCMTYsMzU2MDc3LjEzMDAwMDAwMCw5MjYxMi4yNTAwMDAwMDAsMTE0ODYuMzU5MDMyMjU4LDI5ODcuNDkxOTM1NDg0LDAsMCwwLDAsMSw1MzcKMjAyNS0wMy0wMSxBTSw4NTUuMDYwMDAwMDAwLDU4MzE0Mi4wMTAwMDAwMDAsMjcuNTgyNTgwNjQ1LDE4ODExLjAzMjU4MDY0NSwwLDAsMCwwLDEsNTM4CjIwMjUtMDMtMDEsQVAsMTE4OTgyLjAwOTAwMDAwMCwxNTEzNi45MDgwMDAwMDAsMzgzOC4xMjkzMjI1ODEsNDg4LjI4NzM1NDgzOSwwLDAsMCwwLDEsNTM5CjIwMjUtMDMtMDEsQVUsMTg4ODQxNC40ODAwMDAwMDAsMjQ5Njg0LjUzMTAwMDAwMCw2MDkxNi41OTYxMjkwMzIsODA1NC4zMzk3MDk2NzcsMCwwLDAsMCwxLDU0MAoyMDI1LTAzLTAxLEFWLDgyMC4zMDAwMDAwMDAsMC4wMDAwMDAwMDAsMjYuNDYxMjkwMzIzLDAuMDAwMDAwMDAwLDAsMCwwLDAsMSw1NDEKMjAyNS0wMy0wMSxDVSw1NDY2MTguMzkwMDAwMDAwLDE0MTY3Ni4wMzkwMDAwMDAsMTc2MzIuODUxMjkwMzIzLDQ1NzAuMTk0ODA2NDUyLDAsMCwwLDAsMSw1NDIKMjAyNS0wMy0wMSxFWSw5MjI2NzcuMDExMDAwMDAwLDE3MTIzMy40MzIwMDAwMDAsMjk3NjMuNzc0NTQ4Mzg3LDU1MjMuNjU5MDk2Nzc0LDAsMCwwLDAsMSw1NDMKMjAyNS0wMy0wMSxJTiw0NjM5NjQuNDIwMDAwMDAwLDkwNTU3Ljk1ODAwMDAwMCwxNDk2Ni41OTQxOTM1NDgsMjkyMS4yMjQ0NTE2MTMsMCwwLDAsMCwxLDU0NAoyMDI1LTAzLTAxLElUVCwxMzY1ODkyLjQ1MDAwMDAwMCw3MTM3OC4yOTkwMDAwMDAsNDQwNjEuMDQ2Nzc0MTk0LDIzMDIuNTI1Nzc0MTk0LDAsMCwwLDAsMSw1NDUKMjAyNS0wMy0wMSxMQSwzMjcyMjMuOTMwMDAwMDAwLDIyMDgxMC44NjUwMDAwMDAsMTA1NTUuNjEwNjQ1MTYxLDcxMjIuOTMxMTI5MDMyLDAsMCwwLDAsMSw1NDYKMjAyNS0wMy0wMSxMSSwyOTQzOTEuODYwMDAwMDAwLDE0ODQwNi4zNDkwMDAwMDAsOTQ5Ni41MTE2MTI5MDMsNDc4Ny4zMDE1ODA2NDUsMCwwLDAsMCwxLDU0NwoyMDI1LTAzLTAxLE9ZLDU5Nzc1Mi4wNzAwMDAwMDAsMzI2MzYuMzEzMDAwMDAwLDE5MjgyLjMyNDgzODcxMCwxMDUyLjc4NDI5MDMyMywwLDAsMCwwLDEsNTQ4CjIwMjUtMDMtMDEsUEEsMzg0Njc5LjkyMDAwMDAwMCwzNDQyNTUuMzQwMDAwMDAwLDEyNDA5LjAyOTY3NzQxOSwxMTEwNS4wMTA5Njc3NDIsMCwwLDAsMCwxLDU0OQoyMDI1LTAzLTAxLFNBLDIzMjU3MDYuMTYwMDAwMDAwLDc2NDE5Mi4yMTMwMDAwMDAsNzUwMjIuNzc5MzU0ODM5LDI0NjUxLjM2MTcwOTY3NywwLDAsMCwwLDEsNTUwCjIwMjUtMDMtMDEsU0gsMTY1NDg4Mi4zMjAwMDAwMDAsNTQ5OTAzLjkwOTAwMDAwMCw1MzM4My4zMDA2NDUxNjEsMTc3MzguODM1Nzc0MTk0LDAsMCwwLDAsMSw1NTEKMjAyNS0wNC0wMSxBQjE2LDMzMjkwNS4zMDAwMDAwMDAsNzkwMjAuMjAwMDAwMDAwLDExMDk2Ljg0MzMzMzMzMywyNjM0LjAwNjY2NjY2NywwLDAsMCwwLDEsNTUyCjIwMjUtMDQtMDEsQU0sODI5Ljc3MDAwMDAwMCw1NDY1NDguODMwMDAwMDAwLDI3LjY1OTAwMDAwMCwxODIxOC4yOTQzMzMzMzMsMCwwLDAsMCwxLDU1MwoyMDI1LTA0LTAxLEFQLDExMTkyMy41MjAwMDAwMDAsMTA3OTguNzAyMDAwMDAwLDM3MzAuNzg0MDAwMDAwLDM1OS45NTY3MzMzMzMsMCwwLDAsMCwxLDU1NAoyMDI1LTA0LTAxLEFVLDIxNDc3NjkuOTEwMDAwMDAwLDI4NjEwMC4zMTgwMDAwMDAsNzE1OTIuMzMwMzMzMzMzLDk1MzYuNjc3MjY2NjY3LDAsMCwwLDAsMSw1NTUKMjAyNS0wNC0wMSxBViw4NTcuNjIwMDAwMDAwLDAuMDAwMDAwMDAwLDI4LjU4NzMzMzMzMywwLjAwMDAwMDAwMCwwLDAsMCwwLDEsNTU2CjIwMjUtMDQtMDEsQ1UsNTQ0MzE3Ljg1MDAwMDAwMCwxNDI2NjQuNTEyMDAwMDAwLDE4MTQzLjkyODMzMzMzMyw0NzU1LjQ4MzczMzMzMywwLDAsMCwwLDEsNTU3CjIwMjUtMDQtMDEsRVksOTEwMzg2Ljg0NzAwMDAwMCwxODE4NzcuODU4MDAwMDAwLDMwMzQ2LjIyODIzMzMzMyw2MDYyLjU5NTI2NjY2NywwLDAsMCwwLDEsNTU4CjIwMjUtMDQtMDEsSU4sNDIyNTYwLjY1MDAwMDAwMCw4Mjc1My40MTMwMDAwMDAsMTQwODUuMzU1MDAwMDAwLDI3NTguNDQ3MTAwMDAwLDAsMCwwLDAsMSw1NTkKMjAyNS0wNC0wMSxJVFQsMTMxMjg0OS40ODMwMDAwMDAsNjg2MTAuMjQ5MDAwMDAwLDQzNzYxLjY0OTQzMzMzMywyMjg3LjAwODMwMDAwMCwwLDAsMCwwLDEsNTYwCjIwMjUtMDQtMDEsTEEsMzI1NDk0Ljc3MDAwMDAwMCwyMTcwMzEuNjU2MDAwMDAwLDEwODQ5LjgyNTY2NjY2Nyw3MjM0LjM4ODUzMzMzMywwLDAsMCwwLDEsNTYxCjIwMjUtMDQtMDEsTEksMjc4ODc4LjUzMDAwMDAwMCwxNDI2NTEuMzE1MDAwMDAwLDkyOTUuOTUxMDAwMDAwLDQ3NTUuMDQzODMzMzMzLDAsMCwwLDAsMSw1NjIKMjAyNS0wNC0wMSxPWSw1NzM3NzYuNDIwMDAwMDAwLDMxMzk2LjY4NjAwMDAwMCwxOTEyNS44ODA2NjY2NjcsMTA0Ni41NTYyMDAwMDAsMCwwLDAsMCwxLDU2MwoyMDI1LTA0LTAxLFBBLDM2ODkxOS43NzAwMDAwMDAsMzQxODQwLjQ5NzAwMDAwMCwxMjI5Ny4zMjU2NjY2NjcsMTEzOTQuNjgzMjMzMzMzLDAsMCwwLDAsMSw1NjQKMjAyNS0wNC0wMSxTQSwyMjUyMjkwLjE2MDAwMDAwMCw3MzQxNjkuODU4MDAwMDAwLDc1MDc2LjMzODY2NjY2NywyNDQ3Mi4zMjg2MDAwMDAsMCwwLDAsMCwxLDU2NQoyMDI1LTA0LTAxLFNILDE2NTQyMDQuMzIwMDAwMDAwLDU0MTk5NS4yODMwMDAwMDAsNTUxNDAuMTQ0MDAwMDAwLDE4MDY2LjUwOTQzMzMzMywwLDAsMCwwLDEsNTY2CjIwMjUtMDUtMDEsQUIxNiwzNDIxMDcuMjcwMDAwMDAwLDg5MDg5LjQxMDAwMDAwMCwxMTAzNS43MTgzODcwOTcsMjg3My44NTE5MzU0ODQsMCwwLDAsMCwxLDU2NwoyMDI1LTA1LTAxLEFNLDg1Ny40MjAwMDAwMDAsNTcxMTA2LjQyMDAwMDAwMCwyNy42NTg3MDk2NzcsMTg0MjIuNzg3NzQxOTM1LDAsMCwwLDAsMSw1NjgKMjAyNS0wNS0wMSxBUCwxMTM3NDMuNjE2MDAwMDAwLDE0MDY3LjI5NTAwMDAwMCwzNjY5LjE0ODkwMzIyNiw0NTMuNzgzNzA5Njc3LDAsMCwwLDAsMSw1NjkKMjAyNS0wNS0wMSxBVSwyMTMwMDA5LjMxMDAwMDAwMCwyODIxNDkuODE4MDAwMDAwLDY4NzA5Ljk3Nzc0MTkzNSw5MTAxLjYwNzAzMjI1OCwwLDAsMCwwLDEsNTcwCjIwMjUtMDUtMDEsQVYsNzAzLjY1MDAwMDAwMCwwLjAwMDAwMDAwMCwyMi42OTgzODcwOTcsMC4wMDAwMDAwMDAsMCwwLDAsMCwxLDU3MQoyMDI1LTA1LTAxLENVLDU3Nzg4MC44MzAwMDAwMDAsMTQ4NTAwLjk4NDAwMDAwMCwxODY0MS4zMTcwOTY3NzQsNDc5MC4zNTQzMjI1ODEsMCwwLDAsMCwxLDU3MgoyMDI1LTA1LTAxLEVZLDkzMzMzNy40MjAwMDAwMDAsMTc4MDAwLjU5NTAwMDAwMCwzMDEwNy42NTg3MDk2NzcsNTc0MS45NTQ2Nzc0MTksMCwwLDAsMCwxLDU3MwoyMDI1LTA1LTAxLElOLDQyMTk1Ny4zNjAwMDAwMDAsNzYyODIuNTQyMDAwMDAwLDEzNjExLjUyNzc0MTkzNSwyNDYwLjcyNzE2MTI5MCwwLDAsMCwwLDEsNTc0CjIwMjUtMDUtMDEsSVRULDEzMzk3MzEuNjg0MDAwMDAwLDY5MDc2Ljg0NTAwMDAwMCw0MzIxNy4xNTEwOTY3NzQsMjIyOC4yODUzMjI1ODEsMCwwLDAsMCwxLDU3NQoyMDI1LTA1LTAxLExBLDM1NjQ0NS4zNTAwMDAwMDAsMjI3MzI1LjcxNTAwMDAwMCwxMTQ5OC4yMzcwOTY3NzQsNzMzMy4wODc1ODA2NDUsMCwwLDAsMCwxLDU3NgoyMDI1LTA1LTAxLExJLDI4MTM1Ny4xMTAwMDAwMDAsMTY0NjkwLjE0OTAwMDAwMCw5MDc2LjAzNTgwNjQ1Miw1MzEyLjU4NTQ1MTYxMywwLDAsMCwwLDEsNTc3CjIwMjUtMDUtMDEsT1ksNTgyMzY2LjQ4MDAwMDAwMCwzMjI3My45OTAwMDAwMDAsMTg3ODYuMDE1NDgzODcxLDEwNDEuMDk2NDUxNjEzLDAsMCwwLDAsMSw1NzgKMjAyNS0wNS0wMSxQQSwzOTA5OTAuMzcwMDAwMDAwLDM2NDM0MS44MTkwMDAwMDAsMTI2MTIuNTkyNTgwNjQ1LDExNzUyLjk2MTkwMzIyNiwwLDAsMCwwLDEsNTc5CjIwMjUtMDUtMDEsU0EsMjMyNDY0My42MTAwMDAwMDAsNzM2OTc1LjI0ODAwMDAwMCw3NDk4OC41MDM1NDgzODcsMjM3NzMuMzk1MDk2Nzc0LDAsMCwwLDAsMSw1ODAKMjAyNS0wNS0wMSxTSCwxNjYyNzg0Ljg0MDAwMDAwMCw1NjY5MzMuNTE5MDAwMDAwLDUzNjM4LjIyMDY0NTE2MSwxODI4OC4xNzgwMzIyNTgsMCwwLDAsMCwxLDU4MQoyMDI1LTA2LTAxLEFCMTYsMzMxMjI2LjE5MDAwMDAwMCw4NzA5My41MDAwMDAwMDAsMTEwNDAuODczMDAwMDAwLDI5MDMuMTE2NjY2NjY3LDAsMCwwLDAsMSw1ODIKMjAyNS0wNi0wMSxBTSw4MzAuMjUwMDAwMDAwLDU0ODE4My4xNDAwMDAwMDAsMjcuNjc1MDAwMDAwLDE4MjcyLjc3MTMzMzMzMywwLDAsMCwwLDEsNTgzCjIwMjUtMDYtMDEsQVAsMTE0MzIxLjk2NDAwMDAwMCwxNDg1Ni4yNTEwMDAwMDAsMzgxMC43MzIxMzMzMzMsNDk1LjIwODM2NjY2NywwLDAsMCwwLDEsNTg0CjIwMjUtMDYtMDEsQVUsMjA4NzIxOC4xNjAwMDAwMDAsMjc1MjMzLjkxNDAwMDAwMCw2OTU3My45Mzg2NjY2NjcsOTE3NC40NjM4MDAwMDAsMCwwLDAsMCwxLDU4NQoyMDI1LTA2LTAxLEFWLDkwNS4wMTAwMDAwMDAsMC4wMDAwMDAwMDAsMzAuMTY3MDAwMDAwLDAuMDAwMDAwMDAwLDAsMCwwLDAsMSw1ODYKMjAyNS0wNi0wMSxDVSw1NjI4NDkuNTQwMDAwMDAwLDE0NTIyMS40NTQwMDAwMDAsMTg3NjEuNjUxMzMzMzMzLDQ4NDAuNzE1MTMzMzMzLDAsMCwwLDAsMSw1ODcKMjAyNS0wNi0wMSxFWSw4OTgxMTUuMjQ3MDAwMDAwLDE3MTczMS44MDkwMDAwMDAsMjk5MzcuMTc0OTAwMDAwLDU3MjQuMzkzNjMzMzMzLDAsMCwwLDAsMSw1ODgKMjAyNS0wNi0wMSxJTiw0MTQ1NjYuODAwMDAwMDAwLDcyOTE4LjA5MDAwMDAwMCwxMzgxOC44OTMzMzMzMzMsMjQzMC42MDMwMDAwMDAsMCwwLDAsMCwxLDU4OQoyMDI1LTA2LTAxLElUVCwxMzEyNTQxLjEzOTAwMDAwMCw2NjQxNS4zNDEwMDAwMDAsNDM3NTEuMzcxMzAwMDAwLDIyMTMuODQ0NzAwMDAwLDAsMCwwLDAsMSw1OTAKMjAyNS0wNi0wMSxMQSwzNDc1ODguODgwMDAwMDAwLDIxODA3NC4xOTgwMDAwMDAsMTE1ODYuMjk2MDAwMDAwLDcyNjkuMTM5OTMzMzMzLDAsMCwwLDAsMSw1OTEKMjAyNS0wNi0wMSxMSSwyNTY1NjIuMjAwMDAwMDAwLDE2MjU1My43MjkwMDAwMDAsODU1Mi4wNzMzMzMzMzMsNTQxOC40NTc2MzMzMzMsMCwwLDAsMCwxLDU5MgoyMDI1LTA2LTAxLE9ZLDU3MDgxOC43NjAwMDAwMDAsMzIwMDcuOTk0MDAwMDAwLDE5MDI3LjI5MjAwMDAwMCwxMDY2LjkzMzEzMzMzMywwLDAsMCwwLDEsNTkzCjIwMjUtMDYtMDEsUEEsMzc1MDQ5LjQzMDAwMDAwMCwzNjU5OTAuNTk1MDAwMDAwLDEyNTAxLjY0NzY2NjY2NywxMjE5OS42ODY1MDAwMDAsMCwwLDAsMCwxLDU5NAoyMDI1LTA2LTAxLFNBLDIyNDMwMDEuNDgwMDAwMDAwLDcxMjg0Mi4yMDYwMDAwMDAsNzQ3NjYuNzE2MDAwMDAwLDIzNzYxLjQwNjg2NjY2NywwLDAsMCwwLDEsNTk1CjIwMjUtMDYtMDEsU0gsMTYxMjk2Ny41MTAwMDAwMDAsNTQ5OTU3LjkwNzAwMDAwMCw1Mzc2NS41ODM2NjY2NjcsMTgzMzEuOTMwMjMzMzMzLDAsMCwwLDAsMSw1OTYKMjAyNS0wNy0wMSxBQjE2LDE4NjQ0NC42MzAwMDAwMDAsNTE5ODQuOTQwMDAwMDAwLDYwMTQuMzQyOTAzMjI2LDE2NzYuOTMzNTQ4Mzg3LDAsMCwxLDEsMSw1OTcKMjAyNS0wNy0wMSxBTSw4NTguODQwMDAwMDAwLDU2OTI1Ni44NDAwMDAwMDAsMjcuNzA0NTE2MTI5LDE4MzYzLjEyMzg3MDk2OCwwLDAsMCwwLDEsNTk4CjIwMjUtMDctMDEsQVAsNDEzMDYuODI5MDAwMDAwLDU3MjYuNDU5MDAwMDAwLDEzMzIuNDc4MzU0ODM5LDE4NC43MjQ0ODM4NzEsMCwwLDEsMSwxLDU5OQoyMDI1LTA3LTAxLEFVLDIyNTA4OS4wMzAwMDAwMDAsMjg5NTcuODkyMDAwMDAwLDcyNjAuOTM2NDUxNjEzLDkzNC4xMjU1NDgzODcsMCwwLDEsMSwxLDYwMAoyMDI1LTA3LTAxLEFWLDI2NC43MTAwMDAwMDAsMC4wMDAwMDAwMDAsOC41MzkwMzIyNTgsMC4wMDAwMDAwMDAsMCwwLDEsMCwxLDYwMQoyMDI1LTA3LTAxLENVLDExNDI2OC42MTAwMDAwMDAsMjkxMDUuODM1MDAwMDAwLDM2ODYuMDg0MTkzNTQ4LDkzOC44OTc5MDMyMjYsMCwwLDEsMSwxLDYwMgoyMDI1LTA3LTAxLEVZLDMxNTY5NC42MTMwMDAwMDAsNjk3NDcuNDUxMDAwMDAwLDEwMTgzLjY5NzE5MzU0OCwyMjQ5LjkxNzc3NDE5NCwwLDAsMSwxLDEsNjAzCjIwMjUtMDctMDEsSU4sMTY2ODQ1LjM0MDAwMDAwMCwzMzQ1My4wMDAwMDAwMDAsNTM4Mi4xMDc3NDE5MzUsMTA3OS4xMjkwMzIyNTgsMCwwLDEsMCwxLDYwNAoyMDI1LTA3LTAxLElUVCw0MzA1ODMuMTg4MDAwMDAwLDIyNTMyLjU1MDAwMDAwMCwxMzg4OS43ODAyNTgwNjUsNzI2Ljg1NjQ1MTYxMywwLDAsMSwxLDEsNjA1CjIwMjUtMDctMDEsTEEsMTQ1ODYyLjI5MDAwMDAwMCw5ODg5NS43MzYwMDAwMDAsNDcwNS4yMzUxNjEyOTAsMzE5MC4xODUwMzIyNTgsMCwwLDEsMSwxLDYwNgoyMDI1LTA3LTAxLExJLDEzNzY3OS41MzAwMDAwMDAsNzYzOTguMTM1MDAwMDAwLDQ0NDEuMjc1MTYxMjkwLDI0NjQuNDU1OTY3NzQyLDAsMCwxLDAsMSw2MDcKMjAyNS0wNy0wMSxPWSwyNDcxNjUuNjIwMDAwMDAwLDk3NzQuNzE3MDAwMDAwLDc5NzMuMDg0NTE2MTI5LDMxNS4zMTM0NTE2MTMsMCwwLDEsMSwxLDYwOAoyMDI1LTA3LTAxLFBBLDEwMDA4Ni42MTAwMDAwMDAsMTA3MDM1LjE0MTAwMDAwMCwzMjI4LjYwMDMyMjU4MSwzNDUyLjc0NjQ4Mzg3MSwwLDAsMCwxLDEsNjA5CjIwMjUtMDctMDEsU0EsNjkzMTA1LjAwMDAwMDAwMCwyMzQ0OTguNDgzMDAwMDAwLDIyMzU4LjIyNTgwNjQ1Miw3NTY0LjQ2NzE5MzU0OCwwLDAsMSwxLDEsNjEwCjIwMjUtMDctMDEsU0gsNjE3MjA4LjI5MDAwMDAwMCwyMjExMjAuMDQxMDAwMDAwLDE5OTA5Ljk0NDgzODcxMCw3MTMyLjkwNDU0ODM4NywwLDAsMSwxLDEsNjExCjIwMjUtMDgtMDEsQUIxNiwzNDQ1ODguMjUwMDAwMDAwLDk2NzY4LjMzMDAwMDAwMCwxMTExNS43NTAwMDAwMDAsMzEyMS41NTkwMzIyNTgsMCwwLDAsMCwxLDYxMgoyMDI1LTA4LTAxLEFNLDg2Ni45ODMwMDAwMDAsNTY0NTY0LjI2MDAwMDAwMCwyNy45NjcxOTM1NDgsMTgyMTEuNzUwMzIyNTgxLDAsMCwwLDAsMSw2MTMKMjAyNS0wOC0wMSxBUCwxMjM1MDguNzc3MDAwMDAwLDEzMTgzLjQ1OTAwMDAwMCwzOTg0LjE1NDA5Njc3NCw0MjUuMjcyODcwOTY4LDAsMCwwLDAsMSw2MTQKMjAyNS0wOC0wMSxBVSwyMDg4NDY4LjMxMDAwMDAwMCwyNzcxNTYuOTc1MDAwMDAwLDY3MzY5Ljk0NTQ4Mzg3MSw4OTQwLjU0NzU4MDY0NSwwLDAsMCwwLDEsNjE1CjIwMjUtMDgtMDEsQVYsOTA3LjM0MDAwMDAwMCwwLjAwMDAwMDAwMCwyOS4yNjkwMzIyNTgsMC4wMDAwMDAwMDAsMCwwLDAsMCwxLDYxNgoyMDI1LTA4LTAxLENVLDU4Mzk3My43NTAwMDAwMDAsMTQ5NzAxLjA3MzAwMDAwMCwxODgzNy44NjI5MDMyMjYsNDgyOS4wNjY4NzA5NjgsMCwwLDAsMCwxLDYxNwoyMDI1LTA4LTAxLEVZLDkzMDA3OC4xOTgwMDAwMDAsMTc1ODY3LjA3MTAwMDAwMCwzMDAwMi41MjI1MTYxMjksNTY3My4xMzEzMjI1ODEsMCwwLDAsMCwxLDYxOAoyMDI1LTA4LTAxLElOLDQyODc2My42MDAwMDAwMDAsODA4MTkuMDAwMDAwMDAwLDEzODMxLjA4Mzg3MDk2OCwyNjA3LjA2NDUxNjEyOSwwLDAsMCwwLDEsNjE5CjIwMjUtMDgtMDEsSVRULDEzNDI3NDAuOTY1MDAwMDAwLDY2ODA5LjQ4OTAwMDAwMCw0MzMxNC4yMjQ2Nzc0MTksMjE1NS4xNDQ4MDY0NTIsMCwwLDAsMCwxLDYyMAoyMDI1LTA4LTAxLExBLDM2MzMzMi42NjAwMDAwMDAsMjIzNTE3LjE0OTAwMDAwMCwxMTcyMC40MDgzODcwOTcsNzIxMC4yMzA2MTI5MDMsMCwwLDAsMCwxLDYyMQoyMDI1LTA4LTAxLExJLDMxMjg3OC4zMDAwMDAwMDAsMTY2NjU1LjAxMzAwMDAwMCwxMDA5Mi44NDgzODcwOTcsNTM3NS45NjgxNjEyOTAsMCwwLDAsMCwxLDYyMgoyMDI1LTA4LTAxLE9ZLDYwNzYzOC4zMjAwMDAwMDAsMzI2OTQuNjUzMDAwMDAwLDE5NjAxLjIzNjEyOTAzMiwxMDU0LjY2NjIyNTgwNiwwLDAsMCwwLDEsNjIzCjIwMjUtMDgtMDEsUEEsNDEzMTkyLjI4MDAwMDAwMCwzODQ0MzMuMDgwMDAwMDAwLDEzMzI4Ljc4MzIyNTgwNiwxMjQwMS4wNjcwOTY3NzQsMCwwLDAsMCwxLDYyNAoyMDI1LTA4LTAxLFNBLDIyMzkwNzcuNjQwMDAwMDAwLDc1ODcxOS41MTYwMDAwMDAsNzIyMjguMzEwOTY3NzQyLDI0NDc0LjgyMzA5Njc3NCwwLDAsMCwwLDEsNjI1CjIwMjUtMDgtMDEsU0gsMTY3Njc4MC4xOTAwMDAwMDAsNTY3NjkxLjkyNTAwMDAwMCw1NDA4OS42ODM1NDgzODcsMTgzMTIuNjQyNzQxOTM1LDAsMCwwLDAsMSw2MjYKMjAyNS0wOS0wMSxBQjE2LDM0MDQ1My4zMzAwMDAwMDAsOTkyMTguOTYwMDAwMDAwLDExMzQ4LjQ0NDMzMzMzMywzMzA3LjI5ODY2NjY2NywwLDAsMCwwLDEsNjI3CjIwMjUtMDktMDEsQU0sODg5LjcyMDAwMDAwMCw1NjkwODIuMTIwMDAwMDAwLDI5LjY1NzMzMzMzMywxODk2OS40MDQwMDAwMDAsMCwwLDAsMCwxLDYyOAoyMDI1LTA5LTAxLEFQLDExNTI1My42NTMwMDAwMDAsMTIwMDkuMjk2MDAwMDAwLDM4NDEuNzg4NDMzMzMzLDQwMC4zMDk4NjY2NjcsMCwwLDAsMCwxLDYyOQoyMDI1LTA5LTAxLEFVLDIwNjI1MzUuODQwMDAwMDAwLDI3OTMyOS41MDEwMDAwMDAsNjg3NTEuMTk0NjY2NjY3LDkzMTAuOTgzMzY2NjY3LDAsMCwwLDAsMSw2MzAKMjAyNS0wOS0wMSxBViw0NDcuMTUwMDAwMDAwLDAuMDAwMDAwMDAwLDE0LjkwNTAwMDAwMCwwLjAwMDAwMDAwMCwwLDAsMCwwLDEsNjMxCjIwMjUtMDktMDEsQ1UsNTgxOTU4Ljc4MDAwMDAwMCwxNDQ2NDYuMzg0MDAwMDAwLDE5Mzk4LjYyNjAwMDAwMCw0ODIxLjU0NjEzMzMzMywwLDAsMCwwLDEsNjMyCjIwMjUtMDktMDEsRVksOTA1OTQxLjY2NTAwMDAwMCwxNjQ5NjguODE0MDAwMDAwLDMwMTk4LjA1NTUwMDAwMCw1NDk4Ljk2MDQ2NjY2NywwLDAsMCwwLDEsNjMzCjIwMjUtMDktMDEsSU4sNDAzMDQ1LjM5MDAwMDAwMCw2NjQ2MS4xMjUwMDAwMDAsMTM0MzQuODQ2MzMzMzMzLDIyMTUuMzcwODMzMzMzLDAsMCwwLDAsMSw2MzQKMjAyNS0wOS0wMSxJVFQsMTI5MTU4OS41MjIwMDAwMDAsNjU3MzkuNjQwMDAwMDAwLDQzMDUyLjk4NDA2NjY2NywyMTkxLjMyMTMzMzMzMywwLDAsMCwwLDEsNjM1CjIwMjUtMDktMDEsTEEsMzM1MjU5LjQ2MDAwMDAwMCwyMTM0NDUuMDMwMDAwMDAwLDExMTc1LjMxNTMzMzMzMyw3MTE0LjgzNDMzMzMzMywwLDAsMCwwLDEsNjM2CjIwMjUtMDktMDEsTEksMjk2Njc2LjA0MDAwMDAwMCwxNjU5NTIuNzQ5MDAwMDAwLDk4ODkuMjAxMzMzMzMzLDU1MzEuNzU4MzAwMDAwLDAsMCwwLDAsMSw2MzcKMjAyNS0wOS0wMSxPWSw1ODQ4MzIuNzAwMDAwMDAwLDMxMjAyLjg1NDAwMDAwMCwxOTQ5NC40MjMzMzMzMzMsMTA0MC4wOTUxMzMzMzMsMCwwLDAsMCwxLDYzOAoyMDI1LTA5LTAxLFBBLDQzMDMwMS43MzAwMDAwMDAsMzQxMjYzLjQxNTAwMDAwMCwxNDM0My4zOTEwMDAwMDAsMTEzNzUuNDQ3MTY2NjY3LDAsMCwwLDAsMSw2MzkKMjAyNS0wOS0wMSxTQSwyMjAzNzE1LjYzMDAwMDAwMCw3NDg2OTguMjU5MDAwMDAwLDczNDU3LjE4NzY2NjY2NywyNDk1Ni42MDg2MzMzMzMsMCwwLDAsMCwxLDY0MAoyMDI1LTA5LTAxLFNILDE2MzkzNzEuMTQwMDAwMDAwLDU0MjEzMS45MzYwMDAwMDAsNTQ2NDUuNzA0NjY2NjY3LDE4MDcxLjA2NDUzMzMzMywwLDAsMCwwLDEsNjQxCjIwMjUtMTAtMDEsQUIxNiwzNzc0NjYuOTkwMDAwMDAwLDEwMjY0NS43NTAwMDAwMDAsMTIxNzYuMzU0NTE2MTI5LDMzMTEuMTUzMjI1ODA2LDAsMCwwLDAsMSw2NDIKMjAyNS0xMC0wMSxBTSw5MTcuNjEwMDAwMDAwLDU2MDkxNC45MjAwMDAwMDAsMjkuNjAwMzIyNTgxLDE4MDk0LjAyOTY3NzQxOSwwLDAsMCwwLDEsNjQzCjIwMjUtMTAtMDEsQVAsMTU2NjgyLjc1NTAwMDAwMCwxNTA5MC44NTgwMDAwMDAsNTA1NC4yODI0MTkzNTUsNDg2LjgwMTg3MDk2OCwwLDAsMSwwLDEsNjQ0CjIwMjUtMTAtMDEsQVUsMjE2OTI3OS44OTAwMDAwMDAsMjg2OTE1LjY2NTAwMDAwMCw2OTk3Ni43NzA2NDUxNjEsOTI1NS4zNDQwMzIyNTgsMCwwLDAsMCwxLDY0NQoyMDI1LTEwLTAxLENVLDU5ODQ3OS4wNzAwMDAwMDAsMTQ1ODY2LjIyMjAwMDAwMCwxOTMwNS43NzY0NTE2MTMsNDcwNS4zNjIwMDAwMDAsMCwwLDAsMCwxLDY0NgoyMDI1LTEwLTAxLEVZLDk1MDQ0OS44ODgwMDAwMDAsMTcyMDIyLjUwMjAwMDAwMCwzMDY1OS42NzM4MDY0NTIsNTU0OS4xMTI5Njc3NDIsMCwwLDAsMCwxLDY0NwoyMDI1LTEwLTAxLElOLDM5NTI4MS4wMjAwMDAwMDAsNjQ1MTIuMDAwMDAwMDAwLDEyNzUxLjAwMDY0NTE2MSwyMDgxLjAzMjI1ODA2NSwwLDAsMCwwLDEsNjQ4CjIwMjUtMTAtMDEsSVRULDEzMjE3NzQuMDU3MDAwMDAwLDY3MDM0LjA1NjAwMDAwMCw0MjYzNy44NzI4MDY0NTIsMjE2Mi4zODg5MDMyMjYsMCwwLDAsMCwxLDY0OQoyMDI1LTEwLTAxLExBLDM0MTI2Ny42OTAwMDAwMDAsMjE5MjYwLjgwNDAwMDAwMCwxMTAwOC42MzUxNjEyOTAsNzA3Mi45MjkxNjEyOTAsMCwwLDAsMCwxLDY1MAoyMDI1LTEwLTAxLExJLDI5MTcwNS44NTAwMDAwMDAsMTcyMjcwLjAwNzAwMDAwMCw5NDA5Ljg2NjEyOTAzMiw1NTU3LjA5NzAwMDAwMCwwLDAsMCwwLDEsNjUxCjIwMjUtMTAtMDEsT1ksNjEzODIzLjAyMDAwMDAwMCwzMTYxNy43OTcwMDAwMDAsMTk4MDAuNzQyNTgwNjQ1LDEwMTkuOTI4OTM1NDg0LDAsMCwwLDAsMSw2NTIKMjAyNS0xMC0wMSxQQSw0MTk0MjUuNjkwMDAwMDAwLDM3NzEwNC42NDAwMDAwMDAsMTM1MjkuODYwOTY3NzQyLDEyMTY0LjY2NTgwNjQ1MiwwLDAsMCwwLDEsNjUzCjIwMjUtMTAtMDEsU0EsMjI0OTYwMy43NTAwMDAwMDAsNzcyNTQ1LjkyMjAwMDAwMCw3MjU2Ny44NjI5MDMyMjYsMjQ5MjAuODM2MTkzNTQ4LDAsMCwwLDAsMSw2NTQKMjAyNS0xMC0wMSxTSCwxNjg5NjAwLjg0MDAwMDAwMCw1NTQzMjIuMTI1MDAwMDAwLDU0NTAzLjI1MjkwMzIyNiwxNzg4MS4zNTg4NzA5NjgsMCwwLDAsMCwxLDY1NQoyMDI1LTExLTAxLEFCMTYsMzcxNDU4LjU0MDAwMDAwMCw4ODE0Ni43NTAwMDAwMDAsMTIzODEuOTUxMzMzMzMzLDI5MzguMjI1MDAwMDAwLDAsMCwwLDAsMSw2NTYKMjAyNS0xMS0wMSxBTSw4NTkuMDQwMDAwMDAwLDUyMjI0OC45NTAwMDAwMDAsMjguNjM0NjY2NjY3LDE3NDA4LjI5ODMzMzMzMywwLDAsMCwwLDEsNjU3CjIwMjUtMTEtMDEsQVAsMTU0MTc0Ljk3NDAwMDAwMCwxNTEzNC4yMTIwMDAwMDAsNTEzOS4xNjU4MDAwMDAsNTA0LjQ3MzczMzMzMywwLDAsMSwwLDEsNjU4CjIwMjUtMTEtMDEsQVUsMTkwOTc1MC41ODAwMDAwMDAsMjYxODE3Ljc0NDAwMDAwMCw2MzY1OC4zNTI2NjY2NjcsODcyNy4yNTgxMzMzMzMsMCwwLDAsMCwxLDY1OQoyMDI1LTExLTAxLENVLDU3Njg4OC4yOTAwMDAwMDAsMTM5NTAwLjkzOTAwMDAwMCwxOTIyOS42MDk2NjY2NjcsNDY1MC4wMzEzMDAwMDAsMCwwLDAsMCwxLDY2MAoyMDI1LTExLTAxLEVZLDkzMzQwNS4xMjIwMDAwMDAsMTY3NzQwLjI0ODAwMDAwMCwzMTExMy41MDQwNjY2NjcsNTU5MS4zNDE2MDAwMDAsMCwwLDAsMCwxLDY2MQoyMDI1LTExLTAxLElOLDM5MTU2MS43NzAwMDAwMDAsNjQ0MjkuMTY3MDAwMDAwLDEzMDUyLjA1OTAwMDAwMCwyMTQ3LjYzODkwMDAwMCwwLDAsMCwwLDEsNjYyCjIwMjUtMTEtMDEsSVRULDEzMzM0MTEuMzc0MDAwMDAwLDY0OTQ0LjUzMzAwMDAwMCw0NDQ0Ny4wNDU4MDAwMDAsMjE2NC44MTc3NjY2NjcsMCwwLDAsMCwxLDY2MwoyMDI1LTExLTAxLExBLDM0MDUwMC41NDAwMDAwMDAsMjE1OTA5Ljk0NDAwMDAwMCwxMTM1MC4wMTgwMDAwMDAsNzE5Ni45OTgxMzMzMzMsMCwwLDAsMCwxLDY2NAoyMDI1LTExLTAxLExJLDI3ODU3MS4xMjAwMDAwMDAsMTYwNTg4LjQwMTAwMDAwMCw5Mjg1LjcwNDAwMDAwMCw1MzUyLjk0NjcwMDAwMCwwLDAsMCwwLDEsNjY1CjIwMjUtMTEtMDEsT1ksNjAyMDQ0Ljc5MDAwMDAwMCwzMDk3Mi40MzgwMDAwMDAsMjAwNjguMTU5NjY2NjY3LDEwMzIuNDE0NjAwMDAwLDAsMCwwLDAsMSw2NjYKMjAyNS0xMS0wMSxQQSwzODIzODYuNjUwMDAwMDAwLDM1MDk2Ni45MTIwMDAwMDAsMTI3NDYuMjIxNjY2NjY3LDExNjk4Ljg5NzA2NjY2NywwLDAsMCwwLDEsNjY3CjIwMjUtMTEtMDEsU0EsMjE0NzExMC43NzAwMDAwMDAsNzQyNDQ1LjEwODAwMDAwMCw3MTU3MC4zNTkwMDAwMDAsMjQ3NDguMTcwMjY2NjY3LDAsMCwwLDAsMSw2NjgKMjAyNS0xMS0wMSxTSCwxNjg1NDMxLjYyMDAwMDAwMCw1NTkzNDMuNjAzMDAwMDAwLDU2MTgxLjA1NDAwMDAwMCwxODY0NC43ODY3NjY2NjcsMCwwLDAsMCwxLDY2OQoyMDI1LTEyLTAxLEFCMTYsMzYyOTgwLjIyMDAwMDAwMCw5NDgwOS4yMjAwMDAwMDAsMTE3MDkuMDM5MzU0ODM5LDMwNTguMzYxOTM1NDg0LDAsMCwwLDAsMSw2NzAKMjAyNS0xMi0wMSxBTSw4NzAuNjQwMDAwMDAwLDU2OTQ3NS4xNzAwMDAwMDAsMjguMDg1MTYxMjkwLDE4MzcwLjE2Njc3NDE5NCwwLDAsMCwwLDEsNjcxCjIwMjUtMTItMDEsQVAsMTY2MzM0LjA0NTAwMDAwMCwxODg2Ni4wNzIwMDAwMDAsNTM2NS42MTQzNTQ4MzksNjA4LjU4Mjk2Nzc0MiwwLDAsMSwxLDEsNjcyCjIwMjUtMTItMDEsQVUsMTkyNDUyNy41MzAwMDAwMDAsMjYwMjIwLjM3NzAwMDAwMCw2MjA4MS41MzMyMjU4MDYsODM5NC4yMDU3MDk2NzcsMCwwLDAsMCwxLDY3MwoyMDI1LTEyLTAxLENVLDU4MDU0OS44NTAwMDAwMDAsMTQxMDYyLjgzODAwMDAwMCwxODcyNy40MTQ1MTYxMjksNDU1MC40MTQxMjkwMzIsMCwwLDAsMCwxLDY3NAoyMDI1LTEyLTAxLEVZLDk2MTIxOS40ODAwMDAwMDAsMTc1NzkyLjMwODAwMDAwMCwzMTAwNy4wODAwMDAwMDAsNTY3MC43MTk2MTI5MDMsMCwwLDAsMCwxLDY3NQoyMDI1LTEyLTAxLElOLDQwNzIzMS43ODAwMDAwMDAsNjU0NzIuMDAwMDAwMDAwLDEzMTM2LjUwOTAzMjI1OCwyMTEyLjAwMDAwMDAwMCwwLDAsMCwwLDEsNjc2CjIwMjUtMTItMDEsSVRULDEzNzA3OTcuNTM1MDAwMDAwLDY0ODIyLjQwODAwMDAwMCw0NDIxOS4yNzUzMjI1ODEsMjA5MS4wNDU0MTkzNTUsMCwwLDAsMCwxLDY3NwoyMDI1LTEyLTAxLExBLDM1NDI4NS4zNzAwMDAwMDAsMjE4NDgyLjMyNDAwMDAwMCwxMTQyOC41NjAzMjI1ODEsNzA0Ny44MTY5MDMyMjYsMCwwLDAsMCwxLDY3OAoyMDI1LTEyLTAxLExJLDMxMTUxOC41NTAwMDAwMDAsMTY4Mjk2LjI2ODAwMDAwMCwxMDA0OC45ODU0ODM4NzEsNTQyOC45MTE4NzA5NjgsMCwwLDAsMCwxLDY3OQoyMDI1LTEyLTAxLE9ZLDYyMzEzNC4yOTAwMDAwMDAsMzIyMDUuMjY0MDAwMDAwLDIwMTAxLjEwNjEyOTAzMiwxMDM4Ljg3OTQ4Mzg3MSwwLDAsMCwwLDEsNjgwCjIwMjUtMTItMDEsUEEsNDA0MTc1LjMyMDAwMDAwMCwzOTM2ODcuNzM0MDAwMDAwLDEzMDM3LjkxMzU0ODM4NywxMjY5OS42MDQzMjI1ODEsMCwwLDAsMCwxLDY4MQoyMDI1LTEyLTAxLFNBLDIyMzI4MzkuNzAwMDAwMDAwLDcyNjY5Mi43NzUwMDAwMDAsNzIwMjcuMDg3MDk2Nzc0LDIzNDQxLjcwMjQxOTM1NSwwLDAsMCwwLDEsNjgyCjIwMjUtMTItMDEsU0gsMTcwMDY4NC40MzAwMDAwMDAsNTgzMjIyLjk0MzAwMDAwMCw1NDg2MC43ODgwNjQ1MTYsMTg4MTMuNjQzMzIyNTgxLDAsMCwwLDAsMSw2ODMKMjAyNi0wMS0wMSxBSVQsMzU3OTQzLjI1MDAwMDAwMCwxMDU4NDIuODIwMDAwMDAwLDExNTQ2LjU1NjQ1MTYxMywzNDE0LjI4NDUxNjEyOSwwLDAsMCwwLDEsNjg0CjIwMjYtMDEtMDEsQU0sODgzLjk1MDAwMDAwMCw1NDM2MzAuNTkwMDAwMDAwLDI4LjUxNDUxNjEyOSwxNzUzNi40NzA2NDUxNjEsMCwwLDAsMCwxLDY4NQoyMDI2LTAxLTAxLEFQLDE3OTIyOC40OTUwMDAwMDAsMTk2NTguMDU4MDAwMDAwLDU3ODEuNTY0MzU0ODM5LDYzNC4xMzA5MDMyMjYsMCwwLDEsMSwxLDY4NgoyMDI2LTAxLTAxLEFVLDE5MTYxMjYuNzQwMDAwMDAwLDI1NjgyMS4wMDIwMDAwMDAsNjE4MTAuNTQwMDAwMDAwLDgyODQuNTQ4NDUxNjEzLDAsMCwwLDAsMSw2ODcKMjAyNi0wMS0wMSxBViwzMDMuOTAwMDAwMDAwLDAuMDAwMDAwMDAwLDkuODAzMjI1ODA2LDAuMDAwMDAwMDAwLDAsMCwxLDAsMSw2ODgKMjAyNi0wMS0wMSxDVSw1NzI2NjIuNzcwMDAwMDAwLDE0MjYxMC4yNjgwMDAwMDAsMTg0NzIuOTkyNTgwNjQ1LDQ2MDAuMzMxMjI1ODA2LDAsMCwwLDAsMSw2ODkKMjAyNi0wMS0wMSxFWSw5NTk3MTkuNjA3MDAwMDAwLDE1OTcyOS4wOTIwMDAwMDAsMzA5NTguNjk3MDAwMDAwLDUxNTIuNTUxMzU0ODM5LDAsMCwwLDAsMSw2OTAKMjAyNi0wMS0wMSxJTiw0MDEyNzEuNDYwMDAwMDAwLDY3MjM2LjAwMDAwMDAwMCwxMjk0NC4yNDA2NDUxNjEsMjE2OC45MDMyMjU4MDYsMCwwLDAsMCwxLDY5MQoyMDI2LTAxLTAxLElUVCwxMzc5MDg3LjMzODAwMDAwMCw2MzA0My4xMDUwMDAwMDAsNDQ0ODYuNjg4MzIyNTgxLDIwMzMuNjQ4NTQ4Mzg3LDAsMCwwLDAsMSw2OTIKMjAyNi0wMS0wMSxMQSwzMzIwNDMuNjMwMDAwMDAwLDIxMjI3MS43NjgwMDAwMDAsMTA3MTEuMDg0ODM4NzEwLDY4NDcuNDc2Mzg3MDk3LDAsMCwwLDAsMSw2OTMKMjAyNi0wMS0wMSxMSSwzNDE4OTMuODMwMDAwMDAwLDE3OTMwNy45MDYwMDAwMDAsMTEwMjguODMzMjI1ODA2LDU3ODQuMTI2MDAwMDAwLDAsMCwwLDAsMSw2OTQKMjAyNi0wMS0wMSxPWSw2MzYyMDcuNjQwMDAwMDAwLDMwNTIyLjQ2MDAwMDAwMCwyMDUyMi44MjcwOTY3NzQsOTg0LjU5NTQ4Mzg3MSwwLDAsMCwwLDEsNjk1CjIwMjYtMDEtMDEsUEEsNDA3NDU5LjY1MDAwMDAwMCw0MDcwOTMuNzM1MDAwMDAwLDEzMTQzLjg1OTY3NzQxOSwxMzEzMi4wNTU5Njc3NDIsMCwwLDAsMCwxLDY5NgoyMDI2LTAxLTAxLFNBLDIxODk3NjEuMDMwMDAwMDAwLDcxNjEwOS44NDQwMDAwMDAsNzA2MzcuNDUyNTgwNjQ1LDIzMTAwLjMxNzU0ODM4NywwLDAsMCwwLDEsNjk3CjIwMjYtMDEtMDEsU0gsMTc2MTczOC42NDAwMDAwMDAsNjA0MzYzLjQ0MzAwMDAwMCw1NjgzMC4yNzg3MDk2NzcsMTk0OTUuNTk0OTM1NDg0LDAsMCwwLDAsMSw2OTgKMjAyNi0wMi0wMSxBSVQsMzE2Mzc3LjIxMDAwMDAwMCw5MjI2Ni45NzAwMDAwMDAsMTEyOTkuMTg2MDcxNDI5LDMyOTUuMjQ4OTI4NTcxLDAsMCwwLDAsMSw2OTkKMjAyNi0wMi0wMSxBTSw4MzcuNTYwMDAwMDAwLDQ4OTk2MS4wNTAwMDAwMDAsMjkuOTEyODU3MTQzLDE3NDk4LjYwODkyODU3MSwwLDAsMCwwLDEsNzAwCjIwMjYtMDItMDEsQVAsMTcyMzgyLjE5MDAwMDAwMCwxODQxNi41MzIwMDAwMDAsNjE1Ni41MDY3ODU3MTQsNjU3LjczMzI4NTcxNCwwLDAsMSwxLDEsNzAxCjIwMjYtMDItMDEsQVUsMTcyODk3MS43NDAwMDAwMDAsMjMwNjg1Ljc4NTAwMDAwMCw2MTc0OC45OTA3MTQyODYsODIzOC43NzgwMzU3MTQsMCwwLDAsMCwxLDcwMgoyMDI2LTAyLTAxLEFWLDY0Ny41NjAwMDAwMDAsMC4wMDAwMDAwMDAsMjMuMTI3MTQyODU3LDAuMDAwMDAwMDAwLDAsMCwwLDAsMSw3MDMKMjAyNi0wMi0wMSxDVSw1MTE3NjkuODgwMDAwMDAwLDEyODYzOS4zMDIwMDAwMDAsMTgyNzcuNDk1NzE0Mjg2LDQ1OTQuMjYwNzg1NzE0LDAsMCwwLDAsMSw3MDQKMjAyNi0wMi0wMSxFWSw4ODI1NDUuNjY4MDAwMDAwLDE1NTUwMi4wOTgwMDAwMDAsMzE1MTkuNDg4MTQyODU3LDU1NTMuNjQ2MzU3MTQzLDAsMCwwLDAsMSw3MDUKMjAyNi0wMi0wMSxJTiwzMzU4NDYuNTEwMDAwMDAwLDU4MTY0LjgzNDAwMDAwMCwxMTk5NC41MTgyMTQyODYsMjA3Ny4zMTU1MDAwMDAsMCwwLDAsMCwxLDcwNgoyMDI2LTAyLTAxLElUVCwxMjAwOTkyLjc3MjAwMDAwMCw1NTc5Mi42MjgwMDAwMDAsNDI4OTIuNTk5MDAwMDAwLDE5OTIuNTkzODU3MTQzLDAsMCwwLDAsMSw3MDcKMjAyNi0wMi0wMSxMQSwyOTcxNDYuNjgwMDAwMDAwLDE5MTg2MC45NTYwMDAwMDAsMTA2MTIuMzgxNDI4NTcxLDY4NTIuMTc3MDAwMDAwLDAsMCwwLDAsMSw3MDgKMjAyNi0wMi0wMSxMSSwzMDk0NDEuNzcwMDAwMDAwLDE1OTEwNy43MjUwMDAwMDAsMTEwNTEuNDkxNzg1NzE0LDU2ODIuNDE4NzUwMDAwLDAsMCwwLDAsMSw3MDkKMjAyNi0wMi0wMSxPWSw1NDQ2NDQuMTkwMDAwMDAwLDI2MTk5LjYyNjAwMDAwMCwxOTQ1MS41NzgyMTQyODYsOTM1LjcwMDkyODU3MSwwLDAsMCwwLDEsNzEwCjIwMjYtMDItMDEsUEEsMzU2NzA2LjQ0MDAwMDAwMCwzMzgyMDQuMjE4MDAwMDAwLDEyNzM5LjUxNTcxNDI4NiwxMjA3OC43MjIwNzE0MjksMCwwLDAsMCwxLDcxMQoyMDI2LTAyLTAxLFNBLDE5NjMyNzcuMjgwMDAwMDAwLDYyNTU2NS41NDEwMDAwMDAsNzAxMTcuMDQ1NzE0Mjg2LDIyMzQxLjYyNjQ2NDI4NiwwLDAsMCwwLDEsNzEyCjIwMjYtMDItMDEsU0gsMTU4OTE2MS43NTAwMDAwMDAsNTM5MDc5Ljg2NzAwMDAwMCw1Njc1NS43NzY3ODU3MTQsMTkyNTIuODUyMzkyODU3LDAsMCwwLDAsMSw3MTMKMjAyNi0wMy0wMSxBSVQsMzQ2OTQ3LjcyMDAwMDAwMCwxMDA3NTkuODEwMDAwMDAwLDExMTkxLjg2MTkzNTQ4NCwzMjUwLjMxNjQ1MTYxMywwLDAsMCwwLDEsNzE0CjIwMjYtMDMtMDEsQU0sOTMzLjY3MDAwMDAwMCw1OTQ4MDcuMzMxMDAwMDAwLDMwLjExODM4NzA5NywxOTE4Ny4zMzMyNTgwNjUsMCwwLDAsMCwxLDcxNQoyMDI2LTAzLTAxLEFQLDIxMjE0MC4xOTEwMDAwMDAsMjEzMDUuMjU2MDAwMDAwLDY4NDMuMjMxOTY3NzQyLDY4Ny4yNjYzMjI1ODEsMCwwLDEsMSwxLDcxNgoyMDI2LTAzLTAxLEFVLDE5MDE2NTQuNTUwMDAwMDAwLDI0ODU2MC40NjQwMDAwMDAsNjEzNDMuNjk1MTYxMjkwLDgwMTguMDc5NDgzODcxLDAsMCwwLDAsMSw3MTcKMjAyNi0wMy0wMSxBViw4MDcuNjYwMDAwMDAwLDAuMDAwMDAwMDAwLDI2LjA1MzU0ODM4NywwLjAwMDAwMDAwMCwwLDAsMCwwLDEsNzE4CjIwMjYtMDMtMDEsQ1UsNTU2NTkwLjYwMDAwMDAwMCwxNDE2NjQuMzcyMDAwMDAwLDE3OTU0LjUzNTQ4Mzg3MSw0NTY5LjgxODQ1MTYxMywwLDAsMCwwLDEsNzE5CjIwMjYtMDMtMDEsRVksOTM2MTkxLjIyMjAwMDAwMCwxNjYwMzIuNTg0MDAwMDAwLDMwMTk5LjcxNjgzODcxMCw1MzU1Ljg4OTgwNjQ1MiwwLDAsMCwwLDEsNzIwCjIwMjYtMDMtMDEsSU4sMzgwNjQ2LjAzMDAwMDAwMCw2NTkyMC44NzUwMDAwMDAsMTIyNzguOTA0MTkzNTQ4LDIxMjYuNDc5ODM4NzEwLDAsMCwwLDAsMSw3MjEKMjAyNi0wMy0wMSxJVFQsMTMxODAzMS4wMzcwMDAwMDAsNjIxNTQuOTMzMDAwMDAwLDQyNTE3LjEzMDIyNTgwNiwyMDA0Ljk5NzgzODcxMCwwLDAsMCwwLDEsNzIyCjIwMjYtMDMtMDEsTEEsMzIxMDQ4Ljc1MDAwMDAwMCwyMTQxOTQuMTA4MDAwMDAwLDEwMzU2LjQxMTI5MDMyMyw2OTA5LjQ4NzM1NDgzOSwwLDAsMCwwLDEsNzIzCjIwMjYtMDMtMDEsTEksMzMxODQzLjc1MDAwMDAwMCwxODA4OTEuMzMxMDAwMDAwLDEwNzA0LjYzNzA5Njc3NCw1ODM1LjIwNDIyNTgwNiwwLDAsMCwwLDEsNzI0CjIwMjYtMDMtMDEsT1ksNjQ4MTcwLjg0MDAwMDAwMCwzMjA0Ny41MjEwMDAwMDAsMjA5MDguNzM2Nzc0MTk0LDEwMzMuNzkxMDAwMDAwLDAsMCwwLDAsMSw3MjUKMjAyNi0wMy0wMSxQQSwzODY2NjguNjUwMDAwMDAwLDM3NjAxNS42NjkwMDAwMDAsMTI0NzMuMTgyMjU4MDY1LDEyMTI5LjUzNzcwOTY3NywwLDAsMCwwLDEsNzI2CjIwMjYtMDMtMDEsU0EsMjE3NTU5OS4xMDAwMDAwMDAsNjk1NTM4LjY1MjAwMDAwMCw3MDE4MC42MTYxMjkwMzIsMjI0MzYuNzMwNzA5Njc3LDAsMCwwLDAsMSw3MjcKMjAyNi0wMy0wMSxTSCwxNjkzMzY3LjI4MDAwMDAwMCw1ODM1MDAuNjcxMDAwMDAwLDU0NjI0Ljc1MDk2Nzc0MiwxODgyMi42MDIyOTAzMjMsMCwwLDAsMCwxLDcyOAoyMDI2LTA0LTAxLEFJVCwzMjc0MzUuMDYwMDAwMDAwLDk2MzEzLjUzMDAwMDAwMCwxMDkxNC41MDIwMDAwMDAsMzIxMC40NTEwMDAwMDAsMCwwLDAsMCwxLDcyOQoyMDI2LTA0LTAxLEFNLDgxNy41MjAwMDAwMDAsNzM0MDk0LjIwMDAwMDAwMCwyNy4yNTA2NjY2NjcsMjQ0NjkuODA2NjY2NjY3LDAsMCwwLDAsMSw3MzAKMjAyNi0wNC0wMSxBUCwyMTI5NzAuMzk1MDAwMDAwLDE4NDQ2LjM0NzAwMDAwMCw3MDk5LjAxMzE2NjY2Nyw2MTQuODc4MjMzMzMzLDAsMCwxLDEsMSw3MzEKMjAyNi0wNC0wMSxBVSwxNzc0MjY4LjE1MDAwMDAwMCwyMzg2MjEuNzU0MDAwMDAwLDU5MTQyLjI3MTY2NjY2Nyw3OTU0LjA1ODQ2NjY2NywwLDAsMCwwLDEsNzMyCjIwMjYtMDQtMDEsQVYsNjk4LjIyMDAwMDAwMCwwLjAwMDAwMDAwMCwyMy4yNzQwMDAwMDAsMC4wMDAwMDAwMDAsMCwwLDAsMCwxLDczMwoyMDI2LTA0LTAxLENVLDUyNDYyMC45ODAwMDAwMDAsMTMzNzA1LjgzNDAwMDAwMCwxNzQ4Ny4zNjYwMDAwMDAsNDQ1Ni44NjExMzMzMzMsMCwwLDAsMCwxLDczNAoyMDI2LTA0LTAxLEVZLDg4NTM5Ny43NzkwMDAwMDAsMTQ4NjIxLjExMzAwMDAwMCwyOTUxMy4yNTkzMDAwMDAsNDk1NC4wMzcxMDAwMDAsMCwwLDAsMCwxLDczNQoyMDI2LTA0LTAxLElOLDM1MzA3My41MDAwMDAwMDAsNjIxNDEuMDAwMDAwMDAwLDExNzY5LjExNjY2NjY2NywyMDcxLjM2NjY2NjY2NywwLDAsMCwwLDEsNzM2CjIwMjYtMDQtMDEsSVRULDEyMzQwOTAuOTk2MDAwMDAwLDU4MzM3Ljk2NTAwMDAwMCw0MTEzNi4zNjY1MzMzMzMsMTk0NC41OTg4MzMzMzMsMCwwLDAsMCwxLDczNwoyMDI2LTA0LTAxLExBLDMyNDg5My44NTAwMDAwMDAsMTk5NjcxLjQzMzAwMDAwMCwxMDgyOS43OTUwMDAwMDAsNjY1NS43MTQ0MzMzMzMsMCwwLDAsMCwxLDczOAoyMDI2LTA0LTAxLExJLDMwMDM0My41MzAwMDAwMDAsMTY2ODQ3LjE0NDAwMDAwMCwxMDAxMS40NTEwMDAwMDAsNTU2MS41NzE0NjY2NjcsMCwwLDAsMCwxLDczOQoyMDI2LTA0LTAxLE9ZLDYyNTMzMy41NzAwMDAwMDAsMzExNDAuNDI4MDAwMDAwLDIwODQ0LjQ1MjMzMzMzMywxMDM4LjAxNDI2NjY2NywwLDAsMCwwLDEsNzQwCjIwMjYtMDQtMDEsUEEsMzgwODc3LjUyMDAwMDAwMCwzNzAyNDUuMTgxMDAwMDAwLDEyNjk1LjkxNzMzMzMzMywxMjM0MS41MDYwMzMzMzMsMCwwLDAsMCwxLDc0MQoyMDI2LTA0LTAxLFNBLDIxMjE5MTkuMDMwMDAwMDAwLDY3NTU0Ny4yNDUwMDAwMDAsNzA3MzAuNjM0MzMzMzMzLDIyNTE4LjI0MTUwMDAwMCwwLDAsMCwwLDEsNzQyCjIwMjYtMDQtMDEsU0gsMTYzOTI4NC42ODAwMDAwMDAsNTY5NzQyLjM2NTAwMDAwMCw1NDY0Mi44MjI2NjY2NjcsMTg5OTEuNDEyMTY2NjY3LDAsMCwwLDAsMSw3NDMKMjAyNi0wNS0wMSxBSVQsMzQwMzA5LjU0MDAwMDAwMCwxMDE2ODkuNTkwMDAwMDAwLDEwOTc3LjcyNzA5Njc3NCwzMjgwLjMwOTM1NDgzOSwwLDAsMCwwLDEsNzQ0CjIwMjYtMDUtMDEsQU0sODEwLjEwMDAwMDAwMCw4NDIzMTUuMDQwMDAwMDAwLDI2LjEzMjI1ODA2NSwyNzE3MS40NTI5MDMyMjYsMCwwLDAsMSwxLDc0NQoyMDI2LTA1LTAxLEFQLDIzMzI4OS4yNzMwMDAwMDAsMTc1MzkuNTMzMDAwMDAwLDc1MjUuNDYwNDE5MzU1LDU2NS43OTEzODcwOTcsMCwwLDEsMCwxLDc0NgoyMDI2LTA1LTAxLEFVLDE4NjM1MDUuMDEwMDAwMDAwLDI1MDQ1Ni4xMzcwMDAwMDAsNjAxMTMuMDY0ODM4NzEwLDgwNzkuMjMwMjI1ODA2LDAsMCwwLDAsMSw3NDcKMjAyNi0wNS0wMSxBViw3OTcuODgwMDAwMDAwLDAuMDAwMDAwMDAwLDI1LjczODA2NDUxNiwwLjAwMDAwMDAwMCwwLDAsMCwwLDEsNzQ4CjIwMjYtMDUtMDEsQ1UsNTQxMzE2LjEyMDAwMDAwMCwxMzYxMDEuMjU2MDAwMDAwLDE3NDYxLjgxMDMyMjU4MSw0MzkwLjM2MzA5Njc3NCwwLDAsMCwwLDEsNzQ5CjIwMjYtMDUtMDEsRVksOTA1OTM3LjgwNzAwMDAwMCwxNDYyNDguMDk3MDAwMDAwLDI5MjIzLjgwMDIyNTgwNiw0NzE3LjY4MDU0ODM4NywwLDAsMCwwLDEsNzUwCjIwMjYtMDUtMDEsSU4sMzkzMDM4LjQyMDAwMDAwMCw2NDQ5MC4wMDAwMDAwMDAsMTI2NzguNjU4NzA5Njc3LDIwODAuMzIyNTgwNjQ1LDAsMCwwLDAsMSw3NTEKMjAyNi0wNS0wMSxJVFQsMTI3MTQ5Mi4wNzAwMDAwMDAsNjA4NjMuMTU5MDAwMDAwLDQxMDE1Ljg3MzIyNTgwNiwxOTYzLjMyNzcwOTY3NywwLDAsMCwwLDEsNzUyCjIwMjYtMDUtMDEsTEEsMzgyNTQ2Ljg2MDAwMDAwMCwyMTg4NDMuMDc5MDAwMDAwLDEyMzQwLjIyMTI5MDMyMyw3MDU5LjQ1NDE2MTI5MCwwLDAsMCwwLDEsNzUzCjIwMjYtMDUtMDEsTEksMzA3MTk0Ljk2MDAwMDAwMCwxNjAxODYuMjMwMDAwMDAwLDk5MDkuNTE0ODM4NzEwLDUxNjcuMjk3NzQxOTM1LDAsMCwwLDAsMSw3NTQKMjAyNi0wNS0wMSxPWSw2NDU4ODEuNjMwMDAwMDAwLDM1NjUwLjczNzAwMDAwMCwyMDgzNC44OTEyOTAzMjMsMTE1MC4wMjM3NzQxOTQsMCwwLDAsMCwxLDc1NQoyMDI2LTA1LTAxLFBBLDM5OTkzMy4xOTAwMDAwMDAsMzgyODQ1LjU1MjAwMDAwMCwxMjkwMS4wNzA2NDUxNjEsMTIzNDkuODU2NTE2MTI5LDAsMCwwLDAsMSw3NTYKMjAyNi0wNS0wMSxTQSwyMjM2OTY4LjMyMDAwMDAwMCw3MDg3NjMuMTI4MDAwMDAwLDcyMTYwLjI2ODM4NzA5NywyMjg2My4zMjY3MDk2NzcsMCwwLDAsMCwxLDc1NwoyMDI2LTA1LTAxLFNILDE2OTAyNjMuMjYwMDAwMDAwLDU4Njg1My40OTYwMDAwMDAsNTQ1MjQuNjIxMjkwMzIzLDE4OTMwLjc1NzkzNTQ4NCwwLDAsMCwwLDEsNzU4CjIwMjYtMDYtMDEsQUlULDMzNjI1Mi4xMjAwMDAwMDAsMTA1MjM3LjgxMDAwMDAwMCwxMTIwOC40MDQwMDAwMDAsMzUwNy45MjcwMDAwMDAsMCwwLDAsMSwxLDc1OQoyMDI2LTA2LTAxLEFNLDc4My4wNjAwMDAwMDAsODAxNzEwLjYyMDAwMDAwMCwyNi4xMDIwMDAwMDAsMjY3MjMuNjg3MzMzMzMzLDAsMCwwLDEsMSw3NjAKMjAyNi0wNi0wMSxBUCwyMTEwMjguMzI2MDAwMDAwLDE1NjczLjI5MzAwMDAwMCw3MDM0LjI3NzUzMzMzMyw1MjIuNDQzMTAwMDAwLDAsMCwxLDAsMSw3NjEKMjAyNi0wNi0wMSxBVSwxODM5ODcwLjAxMDAwMDAwMCwyNDEwNDYuMDI0MDAwMDAwLDYxMzI5LjAwMDMzMzMzMyw4MDM0Ljg2NzQ2NjY2NywwLDAsMCwwLDEsNzYyCjIwMjYtMDYtMDEsQVYsOTQuNDQwMDAwMDAwLDAuMDAwMDAwMDAwLDMuMTQ4MDAwMDAwLDAuMDAwMDAwMDAwLDAsMCwxLDAsMSw3NjMKMjAyNi0wNi0wMSxDVSw1MTUwMjEuMDMwMDAwMDAwLDEzMTUwOS4yODkwMDAwMDAsMTcxNjcuMzY3NjY2NjY3LDQzODMuNjQyOTY2NjY3LDAsMCwwLDAsMSw3NjQKMjAyNi0wNi0wMSxFWSw4NDc3MDEuNzg5MDAwMDAwLDEzNzAxNi41MTcwMDAwMDAsMjgyNTYuNzI2MzAwMDAwLDQ1NjcuMjE3MjMzMzMzLDAsMCwwLDAsMSw3NjUKMjAyNi0wNi0wMSxJTiwzODY2NDUuNzkwMDAwMDAwLDYyMDA2LjAwMDAwMDAwMCwxMjg4OC4xOTMwMDAwMDAsMjA2Ni44NjY2NjY2NjcsMCwwLDAsMCwxLDc2NgoyMDI2LTA2LTAxLElUVCwxMjE3MzA0Ljg4NTAwMDAwMCw1OTU1Ny44ODQwMDAwMDAsNDA1NzYuODI5NTAwMDAwLDE5ODUuMjYyODAwMDAwLDAsMCwwLDAsMSw3NjcKMjAyNi0wNi0wMSxMQSwzOTAxMjYuNzIwMDAwMDAwLDIwODQyMy4yMTgwMDAwMDAsMTMwMDQuMjI0MDAwMDAwLDY5NDcuNDQwNjAwMDAwLDAsMCwwLDAsMSw3NjgKMjAyNi0wNi0wMSxMSSwyOTkyOTYuNTgwMDAwMDAwLDE1MTI1OC4zNTYwMDAwMDAsOTk3Ni41NTI2NjY2NjcsNTA0MS45NDUyMDAwMDAsMCwwLDAsMCwxLDc2OQoyMDI2LTA2LTAxLE9ZLDYzMTI1NS4zNzAwMDAwMDAsMzU0MTcuNTA0MDAwMDAwLDIxMDQxLjg0NTY2NjY2NywxMTgwLjU4MzQ2NjY2NywwLDAsMCwxLDEsNzcwCjIwMjYtMDYtMDEsUEEsMzg3MzIzLjIzMDAwMDAwMCwzNzY2OTcuNDQ3MDAwMDAwLDEyOTEwLjc3NDMzMzMzMywxMjU1Ni41ODE1NjY2NjcsMCwwLDAsMCwxLDc3MQoyMDI2LTA2LTAxLFNBLDIxODk0NTMuNzEwMDAwMDAwLDY4ODM5MC4xNjIwMDAwMDAsNzI5ODEuNzkwMzMzMzMzLDIyOTQ2LjMzODczMzMzMywwLDAsMCwwLDEsNzcyCjIwMjYtMDYtMDEsU0gsMTYzNTI1NS42MjAwMDAwMDAsNTUzNTE5LjgwOTAwMDAwMCw1NDUwOC41MjA2NjY2NjcsMTg0NTAuNjYwMzAwMDAwLDAsMCwwLDAsMSw3NzMKMjAyNi0wNy0wMSxBSVQsMzQyODM0Ljk5MDAwMDAwMCwxMDE4NjcuNjIwMDAwMDAwLDExMDU5LjE5MzIyNTgwNiwzMjg2LjA1MjI1ODA2NSwwLDAsMCwwLDEsNzc0CjIwMjYtMDctMDEsQU0sODE2LjIxMDAwMDAwMCw3OTI5NTYuMjAwMDAwMDAwLDI2LjMyOTM1NDgzOSwyNTU3OS4yMzIyNTgwNjUsMCwwLDAsMCwxLDc3NQoyMDI2LTA3LTAxLEFQLDIwMDYxMy4wNjUwMDAwMDAsMTU3MzEuMzg1MDAwMDAwLDY0NzEuMzg5MTkzNTQ4LDUwNy40NjQwMzIyNTgsMCwwLDEsMCwxLDc3NgoyMDI2LTA3LTAxLEFVLDE5NjUyMzIuNjMwMDAwMDAwLDI1NTQ5NS43MjcwMDAwMDAsNjMzOTQuNjAwOTY3NzQyLDgyNDEuNzk3NjQ1MTYxLDAsMCwwLDAsMSw3NzcKMjAyNi0wNy0wMSxBViwxMTI2LjU3MDAwMDAwMCwwLjAwMDAwMDAwMCwzNi4zNDA5Njc3NDIsMC4wMDAwMDAwMDAsMCwwLDAsMCwxLDc3OAoyMDI2LTA3LTAxLENVLDU0MjUwNy4xNDAwMDAwMDAsMTM4MTY3LjMzMzAwMDAwMCwxNzUwMC4yMzAzMjI1ODEsNDQ1Ny4wMTA3NDE5MzUsMCwwLDAsMCwxLDc3OQoyMDI2LTA3LTAxLEVZLDg2MDIxNC44NjMwMDAwMDAsMTQ2Mjg3LjE5NTAwMDAwMCwyNzc0OC44NjY1NDgzODcsNDcxOC45NDE3NzQxOTQsMCwwLDAsMCwxLDc4MAoyMDI2LTA3LTAxLElOLDM5NjkzMC4zMDAwMDAwMDAsNjM5ODYuNjY3MDAwMDAwLDEyODA0LjIwMzIyNTgwNiwyMDY0LjA4NjAzMjI1OCwwLDAsMCwwLDEsNzgxCjIwMjYtMDctMDEsSVRULDEyMzA3MDIuNDcyMDAwMDAwLDYwNzQ5Ljg2NzAwMDAwMCwzOTcwMC4wNzk3NDE5MzUsMTk1OS42NzMxMjkwMzIsMCwwLDAsMCwxLDc4MgoyMDI2LTA3LTAxLExBLDQ1OTg3MC44NjAwMDAwMDAsMjA5NTU1LjgzNzAwMDAwMCwxNDgzNC41NDM4NzA5NjgsNjc1OS44NjU3MDk2NzcsMCwwLDEsMCwxLDc4MwoyMDI2LTA3LTAxLExJLDMxOTM2NS4xNTAwMDAwMDAsMTU4ODg2Ljk2ODAwMDAwMCwxMDMwMi4xMDE2MTI5MDMsNTEyNS4zODYwNjQ1MTYsMCwwLDAsMCwxLDc4NAoyMDI2LTA3LTAxLE9ZLDY0ODE2OS41NzAwMDAwMDAsMzU4MzQuOTU5MDAwMDAwLDIwOTA4LjY5NTgwNjQ1MiwxMTU1Ljk2NjQxOTM1NSwwLDAsMCwwLDEsNzg1CjIwMjYtMDctMDEsUEEsNDE3MTE3LjEwMDAwMDAwMCw0MTAxOTkuNjc2MDAwMDAwLDEzNDU1LjM5MDMyMjU4MSwxMzIzMi4yNDc2MTI5MDMsMCwwLDAsMCwxLDc4NgoyMDI2LTA3LTAxLFNBLDIyNDQ1ODQuNzYwMDAwMDAwLDY5OTkxMC40MzIwMDAwMDAsNzI0MDUuOTYwMDAwMDAwLDIyNTc3Ljc1NTg3MDk2OCwwLDAsMCwwLDEsNzg3CjIwMjYtMDctMDEsU0gsMTY3MDc4OS44ODAwMDAwMDAsNTY2Nzc0LjU2ODAwMDAwMCw1Mzg5Ni40NDc3NDE5MzUsMTgyODMuMDUwNTgwNjQ1LDAsMCwwLDAsMSw3ODgKMjAyNi0wOC0wMSxBSVQsMzQ4MTQ1LjUxMDAwMDAwMCw5NjExMC4wOTAwMDAwMDAsMTEyMzAuNTAwMzIyNTgxLDMxMDAuMzI1NDgzODcxLDAsMCwwLDEsMSw3ODkKMjAyNi0wOC0wMSxBTSw4MjEuMDYwMDAwMDAwLDc2NjY0NC41OTAwMDAwMDAsMjYuNDg1ODA2NDUyLDI0NzMwLjQ3MDY0NTE2MSwwLDAsMCwwLDEsNzkwCjIwMjYtMDgtMDEsQVAsMjIyNTc3LjY0ODAwMDAwMCwyMjYwNS4zMDUwMDAwMDAsNzE3OS45MjQxMjkwMzIsNzI5LjIwMzM4NzA5NywwLDAsMSwxLDEsNzkxCjIwMjYtMDgtMDEsQVUsMTk4MzcwNC42NTAwMDAwMDAsMjU1Nzc0LjE5NjAwMDAwMCw2Mzk5MC40NzI1ODA2NDUsODI1MC43ODA1MTYxMjksMCwwLDAsMCwxLDc5MgoyMDI2LTA4LTAxLEFWLDEwMjAuMTYwMDAwMDAwLDAuMDAwMDAwMDAwLDMyLjkwODM4NzA5NywwLjAwMDAwMDAwMCwwLDAsMCwwLDEsNzkzCjIwMjYtMDgtMDEsQ1UsNTQ5MDIxLjI1MDAwMDAwMCwxMzQ4MDkuODI3MDAwMDAwLDE3NzEwLjM2MjkwMzIyNiw0MzQ4LjcwNDA5Njc3NCwwLDAsMCwwLDEsNzk0CjIwMjYtMDgtMDEsRVksODM0ODgxLjEzMzAwMDAwMCwxNTIxODUuMTc1MDAwMDAwLDI2OTMxLjY0OTQ1MTYxMyw0OTA5LjE5OTE5MzU0OCwwLDAsMSwwLDEsNzk1CjIwMjYtMDgtMDEsSU4sNDAzNTgxLjE4MDAwMDAwMCw2NDM0OS4wMDAwMDAwMDAsMTMwMTguNzQ3NzQxOTM1LDIwNzUuNzc0MTkzNTQ4LDAsMCwwLDAsMSw3OTYKMjAyNi0wOC0wMSxJVFQsMTI0MjYzMS40ODkwMDAwMDAsNjIzMDcuMDI4MDAwMDAwLDQwMDg0Ljg4Njc0MTkzNSwyMDA5LjkwNDEyOTAzMiwwLDAsMCwwLDEsNzk3CjIwMjYtMDgtMDEsTEEsNDUxNjg3LjY2MDAwMDAwMCwyMTAwNjMuMDk5MDAwMDAwLDE0NTcwLjU2OTY3NzQxOSw2Nzc2LjIyOTAwMDAwMCwwLDAsMSwwLDEsNzk4CjIwMjYtMDgtMDEsTEksMzIwNjM4LjYwMDAwMDAwMCwxODEzNDIuNzAwMDAwMDAwLDEwMzQzLjE4MDY0NTE2MSw1ODQ5Ljc2NDUxNjEyOSwwLDAsMCwwLDEsNzk5CjIwMjYtMDgtMDEsT1ksNjM1OTk5LjI4MDAwMDAwMCwzNDQ2Mi4wNTkwMDAwMDAsMjA1MTYuMTA1ODA2NDUyLDExMTEuNjc5MzIyNTgxLDAsMCwwLDAsMSw4MDAKMjAyNi0wOC0wMSxQQSw0MjM0MDMuMDkwMDAwMDAwLDM4ODQ3NS41NjEwMDAwMDAsMTM2NTguMTY0MTkzNTQ4LDEyNTMxLjQ2OTcwOTY3NywwLDAsMCwwLDEsODAxCjIwMjYtMDgtMDEsU0EsMjI2MTU3My4wNjAwMDAwMDAsNjgzODkxLjk1ODAwMDAwMCw3Mjk1My45Njk2Nzc0MTksMjIwNjEuMDMwOTAzMjI2LDAsMCwwLDAsMSw4MDIKMjAyNi0wOC0wMSxTSCwxNjU5NDQ1LjcyMDAwMDAwMCw1NzcxNDEuMjIxMDAwMDAwLDUzNTMwLjUwNzA5Njc3NCwxODYxNy40NTg3NDE5MzUsMCwwLDAsMCwxLDgwMwo=\", BinaryEncoding.Base64), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Encabezados = Table.PromoteHeaders(Fuente, [PromoteAllScalars=true]),",
                "    Nulos = Table.ReplaceValue(Encabezados, \"\", null, Replacer.ReplaceValue, Table.ColumnNames(Encabezados)),",
                "    Tipos = Table.TransformColumnTypes(Nulos, {{\"Mes\", type date}, {\"Activo\", type text}, {\"Crudo_bbl\", type number}, {\"Gas_miles_pies3\", type number}, {\"Crudo_diario_bbl\", type number}, {\"Gas_diario_miles_pies3\", type number}, {\"Conflicto_crudo\", Int64.Type}, {\"Conflicto_gas\", Int64.Type}, {\"Atipico_crudo\", Int64.Type}, {\"Atipico_gas\", Int64.Type}, {\"Filas_origen\", Int64.Type}, {\"Referencias_origen\", type text}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "measures": [
          {
            "name": "Crudo observado (bbl)",
            "expression": "SUM(Produccion[Crudo_bbl])",
            "formatString": "#,0.00",
            "displayFolder": "Produccion",
            "description": "Suma del volumen disponible. Los faltantes no se sustituyen por cero.",
            "lineageTag": "a06a16c8-ca0b-5de2-a4b4-9421e7970fda"
          },
          {
            "name": "Gas observado (miles pies3)",
            "expression": "SUM(Produccion[Gas_miles_pies3])",
            "formatString": "#,0.00",
            "displayFolder": "Produccion",
            "description": "Unidad adoptada del diccionario del proyecto; no es crudo equivalente.",
            "lineageTag": "8463a94f-add5-50bc-a988-7559b2312c7e"
          },
          {
            "name": "N registros",
            "expression": "COUNTROWS(Produccion)",
            "formatString": "#,0",
            "displayFolder": "Calidad",
            "description": "Filas unicas activo-mes en el contexto filtrado.",
            "lineageTag": "eb0eb9bd-5b67-5768-b5c3-81d0af09148f"
          },
          {
            "name": "N crudo",
            "expression": "COUNT(Produccion[Crudo_bbl])",
            "formatString": "#,0",
            "displayFolder": "Calidad",
            "description": "Numero de observaciones mensuales no vacias de crudo; por activo equivale al n del grupo.",
            "lineageTag": "c19cdae4-6388-5174-a70b-510e3e6cc9ab"
          },
          {
            "name": "N gas",
            "expression": "COUNT(Produccion[Gas_miles_pies3])",
            "formatString": "#,0",
            "displayFolder": "Calidad",
            "description": "Numero de observaciones mensuales no vacias de gas.",
            "lineageTag": "4cfc2ab7-cf27-5cc4-bcec-2bd29274b5f7"
          },
          {
            "name": "Dias del periodo productivo",
            "expression": "CALCULATE(SUM(Calendario[Dias_mes]), KEEPFILTERS(Calendario[Con_produccion] = 1))",
            "formatString": "#,0",
            "displayFolder": "Produccion",
            "description": "Dias de los meses seleccionados dentro de enero 2022-agosto 2026, contados una sola vez. Un activo con cobertura incompleta conserva el denominador del periodo.",
            "lineageTag": "2cb9e75d-dd09-5897-a998-26ec490307f8"
          },
          {
            "name": "Aporte diario observado (bbl)",
            "expression": "DIVIDE([Crudo observado (bbl)], [Dias del periodo productivo])",
            "formatString": "#,0.00",
            "displayFolder": "Produccion",
            "description": "Volumen observado / dias del periodo. No es la media simple de las tasas ni un ajuste de faltantes; revisar n y cobertura al comparar activos.",
            "lineageTag": "23ed53db-48a8-57b2-beee-9d2dbba05dbf"
          },
          {
            "name": "Precio promedio (USD/bbl)",
            "expression": "AVERAGE(Precios[Precio_USD_bbl])",
            "formatString": "$#,0.00",
            "displayFolder": "Precios",
            "description": "Media simple entre meses con precio; no se repite por activo, no se pondera por produccion y no equivale a ingresos.",
            "lineageTag": "8138fdc4-336b-57f7-88e3-de53dee3d5c3"
          },
          {
            "name": "N meses con precio",
            "expression": "COUNT(Precios[Precio_USD_bbl])",
            "formatString": "#,0",
            "displayFolder": "Precios",
            "description": "Numero de precios mensuales validos en el periodo.",
            "lineageTag": "319f6f20-38c6-5cc2-9766-77675d76be92"
          },
          {
            "name": "Meses productivos sin precio",
            "expression": "CALCULATE(COUNTROWS(Calendario), KEEPFILTERS(Calendario[Con_produccion] = 1), KEEPFILTERS(Calendario[Con_precio] = 0))",
            "formatString": "#,0",
            "displayFolder": "Precios",
            "description": "Meses de la ventana productiva sin precio: agosto de 2026 en la fuente disponible.",
            "lineageTag": "eba57009-ccac-5326-9880-e011da345ddc"
          },
          {
            "name": "Activos observados",
            "expression": "DISTINCTCOUNT(Produccion[Activo])",
            "formatString": "#,0",
            "displayFolder": "Produccion",
            "description": "Activos con al menos un registro dentro de la seleccion.",
            "lineageTag": "b402fde6-6372-5e9b-a8a8-720f6e395216"
          },
          {
            "name": "Conflictos crudo",
            "expression": "SUM(Produccion[Conflicto_crudo])",
            "formatString": "#,0",
            "displayFolder": "Calidad",
            "description": "Celdas de crudo anuladas por valores discrepantes de una misma clave.",
            "lineageTag": "e91ee3f8-4f3b-598b-9001-43da009d845f"
          },
          {
            "name": "Conflictos gas",
            "expression": "SUM(Produccion[Conflicto_gas])",
            "formatString": "#,0",
            "displayFolder": "Calidad",
            "description": "Celdas de gas anuladas por valores discrepantes de una misma clave.",
            "lineageTag": "81344162-8107-5793-81e7-22a83977badf"
          },
          {
            "name": "Conflictos totales",
            "expression": "[Conflictos crudo] + [Conflictos gas]",
            "formatString": "#,0",
            "displayFolder": "Calidad",
            "description": "Cuenta de celdas conflictivas, no de filas duplicadas.",
            "lineageTag": "5f2f93eb-dd4d-57fc-9dd5-35914dc9ab79"
          },
          {
            "name": "Atipicos crudo",
            "expression": "SUM(Produccion[Atipico_crudo])",
            "formatString": "#,0",
            "displayFolder": "Calidad",
            "description": "Banderas IQR calculadas previamente dentro de cada activo. Se conservan los registros.",
            "lineageTag": "52539a7f-89df-5151-bcea-3f8e1fa3a2b9"
          },
          {
            "name": "Atipicos gas",
            "expression": "SUM(Produccion[Atipico_gas])",
            "formatString": "#,0",
            "displayFolder": "Calidad",
            "description": "Banderas IQR del gas diario dentro de cada activo; el filtro no recalcula los limites historicos.",
            "lineageTag": "ffd1a273-505c-506a-b774-84c7a77d398c"
          },
          {
            "name": "Huecos internos",
            "expression": "CALCULATE(COUNTROWS(Cobertura), KEEPFILTERS(Cobertura[Estado] = \"sin registro interior\"))",
            "formatString": "#,0",
            "displayFolder": "Calidad",
            "description": "Meses ausentes entre el primer y ultimo registro de cada activo; no son volumen cero.",
            "lineageTag": "b5421cb0-7cd2-5ba0-a188-e98f8dff9e9e"
          },
          {
            "name": "Estado del grupo",
            "expression": "VAR N = [N crudo] RETURN IF(ISBLANK(N) || N = 0, \"Sin crudo valido\", IF(N < 12, \"PRECAUCION: n < 12\", \"n >= 12; revisar cobertura\"))",
            "formatString": "",
            "displayFolder": "Calidad",
            "description": "Umbral descriptivo de doce meses para advertir series cortas; no garantiza independencia ni suficiencia estadistica.",
            "lineageTag": "fa15dc43-350f-57f5-948f-a91cdb3dc9cb"
          },
          {
            "name": "Grupos pequenos",
            "expression": "SUMX(VALUES(Activos[Activo]), VAR N = CALCULATE([N crudo]) RETURN IF(N > 0 && N < 12, 1, 0))",
            "formatString": "#,0",
            "displayFolder": "Calidad",
            "description": "Numero de activos seleccionados con entre uno y once meses validos de crudo.",
            "lineageTag": "64c5234a-7477-516b-8d32-80bc9e1aa3b4"
          },
          {
            "name": "Advertencia de grupos",
            "expression": "VAR G = [Grupos pequenos] RETURN IF(ISBLANK([N crudo]) || [N crudo] = 0, \"Sin datos de crudo en esta seleccion\", IF(G > 0, FORMAT(G, \"0\") & \" grupo(s) con n < 12. Interpretar con cautela.\", \"Revisar cobertura, faltantes y cambios de composicion.\"))",
            "formatString": "",
            "displayFolder": "Calidad",
            "description": "Advertencia dinamica segun filtros. Observaciones mensuales, no muestras independientes.",
            "lineageTag": "dd9fffdd-3c08-5267-9258-e477cbf86b96"
          },
          {
            "name": "Participacion crudo",
            "expression": "DIVIDE([Crudo observado (bbl)], CALCULATE([Crudo observado (bbl)], ALLSELECTED(Activos)))",
            "formatString": "0.0%",
            "displayFolder": "Produccion",
            "description": "Fraccion del crudo observado entre los activos seleccionados, manteniendo el periodo.",
            "lineageTag": "d522a674-e171-525c-8f4f-8d753fc6195d"
          }
        ]
      },
      {
        "name": "Precios",
        "lineageTag": "2c4c5e9d-c741-5111-873d-84c830e163d7",
        "columns": [
          {
            "name": "Mes",
            "dataType": "dateTime",
            "sourceColumn": "Mes",
            "summarizeBy": "none",
            "lineageTag": "5b85d36c-6bc4-505c-8557-ee45d3c20b63",
            "formatString": "yyyy-MM-dd"
          },
          {
            "name": "Precio_USD_bbl",
            "dataType": "double",
            "sourceColumn": "Precio_USD_bbl",
            "summarizeBy": "none",
            "lineageTag": "af1a6aae-3f78-5736-a4d7-e254de25e275",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "Precios",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Fuente = Csv.Document(Binary.FromText(\"TWVzLFByZWNpb19VU0RfYmJsCjIwMjEtMDEtMDEsNDguNjAwMDAwMDAwCjIwMjEtMDItMDEsNTUuNjEwMDAwMDAwCjIwMjEtMDMtMDEsNTguNzIwMDAwMDAwCjIwMjEtMDQtMDEsNTcuMjQwMDAwMDAwCjIwMjEtMDUtMDEsNjEuNTIwMDAwMDAwCjIwMjEtMDYtMDEsNjcuMjkwMDAwMDAwCjIwMjEtMDctMDEsNjYuODQwMDAwMDAwCjIwMjEtMDgtMDEsNjEuMTQwMDAwMDAwCjIwMjEtMDktMDEsNjQuNzQwMDAwMDAwCjIwMjEtMTAtMDEsNzUuMjAwMDAwMDAwCjIwMjEtMTEtMDEsNjguNDkwMDAwMDAwCjIwMjEtMTItMDEsNjAuMjgwMDAwMDAwCjIwMjItMDEtMDEsNzcuNjIwMDAwMDAwCjIwMjItMDItMDEsODQuNjYwMDAwMDAwCjIwMjItMDMtMDEsMTAwLjM4MDAwMDAwMAoyMDIyLTA0LTAxLDk0LjcwMDAwMDAwMAoyMDIyLTA1LTAxLDEwMS4zMTAwMDAwMDAKMjAyMi0wNi0wMSwxMDQuNDAwMDAwMDAwCjIwMjItMDctMDEsODcuNDYwMDAwMDAwCjIwMjItMDgtMDEsODMuMjgwMDAwMDAwCjIwMjItMDktMDEsNzcuNjAwMDAwMDAwCjIwMjItMTAtMDEsODAuNTEwMDAwMDAwCjIwMjItMTEtMDEsNzUuMzYwMDAwMDAwCjIwMjItMTItMDEsNjkuMjAwMDAwMDAwCjIwMjMtMDEtMDEsNjUuMTEwMDAwMDAwCjIwMjMtMDItMDEsNjQuMjAwMDAwMDAwCjIwMjMtMDMtMDEsNjAuNzYwMDAwMDAwCjIwMjMtMDQtMDEsNjguNzIwMDAwMDAwCjIwMjMtMDUtMDEsNjEuMzcwMDAwMDAwCjIwMjMtMDYtMDEsNTguMDgwMDAwMDAwCjIwMjMtMDctMDEsNjUuNTgwMDAwMDAwCjIwMjMtMDgtMDEsNzQuNjUwMDAwMDAwCjIwMjMtMDktMDEsODIuNzMwMDAwMDAwCjIwMjMtMTAtMDEsNzguMjkwMDAwMDAwCjIwMjMtMTEtMDEsNzEuNDAwMDAwMDAwCjIwMjMtMTItMDEsNjQuMjUwMDAwMDAwCjIwMjQtMDEtMDEsNjUuMzQwMDAwMDAwCjIwMjQtMDItMDEsNjkuOTcwMDAwMDAwCjIwMjQtMDMtMDEsNzMuNTcwMDAwMDAwCjIwMjQtMDQtMDEsNzcuNjIwMDAwMDAwCjIwMjQtMDUtMDEsNzEuODUwMDAwMDAwCjIwMjQtMDYtMDEsNzIuMTQwMDAwMDAwCjIwMjQtMDctMDEsNzQuNTEwMDAwMDAwCjIwMjQtMDgtMDEsNjguMTMwMDAwMDAwCjIwMjQtMDktMDEsNjIuMzMwMDAwMDAwCjIwMjQtMTAtMDEsNjUuMzMwMDAwMDAwCjIwMjQtMTEtMDEsNjAuODMwMDAwMDAwCjIwMjQtMTItMDEsNjIuMTMwMDAwMDAwCjIwMjUtMDEtMDEsNjcuMzAwMDAwMDAwCjIwMjUtMDItMDEsNjQuODIwMDAwMDAwCjIwMjUtMDMtMDEsNjEuMzEwMDAwMDAwCjIwMjUtMDQtMDEsNTYuMzMwMDAwMDAwCjIwMjUtMDUtMDEsNTUuMDYwMDAwMDAwCjIwMjUtMDYtMDEsNjAuNTIwMDAwMDAwCjIwMjUtMDctMDEsNTguMDMwMDAwMDAwCjIwMjUtMDgtMDEsNTguNTMwMDAwMDAwCjIwMjUtMDktMDEsNTcuNjkwMDAwMDAwCjIwMjUtMTAtMDEsNTUuNDgwMDAwMDAwCjIwMjUtMTEtMDEsNTMuMjcwMDAwMDAwCjIwMjUtMTItMDEsNTEuOTIwMDAwMDAwCjIwMjYtMDEtMDEsNTMuMTAwMDAwMDAwCjIwMjYtMDItMDEsNTcuMDYwMDAwMDAwCjIwMjYtMDMtMDEsODUuMjIwMDAwMDAwCjIwMjYtMDQtMDEsODkuNDQwMDAwMDAwCjIwMjYtMDUtMDEsOTMuMTIwMDAwMDAwCjIwMjYtMDYtMDEsNzkuMDMwMDAwMDAwCjIwMjYtMDctMDEsNzQuMzEwMDAwMDAwCg==\", BinaryEncoding.Base64), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Encabezados = Table.PromoteHeaders(Fuente, [PromoteAllScalars=true]),",
                "    Nulos = Table.ReplaceValue(Encabezados, \"\", null, Replacer.ReplaceValue, Table.ColumnNames(Encabezados)),",
                "    Tipos = Table.TransformColumnTypes(Nulos, {{\"Mes\", type date}, {\"Precio_USD_bbl\", type number}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Activos",
        "lineageTag": "2061f060-c30e-5bdf-8670-1aee33255bfd",
        "columns": [
          {
            "name": "Activo",
            "dataType": "string",
            "sourceColumn": "Activo",
            "summarizeBy": "none",
            "lineageTag": "721d3760-5c36-569f-b674-b270630ef243",
            "isKey": true
          },
          {
            "name": "Nombre",
            "dataType": "string",
            "sourceColumn": "Nombre",
            "summarizeBy": "none",
            "lineageTag": "2e261de1-eb4e-5357-9cfe-c519194cdd0b"
          },
          {
            "name": "Catalogo_faltante",
            "dataType": "int64",
            "sourceColumn": "Catalogo_faltante",
            "summarizeBy": "none",
            "lineageTag": "87d7a409-32c4-5b74-a3d1-c9eea5b5df48",
            "formatString": "0"
          },
          {
            "name": "Etiqueta",
            "dataType": "string",
            "sourceColumn": "Etiqueta",
            "summarizeBy": "none",
            "lineageTag": "2f2e3094-940f-55b2-8c12-74446dfffd33"
          }
        ],
        "partitions": [
          {
            "name": "Activos",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Fuente = Csv.Document(Binary.FromText(\"QWN0aXZvLE5vbWJyZSxDYXRhbG9nb19mYWx0YW50ZSxFdGlxdWV0YQpBTSxBbWlzdGFkLDAsQU0gfCBBbWlzdGFkCkFQLEFwYWlrYSwwLEFQIHwgQXBhaWthCkFVLEF1Y2EsMCxBVSB8IEF1Y2EKQ1UsQ3V5YWJlbm8sMCxDVSB8IEN1eWFiZW5vCkVZLEVkw6luIFl1dHVyaSwwLEVZIHwgRWTDqW4gWXV0dXJpCklOLEluZGlsbGFuYSwwLElOIHwgSW5kaWxsYW5hCklUVCxJc2hwaW5nby1UaXB1dGluaS1UYW1ib2NvY2hhLDAsSVRUIHwgSXNocGluZ28tVGlwdXRpbmktVGFtYm9jb2NoYQpMQSxMYWdvIEFncmlvLDAsTEEgfCBMYWdvIEFncmlvCkxJLExpYmVydGFkb3IsMCxMSSB8IExpYmVydGFkb3IKT1ksT3NvIFl1cmFscGEsMCxPWSB8IE9zbyBZdXJhbHBhClBBLFBhbG8gQXp1bCwwLFBBIHwgUGFsbyBBenVsClNBLFNhY2hhLDAsU0EgfCBTYWNoYQpTSCxTaHVzaHVmaW5kaSwwLFNIIHwgU2h1c2h1ZmluZGkKQUIxNixBQjE2IChzaW4gY2F0w6Fsb2dvKSwxLEFCMTYgfCBBQjE2IChzaW4gY2F0w6Fsb2dvKQpBVixBbWF6b25pYSBWaXZhLDAsQVYgfCBBbWF6b25pYSBWaXZhCkFJVCxBbW8tSXJvLVRpdmFjdW5vLDAsQUlUIHwgQW1vLUlyby1UaXZhY3Vubwo=\", BinaryEncoding.Base64), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Encabezados = Table.PromoteHeaders(Fuente, [PromoteAllScalars=true]),",
                "    Nulos = Table.ReplaceValue(Encabezados, \"\", null, Replacer.ReplaceValue, Table.ColumnNames(Encabezados)),",
                "    Tipos = Table.TransformColumnTypes(Nulos, {{\"Activo\", type text}, {\"Nombre\", type text}, {\"Catalogo_faltante\", Int64.Type}, {\"Etiqueta\", type text}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Calendario",
        "lineageTag": "b73bd678-8db2-5b49-891e-6a4eb6a33875",
        "columns": [
          {
            "name": "Mes",
            "dataType": "dateTime",
            "sourceColumn": "Mes",
            "summarizeBy": "none",
            "lineageTag": "6e01f5e5-8045-55bc-8021-39f438e7dc8a",
            "formatString": "yyyy-MM-dd",
            "isKey": true
          },
          {
            "name": "Anio",
            "dataType": "int64",
            "sourceColumn": "Anio",
            "summarizeBy": "none",
            "lineageTag": "782dc45d-39c6-5db1-a741-e07dcda0df5a",
            "formatString": "0"
          },
          {
            "name": "Mes_numero",
            "dataType": "int64",
            "sourceColumn": "Mes_numero",
            "summarizeBy": "none",
            "lineageTag": "71ad5564-41f6-52a1-a572-299257347656",
            "formatString": "0"
          },
          {
            "name": "Mes_nombre",
            "dataType": "string",
            "sourceColumn": "Mes_nombre",
            "summarizeBy": "none",
            "lineageTag": "fdf69929-de2d-5804-b999-3c02c81388f4",
            "sortByColumn": "Mes_numero"
          },
          {
            "name": "Anio_mes",
            "dataType": "string",
            "sourceColumn": "Anio_mes",
            "summarizeBy": "none",
            "lineageTag": "04fe6d7b-4490-5579-9d82-6093ee68337d"
          },
          {
            "name": "Trimestre",
            "dataType": "string",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none",
            "lineageTag": "d02a659d-b777-5be5-b707-c30c50d1c66d"
          },
          {
            "name": "Dias_mes",
            "dataType": "int64",
            "sourceColumn": "Dias_mes",
            "summarizeBy": "none",
            "lineageTag": "21b31ea2-636c-58a1-b0ff-c9eae26b4f52",
            "formatString": "0"
          },
          {
            "name": "Con_produccion",
            "dataType": "int64",
            "sourceColumn": "Con_produccion",
            "summarizeBy": "none",
            "lineageTag": "b135393a-c7c9-5184-8cbf-582b25ce6bed",
            "formatString": "0"
          },
          {
            "name": "Con_precio",
            "dataType": "int64",
            "sourceColumn": "Con_precio",
            "summarizeBy": "none",
            "lineageTag": "c396338d-d2aa-5f45-a9a4-e3060269cc2d",
            "formatString": "0"
          }
        ],
        "partitions": [
          {
            "name": "Calendario",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Fuente = Csv.Document(Binary.FromText(\"TWVzLEFuaW8sTWVzX251bWVybyxNZXNfbm9tYnJlLEFuaW9fbWVzLFRyaW1lc3RyZSxEaWFzX21lcyxDb25fcHJvZHVjY2lvbixDb25fcHJlY2lvCjIwMjEtMDEtMDEsMjAyMSwxLGVuZXJvLDIwMjEtMDEsVDEsMzEsMCwxCjIwMjEtMDItMDEsMjAyMSwyLGZlYnJlcm8sMjAyMS0wMixUMSwyOCwwLDEKMjAyMS0wMy0wMSwyMDIxLDMsbWFyem8sMjAyMS0wMyxUMSwzMSwwLDEKMjAyMS0wNC0wMSwyMDIxLDQsYWJyaWwsMjAyMS0wNCxUMiwzMCwwLDEKMjAyMS0wNS0wMSwyMDIxLDUsbWF5bywyMDIxLTA1LFQyLDMxLDAsMQoyMDIxLTA2LTAxLDIwMjEsNixqdW5pbywyMDIxLTA2LFQyLDMwLDAsMQoyMDIxLTA3LTAxLDIwMjEsNyxqdWxpbywyMDIxLTA3LFQzLDMxLDAsMQoyMDIxLTA4LTAxLDIwMjEsOCxhZ29zdG8sMjAyMS0wOCxUMywzMSwwLDEKMjAyMS0wOS0wMSwyMDIxLDksc2VwdGllbWJyZSwyMDIxLTA5LFQzLDMwLDAsMQoyMDIxLTEwLTAxLDIwMjEsMTAsb2N0dWJyZSwyMDIxLTEwLFQ0LDMxLDAsMQoyMDIxLTExLTAxLDIwMjEsMTEsbm92aWVtYnJlLDIwMjEtMTEsVDQsMzAsMCwxCjIwMjEtMTItMDEsMjAyMSwxMixkaWNpZW1icmUsMjAyMS0xMixUNCwzMSwwLDEKMjAyMi0wMS0wMSwyMDIyLDEsZW5lcm8sMjAyMi0wMSxUMSwzMSwxLDEKMjAyMi0wMi0wMSwyMDIyLDIsZmVicmVybywyMDIyLTAyLFQxLDI4LDEsMQoyMDIyLTAzLTAxLDIwMjIsMyxtYXJ6bywyMDIyLTAzLFQxLDMxLDEsMQoyMDIyLTA0LTAxLDIwMjIsNCxhYnJpbCwyMDIyLTA0LFQyLDMwLDEsMQoyMDIyLTA1LTAxLDIwMjIsNSxtYXlvLDIwMjItMDUsVDIsMzEsMSwxCjIwMjItMDYtMDEsMjAyMiw2LGp1bmlvLDIwMjItMDYsVDIsMzAsMSwxCjIwMjItMDctMDEsMjAyMiw3LGp1bGlvLDIwMjItMDcsVDMsMzEsMSwxCjIwMjItMDgtMDEsMjAyMiw4LGFnb3N0bywyMDIyLTA4LFQzLDMxLDEsMQoyMDIyLTA5LTAxLDIwMjIsOSxzZXB0aWVtYnJlLDIwMjItMDksVDMsMzAsMSwxCjIwMjItMTAtMDEsMjAyMiwxMCxvY3R1YnJlLDIwMjItMTAsVDQsMzEsMSwxCjIwMjItMTEtMDEsMjAyMiwxMSxub3ZpZW1icmUsMjAyMi0xMSxUNCwzMCwxLDEKMjAyMi0xMi0wMSwyMDIyLDEyLGRpY2llbWJyZSwyMDIyLTEyLFQ0LDMxLDEsMQoyMDIzLTAxLTAxLDIwMjMsMSxlbmVybywyMDIzLTAxLFQxLDMxLDEsMQoyMDIzLTAyLTAxLDIwMjMsMixmZWJyZXJvLDIwMjMtMDIsVDEsMjgsMSwxCjIwMjMtMDMtMDEsMjAyMywzLG1hcnpvLDIwMjMtMDMsVDEsMzEsMSwxCjIwMjMtMDQtMDEsMjAyMyw0LGFicmlsLDIwMjMtMDQsVDIsMzAsMSwxCjIwMjMtMDUtMDEsMjAyMyw1LG1heW8sMjAyMy0wNSxUMiwzMSwxLDEKMjAyMy0wNi0wMSwyMDIzLDYsanVuaW8sMjAyMy0wNixUMiwzMCwxLDEKMjAyMy0wNy0wMSwyMDIzLDcsanVsaW8sMjAyMy0wNyxUMywzMSwxLDEKMjAyMy0wOC0wMSwyMDIzLDgsYWdvc3RvLDIwMjMtMDgsVDMsMzEsMSwxCjIwMjMtMDktMDEsMjAyMyw5LHNlcHRpZW1icmUsMjAyMy0wOSxUMywzMCwxLDEKMjAyMy0xMC0wMSwyMDIzLDEwLG9jdHVicmUsMjAyMy0xMCxUNCwzMSwxLDEKMjAyMy0xMS0wMSwyMDIzLDExLG5vdmllbWJyZSwyMDIzLTExLFQ0LDMwLDEsMQoyMDIzLTEyLTAxLDIwMjMsMTIsZGljaWVtYnJlLDIwMjMtMTIsVDQsMzEsMSwxCjIwMjQtMDEtMDEsMjAyNCwxLGVuZXJvLDIwMjQtMDEsVDEsMzEsMSwxCjIwMjQtMDItMDEsMjAyNCwyLGZlYnJlcm8sMjAyNC0wMixUMSwyOSwxLDEKMjAyNC0wMy0wMSwyMDI0LDMsbWFyem8sMjAyNC0wMyxUMSwzMSwxLDEKMjAyNC0wNC0wMSwyMDI0LDQsYWJyaWwsMjAyNC0wNCxUMiwzMCwxLDEKMjAyNC0wNS0wMSwyMDI0LDUsbWF5bywyMDI0LTA1LFQyLDMxLDEsMQoyMDI0LTA2LTAxLDIwMjQsNixqdW5pbywyMDI0LTA2LFQyLDMwLDEsMQoyMDI0LTA3LTAxLDIwMjQsNyxqdWxpbywyMDI0LTA3LFQzLDMxLDEsMQoyMDI0LTA4LTAxLDIwMjQsOCxhZ29zdG8sMjAyNC0wOCxUMywzMSwxLDEKMjAyNC0wOS0wMSwyMDI0LDksc2VwdGllbWJyZSwyMDI0LTA5LFQzLDMwLDEsMQoyMDI0LTEwLTAxLDIwMjQsMTAsb2N0dWJyZSwyMDI0LTEwLFQ0LDMxLDEsMQoyMDI0LTExLTAxLDIwMjQsMTEsbm92aWVtYnJlLDIwMjQtMTEsVDQsMzAsMSwxCjIwMjQtMTItMDEsMjAyNCwxMixkaWNpZW1icmUsMjAyNC0xMixUNCwzMSwxLDEKMjAyNS0wMS0wMSwyMDI1LDEsZW5lcm8sMjAyNS0wMSxUMSwzMSwxLDEKMjAyNS0wMi0wMSwyMDI1LDIsZmVicmVybywyMDI1LTAyLFQxLDI4LDEsMQoyMDI1LTAzLTAxLDIwMjUsMyxtYXJ6bywyMDI1LTAzLFQxLDMxLDEsMQoyMDI1LTA0LTAxLDIwMjUsNCxhYnJpbCwyMDI1LTA0LFQyLDMwLDEsMQoyMDI1LTA1LTAxLDIwMjUsNSxtYXlvLDIwMjUtMDUsVDIsMzEsMSwxCjIwMjUtMDYtMDEsMjAyNSw2LGp1bmlvLDIwMjUtMDYsVDIsMzAsMSwxCjIwMjUtMDctMDEsMjAyNSw3LGp1bGlvLDIwMjUtMDcsVDMsMzEsMSwxCjIwMjUtMDgtMDEsMjAyNSw4LGFnb3N0bywyMDI1LTA4LFQzLDMxLDEsMQoyMDI1LTA5LTAxLDIwMjUsOSxzZXB0aWVtYnJlLDIwMjUtMDksVDMsMzAsMSwxCjIwMjUtMTAtMDEsMjAyNSwxMCxvY3R1YnJlLDIwMjUtMTAsVDQsMzEsMSwxCjIwMjUtMTEtMDEsMjAyNSwxMSxub3ZpZW1icmUsMjAyNS0xMSxUNCwzMCwxLDEKMjAyNS0xMi0wMSwyMDI1LDEyLGRpY2llbWJyZSwyMDI1LTEyLFQ0LDMxLDEsMQoyMDI2LTAxLTAxLDIwMjYsMSxlbmVybywyMDI2LTAxLFQxLDMxLDEsMQoyMDI2LTAyLTAxLDIwMjYsMixmZWJyZXJvLDIwMjYtMDIsVDEsMjgsMSwxCjIwMjYtMDMtMDEsMjAyNiwzLG1hcnpvLDIwMjYtMDMsVDEsMzEsMSwxCjIwMjYtMDQtMDEsMjAyNiw0LGFicmlsLDIwMjYtMDQsVDIsMzAsMSwxCjIwMjYtMDUtMDEsMjAyNiw1LG1heW8sMjAyNi0wNSxUMiwzMSwxLDEKMjAyNi0wNi0wMSwyMDI2LDYsanVuaW8sMjAyNi0wNixUMiwzMCwxLDEKMjAyNi0wNy0wMSwyMDI2LDcsanVsaW8sMjAyNi0wNyxUMywzMSwxLDEKMjAyNi0wOC0wMSwyMDI2LDgsYWdvc3RvLDIwMjYtMDgsVDMsMzEsMSwwCg==\", BinaryEncoding.Base64), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Encabezados = Table.PromoteHeaders(Fuente, [PromoteAllScalars=true]),",
                "    Nulos = Table.ReplaceValue(Encabezados, \"\", null, Replacer.ReplaceValue, Table.ColumnNames(Encabezados)),",
                "    Tipos = Table.TransformColumnTypes(Nulos, {{\"Mes\", type date}, {\"Anio\", Int64.Type}, {\"Mes_numero\", Int64.Type}, {\"Mes_nombre\", type text}, {\"Anio_mes\", type text}, {\"Trimestre\", type text}, {\"Dias_mes\", Int64.Type}, {\"Con_produccion\", Int64.Type}, {\"Con_precio\", Int64.Type}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Cobertura",
        "lineageTag": "e2d17b16-2403-5d54-bb07-b1158599049a",
        "columns": [
          {
            "name": "Mes",
            "dataType": "dateTime",
            "sourceColumn": "Mes",
            "summarizeBy": "none",
            "lineageTag": "7ab45219-1e80-5021-9776-09a02a041bf7",
            "formatString": "yyyy-MM-dd"
          },
          {
            "name": "Activo",
            "dataType": "string",
            "sourceColumn": "Activo",
            "summarizeBy": "none",
            "lineageTag": "1a6a02ca-b434-525a-9ce1-768c9a9d2d35"
          },
          {
            "name": "Estado",
            "dataType": "string",
            "sourceColumn": "Estado",
            "summarizeBy": "none",
            "lineageTag": "fd5b05c6-c5fe-52ab-983c-657116b6b606"
          },
          {
            "name": "Crudo_valido",
            "dataType": "int64",
            "sourceColumn": "Crudo_valido",
            "summarizeBy": "none",
            "lineageTag": "73d84675-29f1-5fc3-a6b1-51682a36c70e",
            "formatString": "0"
          },
          {
            "name": "Gas_valido",
            "dataType": "int64",
            "sourceColumn": "Gas_valido",
            "summarizeBy": "none",
            "lineageTag": "6872776f-b8a1-51b7-88e2-5f2153e5a47f",
            "formatString": "0"
          }
        ],
        "partitions": [
          {
            "name": "Cobertura",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Fuente = Csv.Document(Binary.FromText(\"TWVzLEFjdGl2byxFc3RhZG8sQ3J1ZG9fdmFsaWRvLEdhc192YWxpZG8KMjAyMi0wMS0wMSxBQjE2LGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjItMDItMDEsQUIxNixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTAzLTAxLEFCMTYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyMi0wNC0wMSxBQjE2LGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjItMDUtMDEsQUIxNixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTA2LTAxLEFCMTYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyMi0wNy0wMSxBQjE2LGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjItMDgtMDEsQUIxNixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTA5LTAxLEFCMTYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyMi0xMC0wMSxBQjE2LGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjItMTEtMDEsQUIxNixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTEyLTAxLEFCMTYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyMy0wMS0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyMy0wMi0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyMy0wMy0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyMy0wNC0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyMy0wNS0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyMy0wNi0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyMy0wNy0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyMy0wOC0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyMy0wOS0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyMy0xMC0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyMy0xMS0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyMy0xMi0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNC0wMS0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNC0wMi0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNC0wMy0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNC0wNC0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNC0wNS0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNC0wNi0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNC0wNy0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNC0wOC0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNC0wOS0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNC0xMC0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNC0xMS0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNC0xMi0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNS0wMS0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNS0wMi0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNS0wMy0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNS0wNC0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNS0wNS0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNS0wNi0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNS0wNy0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNS0wOC0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNS0wOS0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNS0xMC0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNS0xMS0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNS0xMi0wMSxBQjE2LG9ic2VydmFkbywxLDEKMjAyNi0wMS0wMSxBQjE2LGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjYtMDItMDEsQUIxNixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI2LTAzLTAxLEFCMTYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyNi0wNC0wMSxBQjE2LGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjYtMDUtMDEsQUIxNixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI2LTA2LTAxLEFCMTYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyNi0wNy0wMSxBQjE2LGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjYtMDgtMDEsQUIxNixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTAxLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTAyLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTAzLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTA0LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTA1LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTA2LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTA3LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTA4LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTA5LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTEwLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTExLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTEyLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTAxLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTAyLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTAzLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTA0LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTA1LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTA2LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTA3LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTA4LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTA5LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTEwLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTExLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTEyLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI0LTAxLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI0LTAyLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI0LTAzLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI0LTA0LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI0LTA1LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI0LTA2LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI0LTA3LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI0LTA4LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI0LTA5LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI0LTEwLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI0LTExLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI0LTEyLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI1LTAxLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI1LTAyLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI1LTAzLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI1LTA0LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI1LTA1LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI1LTA2LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI1LTA3LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI1LTA4LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI1LTA5LTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI1LTEwLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI1LTExLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI1LTEyLTAxLEFJVCxmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDI2LTAxLTAxLEFJVCxvYnNlcnZhZG8sMSwxCjIwMjYtMDItMDEsQUlULG9ic2VydmFkbywxLDEKMjAyNi0wMy0wMSxBSVQsb2JzZXJ2YWRvLDEsMQoyMDI2LTA0LTAxLEFJVCxvYnNlcnZhZG8sMSwxCjIwMjYtMDUtMDEsQUlULG9ic2VydmFkbywxLDEKMjAyNi0wNi0wMSxBSVQsb2JzZXJ2YWRvLDEsMQoyMDI2LTA3LTAxLEFJVCxvYnNlcnZhZG8sMSwxCjIwMjYtMDgtMDEsQUlULG9ic2VydmFkbywxLDEKMjAyMi0wMS0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjItMDItMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDIyLTAzLTAxLEFNLG9ic2VydmFkbywxLDEKMjAyMi0wNC0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjItMDUtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDIyLTA2LTAxLEFNLG9ic2VydmFkbywxLDEKMjAyMi0wNy0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjItMDgtMDEsQU0sb2JzZXJ2YWRvLDEsMAoyMDIyLTA5LTAxLEFNLG9ic2VydmFkbywxLDEKMjAyMi0xMC0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjItMTEtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDIyLTEyLTAxLEFNLG9ic2VydmFkbywxLDEKMjAyMy0wMS0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjMtMDItMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDIzLTAzLTAxLEFNLG9ic2VydmFkbywxLDEKMjAyMy0wNC0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjMtMDUtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDIzLTA2LTAxLEFNLG9ic2VydmFkbywxLDEKMjAyMy0wNy0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjMtMDgtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDIzLTA5LTAxLEFNLG9ic2VydmFkbywxLDEKMjAyMy0xMC0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjMtMTEtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDIzLTEyLTAxLEFNLG9ic2VydmFkbywxLDEKMjAyNC0wMS0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjQtMDItMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDI0LTAzLTAxLEFNLG9ic2VydmFkbywxLDEKMjAyNC0wNC0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjQtMDUtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDI0LTA2LTAxLEFNLG9ic2VydmFkbywxLDEKMjAyNC0wNy0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjQtMDgtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDI0LTA5LTAxLEFNLG9ic2VydmFkbywxLDEKMjAyNC0xMC0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjQtMTEtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDI0LTEyLTAxLEFNLG9ic2VydmFkbywxLDEKMjAyNS0wMS0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjUtMDItMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDI1LTAzLTAxLEFNLG9ic2VydmFkbywxLDEKMjAyNS0wNC0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjUtMDUtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDI1LTA2LTAxLEFNLG9ic2VydmFkbywxLDEKMjAyNS0wNy0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjUtMDgtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDI1LTA5LTAxLEFNLG9ic2VydmFkbywxLDEKMjAyNS0xMC0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjUtMTEtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDI1LTEyLTAxLEFNLG9ic2VydmFkbywxLDEKMjAyNi0wMS0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjYtMDItMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDI2LTAzLTAxLEFNLG9ic2VydmFkbywxLDEKMjAyNi0wNC0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjYtMDUtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDI2LTA2LTAxLEFNLG9ic2VydmFkbywxLDEKMjAyNi0wNy0wMSxBTSxvYnNlcnZhZG8sMSwxCjIwMjYtMDgtMDEsQU0sb2JzZXJ2YWRvLDEsMQoyMDIyLTAxLTAxLEFQLG9ic2VydmFkbywxLDEKMjAyMi0wMi0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjItMDMtMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDIyLTA0LTAxLEFQLG9ic2VydmFkbywxLDEKMjAyMi0wNS0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjItMDYtMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDIyLTA3LTAxLEFQLG9ic2VydmFkbywxLDEKMjAyMi0wOC0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjItMDktMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDIyLTEwLTAxLEFQLG9ic2VydmFkbywxLDEKMjAyMi0xMS0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjItMTItMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDIzLTAxLTAxLEFQLG9ic2VydmFkbywxLDEKMjAyMy0wMi0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjMtMDMtMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDIzLTA0LTAxLEFQLG9ic2VydmFkbywxLDEKMjAyMy0wNS0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjMtMDYtMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDIzLTA3LTAxLEFQLG9ic2VydmFkbywxLDEKMjAyMy0wOC0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjMtMDktMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDIzLTEwLTAxLEFQLG9ic2VydmFkbywxLDEKMjAyMy0xMS0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjMtMTItMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDI0LTAxLTAxLEFQLG9ic2VydmFkbywxLDEKMjAyNC0wMi0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjQtMDMtMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDI0LTA0LTAxLEFQLG9ic2VydmFkbywxLDEKMjAyNC0wNS0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjQtMDYtMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDI0LTA3LTAxLEFQLG9ic2VydmFkbywxLDEKMjAyNC0wOC0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjQtMDktMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDI0LTEwLTAxLEFQLG9ic2VydmFkbywxLDEKMjAyNC0xMS0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjQtMTItMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDI1LTAxLTAxLEFQLG9ic2VydmFkbywxLDEKMjAyNS0wMi0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjUtMDMtMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDI1LTA0LTAxLEFQLG9ic2VydmFkbywxLDEKMjAyNS0wNS0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjUtMDYtMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDI1LTA3LTAxLEFQLG9ic2VydmFkbywxLDEKMjAyNS0wOC0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjUtMDktMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDI1LTEwLTAxLEFQLG9ic2VydmFkbywxLDEKMjAyNS0xMS0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjUtMTItMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDI2LTAxLTAxLEFQLG9ic2VydmFkbywxLDEKMjAyNi0wMi0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjYtMDMtMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDI2LTA0LTAxLEFQLG9ic2VydmFkbywxLDEKMjAyNi0wNS0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjYtMDYtMDEsQVAsb2JzZXJ2YWRvLDEsMQoyMDI2LTA3LTAxLEFQLG9ic2VydmFkbywxLDEKMjAyNi0wOC0wMSxBUCxvYnNlcnZhZG8sMSwxCjIwMjItMDEtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDIyLTAyLTAxLEFVLG9ic2VydmFkbywxLDEKMjAyMi0wMy0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjItMDQtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDIyLTA1LTAxLEFVLG9ic2VydmFkbywxLDEKMjAyMi0wNi0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjItMDctMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDIyLTA4LTAxLEFVLG9ic2VydmFkbywxLDAKMjAyMi0wOS0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjItMTAtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDIyLTExLTAxLEFVLG9ic2VydmFkbywxLDEKMjAyMi0xMi0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjMtMDEtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDIzLTAyLTAxLEFVLG9ic2VydmFkbywxLDEKMjAyMy0wMy0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjMtMDQtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDIzLTA1LTAxLEFVLG9ic2VydmFkbywxLDEKMjAyMy0wNi0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjMtMDctMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDIzLTA4LTAxLEFVLG9ic2VydmFkbywxLDEKMjAyMy0wOS0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjMtMTAtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDIzLTExLTAxLEFVLG9ic2VydmFkbywxLDEKMjAyMy0xMi0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjQtMDEtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDI0LTAyLTAxLEFVLG9ic2VydmFkbywxLDEKMjAyNC0wMy0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjQtMDQtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDI0LTA1LTAxLEFVLG9ic2VydmFkbywxLDEKMjAyNC0wNi0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjQtMDctMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDI0LTA4LTAxLEFVLG9ic2VydmFkbywxLDEKMjAyNC0wOS0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjQtMTAtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDI0LTExLTAxLEFVLG9ic2VydmFkbywxLDEKMjAyNC0xMi0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjUtMDEtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDI1LTAyLTAxLEFVLG9ic2VydmFkbywxLDEKMjAyNS0wMy0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjUtMDQtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDI1LTA1LTAxLEFVLG9ic2VydmFkbywxLDEKMjAyNS0wNi0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjUtMDctMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDI1LTA4LTAxLEFVLG9ic2VydmFkbywxLDEKMjAyNS0wOS0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjUtMTAtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDI1LTExLTAxLEFVLG9ic2VydmFkbywxLDEKMjAyNS0xMi0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjYtMDEtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDI2LTAyLTAxLEFVLG9ic2VydmFkbywxLDEKMjAyNi0wMy0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjYtMDQtMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDI2LTA1LTAxLEFVLG9ic2VydmFkbywxLDEKMjAyNi0wNi0wMSxBVSxvYnNlcnZhZG8sMSwxCjIwMjYtMDctMDEsQVUsb2JzZXJ2YWRvLDEsMQoyMDI2LTA4LTAxLEFVLG9ic2VydmFkbywxLDEKMjAyMi0wMS0wMSxBVixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTAyLTAxLEFWLGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjItMDMtMDEsQVYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyMi0wNC0wMSxBVixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTA1LTAxLEFWLGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjItMDYtMDEsQVYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyMi0wNy0wMSxBVixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTA4LTAxLEFWLGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjItMDktMDEsQVYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyMi0xMC0wMSxBVixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIyLTExLTAxLEFWLGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjItMTItMDEsQVYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyMy0wMS0wMSxBVixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTAyLTAxLEFWLGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjMtMDMtMDEsQVYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyMy0wNC0wMSxBVixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTA1LTAxLEFWLGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjMtMDYtMDEsQVYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyMy0wNy0wMSxBVixmdWVyYSBkZSBjb2JlcnR1cmEgb2JzZXJ2YWRhLDAsMAoyMDIzLTA4LTAxLEFWLGZ1ZXJhIGRlIGNvYmVydHVyYSBvYnNlcnZhZGEsMCwwCjIwMjMtMDktMDEsQVYsZnVlcmEgZGUgY29iZXJ0dXJhIG9ic2VydmFkYSwwLDAKMjAyMy0xMC0wMSxBVixvYnNlcnZhZG8sMSwxCjIwMjMtMTEtMDEsQVYsc2luIHJlZ2lzdHJvIGludGVyaW9yLDAsMAoyMDIzLTEyLTAxLEFWLHNpbiByZWdpc3RybyBpbnRlcmlvciwwLDAKMjAyNC0wMS0wMSxBVixzaW4gcmVnaXN0cm8gaW50ZXJpb3IsMCwwCjIwMjQtMDItMDEsQVYsc2luIHJlZ2lzdHJvIGludGVyaW9yLDAsMAoyMDI0LTAzLTAxLEFWLHNpbiByZWdpc3RybyBpbnRlcmlvciwwLDAKMjAyNC0wNC0wMSxBVixzaW4gcmVnaXN0cm8gaW50ZXJpb3IsMCwwCjIwMjQtMDUtMDEsQVYsc2luIHJlZ2lzdHJvIGludGVyaW9yLDAsMAoyMDI0LTA2LTAxLEFWLHNpbiByZWdpc3RybyBpbnRlcmlvciwwLDAKMjAyNC0wNy0wMSxBVixzaW4gcmVnaXN0cm8gaW50ZXJpb3IsMCwwCjIwMjQtMDgtMDEsQVYsc2luIHJlZ2lzdHJvIGludGVyaW9yLDAsMAoyMDI0LTA5LTAxLEFWLHNpbiByZWdpc3RybyBpbnRlcmlvciwwLDAKMjAyNC0xMC0wMSxBVixzaW4gcmVnaXN0cm8gaW50ZXJpb3IsMCwwCjIwMjQtMTEtMDEsQVYsc2luIHJlZ2lzdHJvIGludGVyaW9yLDAsMAoyMDI0LTEyLTAxLEFWLHNpbiByZWdpc3RybyBpbnRlcmlvciwwLDAKMjAyNS0wMS0wMSxBVixvYnNlcnZhZG8sMSwxCjIwMjUtMDItMDEsQVYsb2JzZXJ2YWRvLDEsMQoyMDI1LTAzLTAxLEFWLG9ic2VydmFkbywxLDEKMjAyNS0wNC0wMSxBVixvYnNlcnZhZG8sMSwxCjIwMjUtMDUtMDEsQVYsb2JzZXJ2YWRvLDEsMQoyMDI1LTA2LTAxLEFWLG9ic2VydmFkbywxLDEKMjAyNS0wNy0wMSxBVixvYnNlcnZhZG8sMSwxCjIwMjUtMDgtMDEsQVYsb2JzZXJ2YWRvLDEsMQoyMDI1LTA5LTAxLEFWLG9ic2VydmFkbywxLDEKMjAyNS0xMC0wMSxBVixzaW4gcmVnaXN0cm8gaW50ZXJpb3IsMCwwCjIwMjUtMTEtMDEsQVYsc2luIHJlZ2lzdHJvIGludGVyaW9yLDAsMAoyMDI1LTEyLTAxLEFWLHNpbiByZWdpc3RybyBpbnRlcmlvciwwLDAKMjAyNi0wMS0wMSxBVixvYnNlcnZhZG8sMSwxCjIwMjYtMDItMDEsQVYsb2JzZXJ2YWRvLDEsMQoyMDI2LTAzLTAxLEFWLG9ic2VydmFkbywxLDEKMjAyNi0wNC0wMSxBVixvYnNlcnZhZG8sMSwxCjIwMjYtMDUtMDEsQVYsb2JzZXJ2YWRvLDEsMQoyMDI2LTA2LTAxLEFWLG9ic2VydmFkbywxLDEKMjAyNi0wNy0wMSxBVixvYnNlcnZhZG8sMSwxCjIwMjYtMDgtMDEsQVYsb2JzZXJ2YWRvLDEsMQoyMDIyLTAxLTAxLENVLG9ic2VydmFkbywxLDEKMjAyMi0wMi0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjItMDMtMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDIyLTA0LTAxLENVLG9ic2VydmFkbywxLDEKMjAyMi0wNS0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjItMDYtMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDIyLTA3LTAxLENVLG9ic2VydmFkbywxLDEKMjAyMi0wOC0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjItMDktMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDIyLTEwLTAxLENVLG9ic2VydmFkbywxLDEKMjAyMi0xMS0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjItMTItMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDIzLTAxLTAxLENVLG9ic2VydmFkbywxLDEKMjAyMy0wMi0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjMtMDMtMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDIzLTA0LTAxLENVLG9ic2VydmFkbywxLDEKMjAyMy0wNS0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjMtMDYtMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDIzLTA3LTAxLENVLG9ic2VydmFkbywxLDEKMjAyMy0wOC0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjMtMDktMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDIzLTEwLTAxLENVLG9ic2VydmFkbywxLDEKMjAyMy0xMS0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjMtMTItMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDI0LTAxLTAxLENVLG9ic2VydmFkbywxLDEKMjAyNC0wMi0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjQtMDMtMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDI0LTA0LTAxLENVLG9ic2VydmFkbywxLDEKMjAyNC0wNS0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjQtMDYtMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDI0LTA3LTAxLENVLG9ic2VydmFkbywxLDEKMjAyNC0wOC0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjQtMDktMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDI0LTEwLTAxLENVLG9ic2VydmFkbywxLDEKMjAyNC0xMS0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjQtMTItMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDI1LTAxLTAxLENVLG9ic2VydmFkbywxLDEKMjAyNS0wMi0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjUtMDMtMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDI1LTA0LTAxLENVLG9ic2VydmFkbywxLDEKMjAyNS0wNS0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjUtMDYtMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDI1LTA3LTAxLENVLG9ic2VydmFkbywxLDEKMjAyNS0wOC0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjUtMDktMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDI1LTEwLTAxLENVLG9ic2VydmFkbywxLDEKMjAyNS0xMS0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjUtMTItMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDI2LTAxLTAxLENVLG9ic2VydmFkbywxLDEKMjAyNi0wMi0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjYtMDMtMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDI2LTA0LTAxLENVLG9ic2VydmFkbywxLDEKMjAyNi0wNS0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjYtMDYtMDEsQ1Usb2JzZXJ2YWRvLDEsMQoyMDI2LTA3LTAxLENVLG9ic2VydmFkbywxLDEKMjAyNi0wOC0wMSxDVSxvYnNlcnZhZG8sMSwxCjIwMjItMDEtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDIyLTAyLTAxLEVZLG9ic2VydmFkbywxLDEKMjAyMi0wMy0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjItMDQtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDIyLTA1LTAxLEVZLG9ic2VydmFkbywxLDEKMjAyMi0wNi0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjItMDctMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDIyLTA4LTAxLEVZLG9ic2VydmFkbywxLDEKMjAyMi0wOS0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjItMTAtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDIyLTExLTAxLEVZLG9ic2VydmFkbywxLDEKMjAyMi0xMi0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjMtMDEtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDIzLTAyLTAxLEVZLG9ic2VydmFkbywxLDEKMjAyMy0wMy0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjMtMDQtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDIzLTA1LTAxLEVZLG9ic2VydmFkbywxLDEKMjAyMy0wNi0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjMtMDctMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDIzLTA4LTAxLEVZLG9ic2VydmFkbywxLDEKMjAyMy0wOS0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjMtMTAtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDIzLTExLTAxLEVZLG9ic2VydmFkbywxLDEKMjAyMy0xMi0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjQtMDEtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDI0LTAyLTAxLEVZLG9ic2VydmFkbywxLDEKMjAyNC0wMy0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjQtMDQtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDI0LTA1LTAxLEVZLG9ic2VydmFkbywxLDEKMjAyNC0wNi0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjQtMDctMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDI0LTA4LTAxLEVZLG9ic2VydmFkbywxLDEKMjAyNC0wOS0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjQtMTAtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDI0LTExLTAxLEVZLG9ic2VydmFkbywxLDEKMjAyNC0xMi0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjUtMDEtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDI1LTAyLTAxLEVZLG9ic2VydmFkbywxLDEKMjAyNS0wMy0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjUtMDQtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDI1LTA1LTAxLEVZLG9ic2VydmFkbywxLDEKMjAyNS0wNi0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjUtMDctMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDI1LTA4LTAxLEVZLG9ic2VydmFkbywxLDEKMjAyNS0wOS0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjUtMTAtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDI1LTExLTAxLEVZLG9ic2VydmFkbywxLDEKMjAyNS0xMi0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjYtMDEtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDI2LTAyLTAxLEVZLG9ic2VydmFkbywxLDEKMjAyNi0wMy0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjYtMDQtMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDI2LTA1LTAxLEVZLG9ic2VydmFkbywxLDEKMjAyNi0wNi0wMSxFWSxvYnNlcnZhZG8sMSwxCjIwMjYtMDctMDEsRVksb2JzZXJ2YWRvLDEsMQoyMDI2LTA4LTAxLEVZLG9ic2VydmFkbywxLDEKMjAyMi0wMS0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjItMDItMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDIyLTAzLTAxLElOLG9ic2VydmFkbywxLDEKMjAyMi0wNC0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjItMDUtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDIyLTA2LTAxLElOLG9ic2VydmFkbywxLDEKMjAyMi0wNy0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjItMDgtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDIyLTA5LTAxLElOLG9ic2VydmFkbywxLDEKMjAyMi0xMC0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjItMTEtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDIyLTEyLTAxLElOLG9ic2VydmFkbywxLDEKMjAyMy0wMS0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjMtMDItMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDIzLTAzLTAxLElOLG9ic2VydmFkbywxLDEKMjAyMy0wNC0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjMtMDUtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDIzLTA2LTAxLElOLG9ic2VydmFkbywxLDEKMjAyMy0wNy0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjMtMDgtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDIzLTA5LTAxLElOLG9ic2VydmFkbywxLDEKMjAyMy0xMC0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjMtMTEtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDIzLTEyLTAxLElOLG9ic2VydmFkbywxLDEKMjAyNC0wMS0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjQtMDItMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDI0LTAzLTAxLElOLG9ic2VydmFkbywxLDEKMjAyNC0wNC0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjQtMDUtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDI0LTA2LTAxLElOLG9ic2VydmFkbywxLDEKMjAyNC0wNy0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjQtMDgtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDI0LTA5LTAxLElOLG9ic2VydmFkbywxLDEKMjAyNC0xMC0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjQtMTEtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDI0LTEyLTAxLElOLG9ic2VydmFkbywxLDEKMjAyNS0wMS0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjUtMDItMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDI1LTAzLTAxLElOLG9ic2VydmFkbywxLDEKMjAyNS0wNC0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjUtMDUtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDI1LTA2LTAxLElOLG9ic2VydmFkbywxLDEKMjAyNS0wNy0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjUtMDgtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDI1LTA5LTAxLElOLG9ic2VydmFkbywxLDEKMjAyNS0xMC0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjUtMTEtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDI1LTEyLTAxLElOLG9ic2VydmFkbywxLDEKMjAyNi0wMS0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjYtMDItMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDI2LTAzLTAxLElOLG9ic2VydmFkbywxLDEKMjAyNi0wNC0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjYtMDUtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDI2LTA2LTAxLElOLG9ic2VydmFkbywxLDEKMjAyNi0wNy0wMSxJTixvYnNlcnZhZG8sMSwxCjIwMjYtMDgtMDEsSU4sb2JzZXJ2YWRvLDEsMQoyMDIyLTAxLTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjItMDItMDEsSVRULG9ic2VydmFkbywxLDEKMjAyMi0wMy0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDIyLTA0LTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjItMDUtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyMi0wNi0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDIyLTA3LTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjItMDgtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyMi0wOS0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDIyLTEwLTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjItMTEtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyMi0xMi0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDIzLTAxLTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjMtMDItMDEsSVRULG9ic2VydmFkbywxLDEKMjAyMy0wMy0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDIzLTA0LTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjMtMDUtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyMy0wNi0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDIzLTA3LTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjMtMDgtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyMy0wOS0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDIzLTEwLTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjMtMTEtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyMy0xMi0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDI0LTAxLTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjQtMDItMDEsSVRULG9ic2VydmFkbywxLDEKMjAyNC0wMy0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDI0LTA0LTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjQtMDUtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyNC0wNi0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDI0LTA3LTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjQtMDgtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyNC0wOS0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDI0LTEwLTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjQtMTEtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyNC0xMi0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDI1LTAxLTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjUtMDItMDEsSVRULG9ic2VydmFkbywxLDEKMjAyNS0wMy0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDI1LTA0LTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjUtMDUtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyNS0wNi0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDI1LTA3LTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjUtMDgtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyNS0wOS0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDI1LTEwLTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjUtMTEtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyNS0xMi0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDI2LTAxLTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjYtMDItMDEsSVRULG9ic2VydmFkbywxLDEKMjAyNi0wMy0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDI2LTA0LTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjYtMDUtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyNi0wNi0wMSxJVFQsb2JzZXJ2YWRvLDEsMQoyMDI2LTA3LTAxLElUVCxvYnNlcnZhZG8sMSwxCjIwMjYtMDgtMDEsSVRULG9ic2VydmFkbywxLDEKMjAyMi0wMS0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjItMDItMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDIyLTAzLTAxLExBLG9ic2VydmFkbywxLDEKMjAyMi0wNC0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjItMDUtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDIyLTA2LTAxLExBLG9ic2VydmFkbywxLDEKMjAyMi0wNy0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjItMDgtMDEsTEEsb2JzZXJ2YWRvLDAsMQoyMDIyLTA5LTAxLExBLG9ic2VydmFkbywxLDEKMjAyMi0xMC0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjItMTEtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDIyLTEyLTAxLExBLG9ic2VydmFkbywxLDEKMjAyMy0wMS0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjMtMDItMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDIzLTAzLTAxLExBLG9ic2VydmFkbywxLDEKMjAyMy0wNC0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjMtMDUtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDIzLTA2LTAxLExBLG9ic2VydmFkbywxLDEKMjAyMy0wNy0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjMtMDgtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDIzLTA5LTAxLExBLG9ic2VydmFkbywxLDEKMjAyMy0xMC0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjMtMTEtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDIzLTEyLTAxLExBLG9ic2VydmFkbywxLDEKMjAyNC0wMS0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjQtMDItMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDI0LTAzLTAxLExBLG9ic2VydmFkbywxLDEKMjAyNC0wNC0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjQtMDUtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDI0LTA2LTAxLExBLG9ic2VydmFkbywxLDEKMjAyNC0wNy0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjQtMDgtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDI0LTA5LTAxLExBLG9ic2VydmFkbywxLDEKMjAyNC0xMC0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjQtMTEtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDI0LTEyLTAxLExBLG9ic2VydmFkbywxLDEKMjAyNS0wMS0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjUtMDItMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDI1LTAzLTAxLExBLG9ic2VydmFkbywxLDEKMjAyNS0wNC0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjUtMDUtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDI1LTA2LTAxLExBLG9ic2VydmFkbywxLDEKMjAyNS0wNy0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjUtMDgtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDI1LTA5LTAxLExBLG9ic2VydmFkbywxLDEKMjAyNS0xMC0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjUtMTEtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDI1LTEyLTAxLExBLG9ic2VydmFkbywxLDEKMjAyNi0wMS0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjYtMDItMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDI2LTAzLTAxLExBLG9ic2VydmFkbywxLDEKMjAyNi0wNC0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjYtMDUtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDI2LTA2LTAxLExBLG9ic2VydmFkbywxLDEKMjAyNi0wNy0wMSxMQSxvYnNlcnZhZG8sMSwxCjIwMjYtMDgtMDEsTEEsb2JzZXJ2YWRvLDEsMQoyMDIyLTAxLTAxLExJLG9ic2VydmFkbywxLDEKMjAyMi0wMi0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjItMDMtMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDIyLTA0LTAxLExJLG9ic2VydmFkbywxLDEKMjAyMi0wNS0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjItMDYtMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDIyLTA3LTAxLExJLG9ic2VydmFkbywxLDEKMjAyMi0wOC0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjItMDktMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDIyLTEwLTAxLExJLG9ic2VydmFkbywxLDEKMjAyMi0xMS0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjItMTItMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDIzLTAxLTAxLExJLG9ic2VydmFkbywxLDEKMjAyMy0wMi0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjMtMDMtMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDIzLTA0LTAxLExJLG9ic2VydmFkbywxLDEKMjAyMy0wNS0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjMtMDYtMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDIzLTA3LTAxLExJLG9ic2VydmFkbywxLDEKMjAyMy0wOC0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjMtMDktMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDIzLTEwLTAxLExJLG9ic2VydmFkbywxLDEKMjAyMy0xMS0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjMtMTItMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDI0LTAxLTAxLExJLG9ic2VydmFkbywxLDEKMjAyNC0wMi0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjQtMDMtMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDI0LTA0LTAxLExJLG9ic2VydmFkbywxLDEKMjAyNC0wNS0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjQtMDYtMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDI0LTA3LTAxLExJLG9ic2VydmFkbywxLDEKMjAyNC0wOC0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjQtMDktMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDI0LTEwLTAxLExJLG9ic2VydmFkbywxLDEKMjAyNC0xMS0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjQtMTItMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDI1LTAxLTAxLExJLG9ic2VydmFkbywxLDEKMjAyNS0wMi0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjUtMDMtMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDI1LTA0LTAxLExJLG9ic2VydmFkbywxLDEKMjAyNS0wNS0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjUtMDYtMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDI1LTA3LTAxLExJLG9ic2VydmFkbywxLDEKMjAyNS0wOC0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjUtMDktMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDI1LTEwLTAxLExJLG9ic2VydmFkbywxLDEKMjAyNS0xMS0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjUtMTItMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDI2LTAxLTAxLExJLG9ic2VydmFkbywxLDEKMjAyNi0wMi0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjYtMDMtMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDI2LTA0LTAxLExJLG9ic2VydmFkbywxLDEKMjAyNi0wNS0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjYtMDYtMDEsTEksb2JzZXJ2YWRvLDEsMQoyMDI2LTA3LTAxLExJLG9ic2VydmFkbywxLDEKMjAyNi0wOC0wMSxMSSxvYnNlcnZhZG8sMSwxCjIwMjItMDEtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDIyLTAyLTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyMi0wMy0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjItMDQtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDIyLTA1LTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyMi0wNi0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjItMDctMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDIyLTA4LTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyMi0wOS0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjItMTAtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDIyLTExLTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyMi0xMi0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjMtMDEtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDIzLTAyLTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyMy0wMy0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjMtMDQtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDIzLTA1LTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyMy0wNi0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjMtMDctMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDIzLTA4LTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyMy0wOS0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjMtMTAtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDIzLTExLTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyMy0xMi0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjQtMDEtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDI0LTAyLTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyNC0wMy0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjQtMDQtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDI0LTA1LTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyNC0wNi0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjQtMDctMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDI0LTA4LTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyNC0wOS0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjQtMTAtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDI0LTExLTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyNC0xMi0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjUtMDEtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDI1LTAyLTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyNS0wMy0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjUtMDQtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDI1LTA1LTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyNS0wNi0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjUtMDctMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDI1LTA4LTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyNS0wOS0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjUtMTAtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDI1LTExLTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyNS0xMi0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjYtMDEtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDI2LTAyLTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyNi0wMy0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjYtMDQtMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDI2LTA1LTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyNi0wNi0wMSxPWSxvYnNlcnZhZG8sMSwxCjIwMjYtMDctMDEsT1ksb2JzZXJ2YWRvLDEsMQoyMDI2LTA4LTAxLE9ZLG9ic2VydmFkbywxLDEKMjAyMi0wMS0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjItMDItMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDIyLTAzLTAxLFBBLG9ic2VydmFkbywxLDEKMjAyMi0wNC0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjItMDUtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDIyLTA2LTAxLFBBLG9ic2VydmFkbywxLDEKMjAyMi0wNy0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjItMDgtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDIyLTA5LTAxLFBBLG9ic2VydmFkbywxLDEKMjAyMi0xMC0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjItMTEtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDIyLTEyLTAxLFBBLG9ic2VydmFkbywxLDEKMjAyMy0wMS0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjMtMDItMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDIzLTAzLTAxLFBBLG9ic2VydmFkbywxLDEKMjAyMy0wNC0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjMtMDUtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDIzLTA2LTAxLFBBLG9ic2VydmFkbywxLDEKMjAyMy0wNy0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjMtMDgtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDIzLTA5LTAxLFBBLG9ic2VydmFkbywxLDEKMjAyMy0xMC0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjMtMTEtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDIzLTEyLTAxLFBBLG9ic2VydmFkbywxLDEKMjAyNC0wMS0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjQtMDItMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDI0LTAzLTAxLFBBLG9ic2VydmFkbywxLDEKMjAyNC0wNC0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjQtMDUtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDI0LTA2LTAxLFBBLG9ic2VydmFkbywxLDEKMjAyNC0wNy0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjQtMDgtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDI0LTA5LTAxLFBBLG9ic2VydmFkbywxLDEKMjAyNC0xMC0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjQtMTEtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDI0LTEyLTAxLFBBLG9ic2VydmFkbywxLDEKMjAyNS0wMS0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjUtMDItMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDI1LTAzLTAxLFBBLG9ic2VydmFkbywxLDEKMjAyNS0wNC0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjUtMDUtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDI1LTA2LTAxLFBBLG9ic2VydmFkbywxLDEKMjAyNS0wNy0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjUtMDgtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDI1LTA5LTAxLFBBLG9ic2VydmFkbywxLDEKMjAyNS0xMC0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjUtMTEtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDI1LTEyLTAxLFBBLG9ic2VydmFkbywxLDEKMjAyNi0wMS0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjYtMDItMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDI2LTAzLTAxLFBBLG9ic2VydmFkbywxLDEKMjAyNi0wNC0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjYtMDUtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDI2LTA2LTAxLFBBLG9ic2VydmFkbywxLDEKMjAyNi0wNy0wMSxQQSxvYnNlcnZhZG8sMSwxCjIwMjYtMDgtMDEsUEEsb2JzZXJ2YWRvLDEsMQoyMDIyLTAxLTAxLFNBLG9ic2VydmFkbywxLDEKMjAyMi0wMi0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjItMDMtMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDIyLTA0LTAxLFNBLG9ic2VydmFkbywxLDEKMjAyMi0wNS0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjItMDYtMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDIyLTA3LTAxLFNBLG9ic2VydmFkbywxLDEKMjAyMi0wOC0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjItMDktMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDIyLTEwLTAxLFNBLG9ic2VydmFkbywxLDEKMjAyMi0xMS0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjItMTItMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDIzLTAxLTAxLFNBLG9ic2VydmFkbywxLDEKMjAyMy0wMi0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjMtMDMtMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDIzLTA0LTAxLFNBLG9ic2VydmFkbywxLDEKMjAyMy0wNS0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjMtMDYtMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDIzLTA3LTAxLFNBLG9ic2VydmFkbywxLDEKMjAyMy0wOC0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjMtMDktMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDIzLTEwLTAxLFNBLG9ic2VydmFkbywxLDEKMjAyMy0xMS0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjMtMTItMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDI0LTAxLTAxLFNBLG9ic2VydmFkbywxLDEKMjAyNC0wMi0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjQtMDMtMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDI0LTA0LTAxLFNBLG9ic2VydmFkbywxLDEKMjAyNC0wNS0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjQtMDYtMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDI0LTA3LTAxLFNBLG9ic2VydmFkbywxLDEKMjAyNC0wOC0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjQtMDktMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDI0LTEwLTAxLFNBLG9ic2VydmFkbywxLDEKMjAyNC0xMS0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjQtMTItMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDI1LTAxLTAxLFNBLG9ic2VydmFkbywxLDEKMjAyNS0wMi0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjUtMDMtMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDI1LTA0LTAxLFNBLG9ic2VydmFkbywxLDEKMjAyNS0wNS0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjUtMDYtMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDI1LTA3LTAxLFNBLG9ic2VydmFkbywxLDEKMjAyNS0wOC0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjUtMDktMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDI1LTEwLTAxLFNBLG9ic2VydmFkbywxLDEKMjAyNS0xMS0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjUtMTItMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDI2LTAxLTAxLFNBLG9ic2VydmFkbywxLDEKMjAyNi0wMi0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjYtMDMtMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDI2LTA0LTAxLFNBLG9ic2VydmFkbywxLDEKMjAyNi0wNS0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjYtMDYtMDEsU0Esb2JzZXJ2YWRvLDEsMQoyMDI2LTA3LTAxLFNBLG9ic2VydmFkbywxLDEKMjAyNi0wOC0wMSxTQSxvYnNlcnZhZG8sMSwxCjIwMjItMDEtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDIyLTAyLTAxLFNILG9ic2VydmFkbywxLDEKMjAyMi0wMy0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjItMDQtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDIyLTA1LTAxLFNILG9ic2VydmFkbywxLDEKMjAyMi0wNi0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjItMDctMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDIyLTA4LTAxLFNILG9ic2VydmFkbywxLDEKMjAyMi0wOS0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjItMTAtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDIyLTExLTAxLFNILG9ic2VydmFkbywxLDEKMjAyMi0xMi0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjMtMDEtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDIzLTAyLTAxLFNILG9ic2VydmFkbywxLDEKMjAyMy0wMy0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjMtMDQtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDIzLTA1LTAxLFNILG9ic2VydmFkbywxLDEKMjAyMy0wNi0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjMtMDctMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDIzLTA4LTAxLFNILG9ic2VydmFkbywxLDEKMjAyMy0wOS0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjMtMTAtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDIzLTExLTAxLFNILG9ic2VydmFkbywxLDEKMjAyMy0xMi0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjQtMDEtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDI0LTAyLTAxLFNILG9ic2VydmFkbywxLDEKMjAyNC0wMy0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjQtMDQtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDI0LTA1LTAxLFNILG9ic2VydmFkbywxLDEKMjAyNC0wNi0wMSxTSCxzaW4gcmVnaXN0cm8gaW50ZXJpb3IsMCwwCjIwMjQtMDctMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDI0LTA4LTAxLFNILG9ic2VydmFkbywxLDEKMjAyNC0wOS0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjQtMTAtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDI0LTExLTAxLFNILG9ic2VydmFkbywxLDEKMjAyNC0xMi0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjUtMDEtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDI1LTAyLTAxLFNILG9ic2VydmFkbywxLDEKMjAyNS0wMy0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjUtMDQtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDI1LTA1LTAxLFNILG9ic2VydmFkbywxLDEKMjAyNS0wNi0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjUtMDctMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDI1LTA4LTAxLFNILG9ic2VydmFkbywxLDEKMjAyNS0wOS0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjUtMTAtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDI1LTExLTAxLFNILG9ic2VydmFkbywxLDEKMjAyNS0xMi0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjYtMDEtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDI2LTAyLTAxLFNILG9ic2VydmFkbywxLDEKMjAyNi0wMy0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjYtMDQtMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDI2LTA1LTAxLFNILG9ic2VydmFkbywxLDEKMjAyNi0wNi0wMSxTSCxvYnNlcnZhZG8sMSwxCjIwMjYtMDctMDEsU0gsb2JzZXJ2YWRvLDEsMQoyMDI2LTA4LTAxLFNILG9ic2VydmFkbywxLDEK\", BinaryEncoding.Base64), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Encabezados = Table.PromoteHeaders(Fuente, [PromoteAllScalars=true]),",
                "    Nulos = Table.ReplaceValue(Encabezados, \"\", null, Replacer.ReplaceValue, Table.ColumnNames(Encabezados)),",
                "    Tipos = Table.TransformColumnTypes(Nulos, {{\"Mes\", type date}, {\"Activo\", type text}, {\"Estado\", type text}, {\"Crudo_valido\", Int64.Type}, {\"Gas_valido\", Int64.Type}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "915ddfdc-7d82-5a67-83a7-a56247c299cd",
        "fromTable": "Produccion",
        "fromColumn": "Mes",
        "toTable": "Calendario",
        "toColumn": "Mes",
        "fromCardinality": "many",
        "toCardinality": "one",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "1bacf330-7fa7-5940-a3e3-a51062351573",
        "fromTable": "Produccion",
        "fromColumn": "Activo",
        "toTable": "Activos",
        "toColumn": "Activo",
        "fromCardinality": "many",
        "toCardinality": "one",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "c742f927-dd53-504f-9f07-25e0315edcdc",
        "fromTable": "Precios",
        "fromColumn": "Mes",
        "toTable": "Calendario",
        "toColumn": "Mes",
        "fromCardinality": "many",
        "toCardinality": "one",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "2f45c605-0cf0-5b86-b6e7-17b9dad78418",
        "fromTable": "Cobertura",
        "fromColumn": "Mes",
        "toTable": "Calendario",
        "toColumn": "Mes",
        "fromCardinality": "many",
        "toCardinality": "one",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "c4313e0c-7964-52f2-84d3-91babb27bcd1",
        "fromTable": "Cobertura",
        "fromColumn": "Activo",
        "toTable": "Activos",
        "toColumn": "Activo",
        "fromCardinality": "many",
        "toCardinality": "one",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Produccion\", \"Precios\", \"Activos\", \"Calendario\", \"Cobertura\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}
